'use strict';
const APP_STORAGE='wwn_app_v6';
const appSaved=JSON.parse(localStorage.getItem(APP_STORAGE)||'null')||{};
let appState=Object.assign({audio:true,tts:true,fog:true,autoWeather:true,session:8,combatRound:2,lastOracle:null},appSaved);
const ORACLES={acao:['Confronto Direto','Mudança Repentina','Oportunidade Arriscada','Recurso Inesperado','Obstáculo Crescente','Sinal Ambíguo'],encontro:['Patrulha local','Mercadores cansados','Predador faminto','Exploradores rivais','Mensageiro ferido','Viajante perdido'],rumor:['Algo antigo despertou','Uma rota desapareceu','Um senhor local procura ajuda','Há luzes na floresta','Uma ruína foi aberta','Uma caravana não chegou'],perigo:['Ameaça próxima','Terreno instável','Tempo severo','Emboscada possível','Doença ou veneno','Conflito entre facções'],descoberta:['Marcas antigas','Passagem escondida','Fonte de água','Sinais de ocupação','Artefato incomum','Vista privilegiada'],reacao:['Hostil','Desconfiada','Cautelosa','Neutra','Curiosa','Favorável'],moral:['Quebrando','Baixa','Instável','Firme','Alta','Fanática'],instinto:['Proteger território','Buscar alimento','Evitar conflito','Impressionar rivais','Obter vantagem','Escapar'],virada:['Chega reforço','O objetivo muda','Algo desaba','Uma verdade aparece','O tempo se esgota','Um aliado muda de lado']};
function saveApp(){localStorage.setItem(APP_STORAGE,JSON.stringify(appState))}
function appSvg(id,cls='ui'){return`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><use href="assets/ui-icons.svg#${id}"></use></svg>`}
function appGo(v){showView(v);window.scrollTo({top:0,behavior:'instant'});if(v==='favoritos')renderFavorites();if(v==='sessoes')renderSessions();if(v==='configuracoes')renderSettings();if(v==='mestre')renderMasterV6()}
function appBack(){appGo('inicio')}
function rollSkill(name,bonus=0){const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6),total=a+b+bonus;const el=document.getElementById('skillResult');if(el){el.innerHTML=`<b>${name}</b><span>${a} + ${b}${bonus>=0?` + ${bonus}`:''} = <strong>${total}</strong></span>`;el.classList.add('show')}toast(`${name}: ${total}`)}
function oracleRoll(type){const values=ORACLES[type]||ORACLES.acao;const die=1+Math.floor(Math.random()*20);const result=values[Math.floor((die-1)/20*values.length)];appState.lastOracle={type,die,result,time:Date.now()};saveApp();renderMasterV6();toast(`Oráculo: ${result}`)}
function renderMasterV6(){const die=document.getElementById('oracleDie'),kind=document.getElementById('oracleKind'),res=document.getElementById('oracleText');if(!die||!kind||!res)return;const o=appState.lastOracle;if(!o){die.textContent='—';kind.textContent='Nenhum resultado';res.textContent='Role um dos oráculos rápidos.';return}die.textContent=o.die;kind.textContent=o.type.toUpperCase();res.textContent=o.result}
function combatAttack(){const roll=1+Math.floor(Math.random()*20),bonus=5,total=roll+bonus,target=12,hit=total>=target;const die=document.getElementById('combatDie'),tot=document.getElementById('combatTotal'),out=document.getElementById('combatOutcome');if(die)die.textContent=roll;if(tot)tot.textContent=total;if(out){out.textContent=hit?'ACERTO!':'ERRO';out.className=hit?'hit':'muted'}note(`Ataque: ${roll} + ${bonus} = ${total} contra CA ${target}.`)}
function combatDamage(){const d=1+Math.floor(Math.random()*8),total=d+3;const el=document.getElementById('damageTotal');if(el)el.textContent=total;note(`Dano: ${d} + 3 = ${total}.`)}
function nextCombatRound(){appState.combatRound++;saveApp();const el=document.getElementById('combatRound');if(el)el.textContent=appState.combatRound;nextRound()}
function toggleSetting(k){appState[k]=!appState[k];saveApp();renderSettings();if(k==='fog'){document.body.classList.toggle('fog-disabled',!appState.fog);appApplyFog()}}
function renderSettings(){document.querySelectorAll('[data-setting]').forEach(el=>el.classList.toggle('on',!!appState[el.dataset.setting]));document.body.classList.toggle('fog-disabled',!appState.fog)}
function renderSessions(){const box=document.getElementById('sessionsList');if(!box)return;box.innerHTML=[{n:appState.session,title:'A Passagem nas Colinas Cinzentas',meta:`Dia ${clock.day} • ${clockLabel()} • ${events.length} acontecimentos`},{n:appState.session-1,title:'O Vale do Sussurro',meta:'Encerrada • 4 POIs registrados'},{n:appState.session-2,title:'Estrada para Ferranor',meta:'Encerrada • jornada e combate'}].map((s,i)=>`<button class="session-card orn-card" onclick="${i===0?"appGo('explorar')":"toast('Sessão registrada no diário.')"}">${appSvg(i===0?'d20':'book')}<span><b>Sessão ${s.n} — ${s.title}</b><small>${s.meta}</small></span><span class="mini-arrow">›</span></button>`).join('')}
function renderFavorites(){const box=document.getElementById('favoritesList');if(!box)return;const rows=[];for(const id of knownPOIs){const t=byKey[id];if(!t?.poi)continue;const p=POIS[t.poi];rows.push(`<button class="fav-card orn-card" onclick="appGo('explorar');wwnSelectedIndex=world.indexOf(byKey['${id}']);wwnRenderMap();requestAnimationFrame(()=>wwnCenterOn(wwnSelectedIndex))"><span class="fav-thumb" style="background-image:url('${p.asset}')"></span><span><b>${escapeHTML(p.name)}</b><small>${escapeHTML(BASES[t.base].name)} • Q ${t.q} R ${t.r}</small></span></button>`)}box.innerHTML=rows.length?rows.join(''):'<div class="orn-card" style="padding:20px;text-align:center;opacity:.65">Descubra POIs no Atlas para adicioná-los aos favoritos do mundo.</div>'}
function appApplyFog(){if(typeof world==='undefined')return;document.querySelectorAll('#map .hex').forEach((e,i)=>{e.querySelector('.fog-unknown')?.remove();if(!appState.fog)return;const t=world[i];if(!t)return;const f=document.createElement('div');f.className='fog-unknown';if(t.visited)f.style.opacity='.04';else if(t.seen)f.style.opacity='.28';else f.style.opacity='.97';e.appendChild(f)})}
if(typeof render==='function'){const _render=render;render=function(){_render();appApplyFog()}}
if(typeof wwnRenderMap==='function'){const _wwnRenderMap=wwnRenderMap;wwnRenderMap=function(){_wwnRenderMap();appApplyFog()};render=wwnRenderMap}
function appRefreshSummary(){const hp=document.getElementById('homeWorldSummary');if(hp)hp.textContent=`${world.filter(t=>t.seen).length} hexes vistos • ${knownPOIs.size} POIs • Dia ${clock.day}`;const cr=document.getElementById('combatRound');if(cr)cr.textContent=appState.combatRound;renderMasterV6();renderSettings()}
const _showViewV6=showView;showView=function(v){_showViewV6(v);document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));if(v==='inicio')appRefreshSummary();if(v==='favoritos')renderFavorites();if(v==='sessoes')renderSessions();if(v==='configuracoes')renderSettings();if(v==='mestre')renderMasterV6();if(v==='explorar')requestAnimationFrame(appApplyFog)};
function initAppV6(){appRefreshSummary();renderSessions();renderFavorites();renderSettings();appApplyFog();const initial=document.getElementById('inicio');if(initial){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));initial.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.v==='inicio'))}}
initAppV6();