'use strict';
/* GAME_RUNTIME_V26 — manuais PDF/TXT em IndexedDB + busca local + integração com RAG existente. */
const GAME26_STORAGE='wwn_game_runtime_v26';
const GAME26_DB='wwn_manual_corpus_v26';
const GAME26_STORE='chunks';
const GAME26_PDFJS='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs';
const GAME26_PDFWORKER='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';
const game26Default={sources:[],busy:false,progress:0,status:'',lastError:'',lastQuery:'',lastResults:[],ready:false,lastImport:0};
let game26=Object.assign({},game26Default,JSON.parse(localStorage.getItem(GAME26_STORAGE)||'null')||{});
let game26Cache=[];
let game26DbPromise=null;
function game26Save(){localStorage.setItem(GAME26_STORAGE,JSON.stringify({sources:game26.sources,busy:false,progress:0,status:game26.status,lastError:game26.lastError,lastQuery:game26.lastQuery,lastResults:game26.lastResults,ready:game26.ready,lastImport:game26.lastImport}))}
function game26Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game26Toast(s){try{if(typeof toast==='function')toast(s)}catch(e){}}
function game26Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game26OpenDb(){if(game26DbPromise)return game26DbPromise;game26DbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(GAME26_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(GAME26_STORE)){const st=db.createObjectStore(GAME26_STORE,{keyPath:'id'});st.createIndex('sourceId','sourceId',{unique:false});st.createIndex('sourceName','sourceName',{unique:false})}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Falha ao abrir a biblioteca local.'))});return game26DbPromise}
async function game26AllChunks(){const db=await game26OpenDb();return new Promise((resolve,reject)=>{const tx=db.transaction(GAME26_STORE,'readonly'),r=tx.objectStore(GAME26_STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function game26PutChunks(rows){if(!rows.length)return;const db=await game26OpenDb();await new Promise((resolve,reject)=>{const tx=db.transaction(GAME26_STORE,'readwrite'),st=tx.objectStore(GAME26_STORE);for(const row of rows)st.put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function game26DeleteSource(sourceId){const db=await game26OpenDb();await new Promise((resolve,reject)=>{const tx=db.transaction(GAME26_STORE,'readwrite'),idx=tx.objectStore(GAME26_STORE).index('sourceId'),range=IDBKeyRange.only(sourceId),r=idx.openCursor(range);r.onsuccess=()=>{const c=r.result;if(c){c.delete();c.continue()}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});game26.sources=game26.sources.filter(x=>x.id!==sourceId);game26Cache=game26Cache.filter(x=>x.sourceId!==sourceId);game26Save();game26RenderAll()}
async function game26ClearAll(){if(!confirm('Apagar todos os manuais indexados deste dispositivo?'))return;const db=await game26OpenDb();await new Promise((resolve,reject)=>{const tx=db.transaction(GAME26_STORE,'readwrite'),r=tx.objectStore(GAME26_STORE).clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)});game26.sources=[];game26Cache=[];game26.lastResults=[];game26.lastQuery='';game26.ready=false;game26.status='Biblioteca PDF vazia.';game26Save();game26RenderAll()}
function game26Norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ')}
function game26Terms(q){const stop=new Set(['para','com','como','uma','uns','das','dos','que','por','sem','sobre','qual','quando','onde','isso','esta','esse','essa','the','and','with','from','into']);return [...new Set(game26Norm(q).split(/\s+/).filter(x=>x.length>2&&!stop.has(x)))]}
function game26Score(q,row){const terms=game26Terms(q),txt=game26Norm(`${row.sourceName||''} ${row.text||''}`);if(!terms.length)return 0;let score=0;for(const t of terms){const n=txt.split(t).length-1;if(n)score+=4+Math.min(12,n*2)}const phrase=game26Norm(q).trim();if(phrase&&txt.includes(phrase))score+=24;return score}
function game26Search(q,limit=8){const query=String(q||'').trim();if(!query)return[];return game26Cache.map(row=>({row,score:game26Score(query,row)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
function game26ChunkText(text,meta){const clean=String(text||'').replace(/\r/g,'').replace(/[\t ]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();if(!clean)return[];const out=[];let start=0,part=0;while(start<clean.length){let end=Math.min(clean.length,start+1500);if(end<clean.length){const cut=Math.max(clean.lastIndexOf('\n\n',end),clean.lastIndexOf('. ',end));if(cut>start+850)end=cut+1}const txt=clean.slice(start,end).trim();if(txt)out.push({id:`${meta.sourceId}_${meta.page||0}_${part}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,sourceId:meta.sourceId,sourceName:meta.sourceName,page:meta.page||0,title:meta.title||meta.sourceName,text:txt,stamp:Date.now()});start=end;part++}return out}
async function game26LoadCache(){try{game26Cache=await game26AllChunks();game26.ready=true;game26.status=`${game26Cache.length} trechos carregados.`;game26.lastError=''}catch(e){game26.lastError=e?.message||String(e);game26.status='Falha ao carregar os manuais.'}game26Save();game26HookRag();game26RenderAll()}
async function game26LoadPdfJs(){if(window.__game26PdfJs)return window.__game26PdfJs;const mod=await import(GAME26_PDFJS);if(mod?.GlobalWorkerOptions)mod.GlobalWorkerOptions.workerSrc=GAME26_PDFWORKER;window.__game26PdfJs=mod;return mod}
function game26SetBusy(on,status='',progress=0){game26.busy=on;game26.status=status;game26.progress=Math.max(0,Math.min(100,Math.round(progress||0)));game26Save();game26RenderAll()}
async function game26ImportPdf(file){if(!file)return;const sourceId=`pdf_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;game26SetBusy(true,`Abrindo ${file.name}…`,2);try{const pdfjs=await game26LoadPdfJs(),buf=await file.arrayBuffer(),pdf=await pdfjs.getDocument({data:buf}).promise,rows=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),tc=await page.getTextContent(),text=(tc.items||[]).map(x=>x.str||'').join(' ').replace(/\s+/g,' ').trim();rows.push(...game26ChunkText(text,{sourceId,sourceName:file.name,page:p,title:file.name}));if(p%8===0||p===pdf.numPages)game26SetBusy(true,`Indexando ${file.name} • página ${p}/${pdf.numPages}`,5+(p/pdf.numPages)*78)}await game26PutChunks(rows);game26.sources.unshift({id:sourceId,name:file.name,type:'pdf',pages:pdf.numPages,chunks:rows.length,size:file.size||0,stamp:Date.now()});game26.sources=game26.sources.slice(0,40);game26Cache.push(...rows);game26.lastImport=Date.now();game26.ready=true;game26.status=`${file.name} indexado: ${pdf.numPages} páginas, ${rows.length} trechos.`;game26.lastError='';game26Save();game26Log('rules',`Manual importado: ${file.name}`,`${pdf.numPages} páginas • ${rows.length} trechos`);game26HookRag();game26RenderAll();game26Toast('Manual PDF indexado no dispositivo.')}catch(e){game26.lastError=e?.message||String(e);game26.status='Falha ao indexar o PDF.';game26Save();game26RenderAll()}finally{game26.busy=false;game26.progress=0;game26Save();game26RenderAll()}}
async function game26ImportText(file){if(!file)return;const sourceId=`txt_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;game26SetBusy(true,`Lendo ${file.name}…`,15);try{const text=await file.text();const rows=game26ChunkText(text,{sourceId,sourceName:file.name,page:0,title:file.name});await game26PutChunks(rows);game26.sources.unshift({id:sourceId,name:file.name,type:'text',pages:0,chunks:rows.length,size:file.size||0,stamp:Date.now()});game26Cache.push(...rows);game26.lastImport=Date.now();game26.ready=true;game26.status=`${file.name} indexado: ${rows.length} trechos.`;game26.lastError='';game26Save();game26HookRag();game26Log('rules',`Referência importada: ${file.name}`,`${rows.length} trechos`);game26RenderAll()}catch(e){game26.lastError=e?.message||String(e);game26.status='Falha ao importar o arquivo.';game26Save();game26RenderAll()}finally{game26.busy=false;game26.progress=0;game26Save();game26RenderAll()}}
async function game26Import(file){if(!file)return;const n=file.name.toLowerCase();if(n.endsWith('.pdf'))return game26ImportPdf(file);return game26ImportText(file)}
function game26DoSearch(){const input=document.getElementById('g26q'),q=input?.value.trim()||game26.lastQuery;if(!q)return;game26.lastQuery=q;game26.lastResults=game26Search(q,8).map(x=>({sourceName:x.row.sourceName,page:x.row.page||0,text:x.row.text.slice(0,500),score:x.score,id:x.row.id}));game26Save();game26RenderAll()}
function game26SourceOptions(){return game26.sources.map(s=>`<option value="${game26Esc(s.id)}">${game26Esc(s.name)}</option>`).join('')}
async function game26ExportCorpus(){if(!game26Cache.length){game26Toast('Não há corpus para exportar.');return}const payload={format:'BRASEIRO_WWN_MANUAL_CORPUS_V26',createdAt:new Date().toISOString(),sources:game26.sources,chunks:game26Cache};const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`wwn-manual-corpus-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),700)}
async function game26ImportCorpus(file){if(!file)return;game26SetBusy(true,'Restaurando corpus…',10);try{const p=JSON.parse(await file.text());if(p?.format!=='BRASEIRO_WWN_MANUAL_CORPUS_V26'||!Array.isArray(p.chunks))throw new Error('Corpus incompatível.');await game26PutChunks(p.chunks);game26.sources=Array.isArray(p.sources)?p.sources:game26.sources;game26Cache=await game26AllChunks();game26.ready=true;game26.status=`Corpus restaurado: ${game26Cache.length} trechos.`;game26.lastError='';game26Save();game26HookRag();game26RenderAll()}catch(e){game26.lastError=e?.message||String(e);game26.status='Falha ao restaurar o corpus.';game26Save();game26RenderAll()}finally{game26.busy=false;game26.progress=0;game26Save()}}
function game26MergedDocs(){const legacy=(()=>{try{return Array.isArray(game13?.docs)?game13.docs:[]}catch(e){return[]}})();const pdf=game26Cache.map(x=>({id:x.id,title:`${x.sourceName}${x.page?` • p. ${x.page}`:''}`,text:x.text,sourceId:x.sourceId,page:x.page,sourceName:x.sourceName}));return legacy.concat(pdf)}
function game26HookRag(){try{if(typeof game22Docs==='function'&&!window.__game26DocsHooked){window.__game26DocsHooked=true;window.game22Docs=()=>game26MergedDocs()}}catch(e){}try{if(typeof game13Context==='function'&&!window.__game26ContextHooked){window.__game26ContextHooked=true;const old=game13Context;window.game13Context=function(q){const direct=game26Search(q,4).map(x=>`[${x.row.sourceName}${x.row.page?` p.${x.row.page}`:''}] ${x.row.text}`).join('\n\n');return (direct||old(q)).slice(0,4200)}}}catch(e){}try{if(typeof g11Ctx==='function'&&!window.__game26GeminiHooked){window.__game26GeminiHooked=true;const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action);const query=[action,c?.terrain,c?.feature,c?.poi,c?.objective?.title||c?.objective||''].filter(Boolean).join(' '),refs=game26Search(query,4);if(refs.length)c.manualCorpus=refs.map((x,i)=>`[M${i+1}] ${x.row.sourceName}${x.row.page?` p.${x.row.page}`:''}: ${x.row.text}`).join('\n\n').slice(0,4200);return c}}}catch(e){}}
function game26Inject(){const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game26Master')){const a=document.getElementById('game22Rules')||document.getElementById('game25Master')||document.getElementById('gameMasterRuntime');a?.insertAdjacentHTML('afterend','<div id="game26Master" class="game26-runtime"></div>')}const cfg=document.getElementById('configuracoes');if(cfg&&!document.getElementById('game26Config'))cfg.insertAdjacentHTML('beforeend','<div id="game26Config" class="game26-runtime"></div>')}
function game26RenderMaster(){const el=document.getElementById('game26Master');if(!el)return;const results=game26.lastResults||[];el.innerHTML=`<div class="section-cap">Manuais & RAG</div><div class="game26-card orn-card"><div class="game26-head"><div><span class="game26-label">Corpus local persistente</span><h3>${game26.sources.length} fonte(s) • ${game26Cache.length} trechos</h3></div><span class="game26-chip ${game26.ready?'ok':'warn'}">${game26.ready?'índice pronto':'carregando'}</span></div><div class="game26-grid"><div class="game26-kpi"><b>${game26.sources.reduce((n,s)=>n+(s.pages||0),0)}</b><small>páginas PDF</small></div><div class="game26-kpi"><b>${game26Cache.length}</b><small>trechos</small></div><div class="game26-kpi"><b>${game26.lastResults?.length||0}</b><small>resultados</small></div></div><div class="game26-actions"><button class="primary" onclick="document.getElementById('g26files').click()">Importar manuais</button><button onclick="game26ExportCorpus()">Exportar corpus</button><button onclick="document.getElementById('g26corpus').click()">Restaurar corpus</button><button class="danger" onclick="game26ClearAll()">Limpar PDF/RAG</button></div><input id="g26files" class="game26-file" type="file" accept=".pdf,.txt,.md,.json,application/pdf,text/plain" multiple onchange="game26ImportMany(this.files)"><input id="g26corpus" class="game26-file" type="file" accept=".json,application/json" onchange="game26ImportCorpus(this.files[0])">${game26.busy?`<div class="game26-progress"><i style="width:${game26.progress}%"></i></div>`:''}<div class="game26-status ${game26.busy?'busy':game26.lastError?'bad':'ok'}">${game26Esc(game26.status||'Pronto para importar manuais.')}${game26.lastError?` • ${game26Esc(game26.lastError)}`:''}</div><div class="game26-search"><input id="g26q" value="${game26Esc(game26.lastQuery)}" placeholder="Buscar regra, classe, Focus, Shock, viagem..." onkeydown="if(event.key==='Enter')game26DoSearch()"><button onclick="game26DoSearch()">Buscar</button></div>${results.length?`<div class="game26-results">${results.map(r=>`<div class="game26-result"><b>${game26Esc(r.sourceName)}${r.page?` • p. ${r.page}`:''}</b><small>relevância ${r.score}</small><p>${game26Esc(r.text)}</p></div>`).join('')}</div>`:''}<div class="game26-note">PDFs ficam somente neste dispositivo, em IndexedDB. A busca e o Gemini usam os trechos recuperados; nenhuma regra ausente é inventada para completar lacunas.</div></div>`}
function game26RenderConfig(){const el=document.getElementById('game26Config');if(!el)return;el.innerHTML=`<div class="section-cap">Biblioteca de manuais</div><div class="game26-card orn-card"><div class="game26-head"><div><span class="game26-label">Armazenamento local</span><h3>${game26.sources.length?`${game26.sources.length} fontes indexadas`:'Nenhum PDF indexado'}</h3></div><span class="game26-chip ${game26Cache.length?'ok':'warn'}">${game26Cache.length} trechos</span></div><div class="game26-sources">${game26.sources.map(s=>`<div class="game26-source"><div class="game26-source-head"><div><b>${game26Esc(s.name)}</b><small>${s.type==='pdf'?`${s.pages} páginas • `:''}${s.chunks} trechos • ${new Date(s.stamp).toLocaleDateString('pt-BR')}</small></div><div class="game26-source-actions"><button class="game26-mini" onclick="game26Remove('${game26Esc(s.id)}')">Remover</button></div></div></div>`).join('')||'<div class="game26-note">Importe os manuais na aba Mestre. Depois disso a consulta de regras e o contexto do Gemini passam a usar o corpus automaticamente.</div>'}</div></div>`}
function game26RenderAll(){game26Inject();game26RenderMaster();game26RenderConfig();game26Save()}
async function game26ImportMany(files){for(const f of Array.from(files||[]))await game26Import(f);game26RenderAll()}
async function game26Remove(id){const s=game26.sources.find(x=>x.id===id);if(!s)return;if(!confirm(`Remover ${s.name} da biblioteca local?`))return;await game26DeleteSource(id);game26.status=`${s.name} removido.`;game26Save();game26RenderAll()}
function game26Hook(){if(window.__game26Hooked)return;window.__game26Hooked=true;game26HookRag();try{if(typeof showView==='function'){const old=showView;window.showView=function(v){old(v);if(v==='mestre'||v==='configuracoes')requestAnimationFrame(game26RenderAll)}}}catch(e){}setInterval(game26HookRag,1200)}
function game26Init(){game26Hook();game26RenderAll();game26LoadCache()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game26Init);else game26Init();
