'use strict';
/* GAME_RUNTIME_V10 — PLAYER_ACTION livre com despacho para os sistemas existentes. */
const GAME10_STORAGE='wwn_game_runtime_v10';
const game10Default={history:[],lastIntent:'',lastResponse:'',count:0};
function game10Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game10Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game10=game10Merge(game10Default,JSON.parse(localStorage.getItem(GAME10_STORAGE)||'null'));
function game10Save(){localStorage.setItem(GAME10_STORAGE,JSON.stringify(game10))}
function game10Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game10Toast(s){if(typeof toast==='function')toast(s)}
function game10Log(role,text,intent=''){game10.history.unshift({role,text,intent,time:Date.now()});game10.history=game10.history.slice(0,30);game10Save()}
function game10Tile(){try{return currentTile()}catch(e){return null}}
function game10Poi(){const t=game10Tile();try{return t?.poi&&knownPOIs.has(key(t.q,t.r))?POIS[t.poi]:null}catch(e){return null}}
function game10Terrain(){const t=game10Tile();try{return BASES[t.base].name}catch(e){return'território atual'}}
function game10Intent(text){const s=String(text||'').trim().toLowerCase();if(!s)return'vazio';if(/atac|lutar|combate|enfrent|golpear|matar/.test(s))return'combate';if(/viaj|ir para|seguir|andar|mover|partir|rota|destino/.test(s))return'viagem';if(/explor|procur|vasculh|examinar terreno|mapear/.test(s))return'explorar';if(/investig|examinar|inspec|olhar o local|pista|sinal/.test(s))return'investigar';if(/falar|convers|pergunt|dialog|rumor|informação|informacao/.test(s))return'conversar';if(/acampar|descans|dormir|repousar|parar/.test(s))return'descanso';if(/observar|vigiar|espreit|escutar|perceber/.test(s))return'observar';if(/comer|ração|racao|suprimento|forrage|buscar comida|água|agua/.test(s))return'recursos';if(/missão|missao|objetivo|tarefa|quest/.test(s))return'missao';return'livre'}
function game10Response(intent,text){const poi=game10Poi(),place=poi?.name||game10Terrain();const q=typeof game8ActiveQuest==='function'?game8ActiveQuest():null;const table={
 combate:`O Mestre registra sua intenção de confronto em ${place}. Se houver uma ameaça ativa, a cena será convertida em combate; caso contrário, a atitude hostil ficará registrada no contexto.`,
 viagem:`Você indica que quer deixar ${place}. O Atlas passa a ser a autoridade para escolher o próximo hex e manter a jornada adjacente.`,
 explorar:`Você dedica atenção ao território de ${place}. O Mestre resolve a exploração pelo motor do Atlas e atualiza descobertas, tempo e registros.`,
 investigar:`Você concentra a ação nos sinais e detalhes de ${place}. Se houver um local oculto neste hex, o sistema tentará identificá-lo antes de qualquer entrada.`,
 conversar:`Você procura alguém com quem falar em ${place}. O Mestre puxa um NPC ou fonte local e registra o que for revelado na memória da campanha.`,
 descanso:`Você decide interromper a marcha em ${place}. O relógio, acampamento e estado da expedição serão atualizados pelo motor.`,
 observar:`Você evita agir de imediato e lê a situação. O Mestre atualiza a cena com o que é perceptível sem deslocar o grupo.`,
 recursos:`Você procura sustento ou reorganiza suprimentos. O sistema encaminha a ação ao controle de expedição.`,
 missao:q?`Seu objetivo ativo é “${q.title}”. O Mestre mantém esse objetivo ligado às descobertas e decisões da sessão.`:'Não há uma missão ativa registrada agora.',
 livre:`Sua intenção foi registrada: “${text}”. O Mestre mantém a cena em ${place}, preserva o contexto e aguarda a consequência dessa ação no próximo turno.`
};return table[intent]||table.livre}
function game10Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game10Console')){const a=document.getElementById('game9Play')||document.getElementById('game8Home')||document.getElementById('gameCampaignState');a?.insertAdjacentHTML('afterend','<div id="game10Console" class="game10-runtime"></div>')}const master=document.getElementById('mestre');if(master&&!document.getElementById('game10Master')){const a=document.getElementById('game9Master')||document.getElementById('game8Master')||document.getElementById('gameMasterRuntime');a?.insertAdjacentHTML('afterend','<div id="game10Master" class="game10-runtime"></div>')}}
function game10Render(){game10Inject();const el=document.getElementById('game10Console');if(el){el.innerHTML=`<div class="section-cap">Sua ação</div><div class="game10-console orn-card"><h3>Diga ao Mestre o que você faz</h3><div class="game10-inputrow"><input id="game10Action" class="game10-input" maxlength="240" placeholder="Ex.: examino as ruínas, falo com a batedora, sigo para o norte..." onkeydown="if(event.key==='Enter')game10Submit()"><button class="game10-send" onclick="game10Submit()">Enviar</button></div><div class="game10-help">O sistema interpreta a intenção e encaminha para exploração, viagem, conversa, descanso ou confronto.</div>${game10.lastResponse?`<div class="game10-response"><span>Mestre</span>${game10Esc(game10.lastResponse)}${game10.lastIntent?`<i class="game10-intent">${game10Esc(game10.lastIntent)}</i>`:''}</div>`:''}${game10.history.length?`<div class="game10-history">${game10.history.slice(0,4).map(h=>`<div class="game10-history-item"><b>${h.role==='player'?'Você':'Mestre'}</b><small>${game10Esc(h.text)}</small>${h.intent?`<i class="game10-intent">${game10Esc(h.intent)}</i>`:''}</div>`).join('')}</div>`:''}</div>`}const ma=document.getElementById('game10Master');if(ma){ma.innerHTML=`<div class="section-cap">PLAYER_ACTION</div><div class="game10-masterlog orn-card">${game10.history.length?game10.history.slice(0,10).map(h=>`<div class="game10-history-item ${h.role}"><b>${h.role==='player'?'Jogador':'Mestre'}</b><small>${game10Esc(h.text)}</small>${h.intent?`<i class="game10-intent">${game10Esc(h.intent)}</i>`:''}</div>`).join(''):'<div class="game10-history-item gm"><small>Nenhuma ação livre registrada nesta sessão.</small></div>'}</div>`}}
function game10Dispatch(intent,text){if(intent==='combate'){try{if(typeof game8StartEncounter==='function'&&game8?.lastEncounter?.hostile){game8StartEncounter();return}}catch(e){}if(typeof appGo==='function')appGo('confronto');return}if(intent==='viagem'){if(typeof appGo==='function')appGo('explorar');game10Toast('Selecione o hex de destino no Atlas.');return}if(intent==='explorar'){try{if(typeof explore==='function')explore()}catch(e){}return}if(intent==='investigar'){try{if(typeof inspectPOI==='function')inspectPOI()}catch(e){}return}if(intent==='conversar'){try{if(typeof game9Talk==='function'){game9Talk(false);return}}catch(e){}try{if(typeof game8GenerateRumor==='function')game8GenerateRumor()}catch(e){}return}if(intent==='descanso'){try{if(typeof camp==='function')camp()}catch(e){}return}if(intent==='observar'){try{if(typeof game8Scout==='function')game8Scout()}catch(e){}return}if(intent==='recursos'){try{if(typeof game8Forage==='function')game8Forage()}catch(e){}return}if(intent==='missao'){if(typeof appGo==='function')appGo('sessoes');return}}
function game10Submit(){const input=document.getElementById('game10Action');if(!input)return;const text=input.value.trim();if(!text){game10Toast('Digite sua ação.');return}const intent=game10Intent(text),response=game10Response(intent,text);game10.count++;game10.lastIntent=intent;game10.lastResponse=response;game10Log('player',text,intent);game10Log('gm',response,intent);game10Save();try{game10Dispatch(intent,text)}catch(e){}try{if(typeof game9AfterAction==='function'&&intent==='livre')game9AfterAction('Ação livre do jogador',text)}catch(e){}try{if(typeof gameLog==='function')gameLog('player','PLAYER_ACTION',`${text} • intenção: ${intent}`)}catch(e){}input.value='';game10Render();try{if(typeof game9RenderAll==='function')game9RenderAll()}catch(e){}}
function game10Hook(){if(window.__game10Hooked)return;window.__game10Hooked=true;try{if(typeof showView==='function'){const old=showView;showView=function(v){old(v);requestAnimationFrame(game10Render)}}}catch(e){}try{if(typeof game9RenderAll==='function'){const old9=game9RenderAll;game9RenderAll=function(){old9();game10Render()}}}catch(e){}}
function game10Init(){game10Hook();game10Render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game10Init);else game10Init();
