'use strict';
/* GAME_RUNTIME_V30 — diretor de campanha: threads, pistas, cânone, segredos e seleção de cenas. Sem UI. */
const GAME30_STORAGE='wwn_game_runtime_v30';
const game30Default={threads:[],clues:[],canon:[],secrets:[],sceneHistory:[],questions:[],summary:'',lastScene:null,lastBootstrap:0,seq:0};
let game30=Object.assign({},game30Default,JSON.parse(localStorage.getItem(GAME30_STORAGE)||'null')||{});
function game30Save(){try{localStorage.setItem(GAME30_STORAGE,JSON.stringify(game30))}catch(e){}}
function game30Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game30Id(prefix){return`${prefix}${Date.now()}_${++game30.seq}`}
function game30Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game30Emit(t,p){try{window.WWN_ENGINE?.emit?.(t,p)}catch(e){}}
function game30CurrentQuest(){try{return typeof game14ActiveQuest==='function'?game14ActiveQuest():typeof game8ActiveQuest==='function'?game8ActiveQuest():null}catch(e){return null}}
function game30CurrentPlace(){try{const t=currentTile();if(t?.poi&&knownPOIs.has(key(t.q,t.r)))return POIS[t.poi]?.name||BASES[t.base]?.name;return BASES[t.base]?.name||''}catch(e){return''}}
function game30Bootstrap(){if(game30.threads.length)return;const q=game30CurrentQuest();if(q)game30.threads.push({id:game30Id('th'),title:q.title||'Objetivo principal',premise:q.desc||'',type:'quest',urgency:3,progress:Number(q.progress||0),max:Number(q.max||4),status:'open',public:true,source:'quest'});for(const f of (window.gameState?.factions||[]).slice(0,4))game30.threads.push({id:game30Id('th'),title:`Projeto de ${f.name}`,premise:f.goal||'',type:'faction',urgency:Math.max(1,Math.min(5,Math.ceil((Number(f.clock||0)/Math.max(1,Number(f.max||6)))*5))),progress:Number(f.clock||0),max:Number(f.max||6),status:'open',public:false,source:f.name});try{for(const id of knownPOIs||[]){const t=byKey[id],p=t?.poi?POIS[t.poi]:null;if(p?.type==='perigoso')game30.threads.push({id:game30Id('th'),title:`Segredo de ${p.name}`,premise:'Local perigoso conhecido, mas ainda não plenamente compreendido.',type:'location',urgency:2,progress:enteredPOIs?.has(id)?1:0,max:3,status:'open',public:true,source:id})}}catch(e){}if(!game30.questions.length)game30.questions.push({id:game30Id('q'),text:'O que está mudando nesta região enquanto o personagem age?',status:'open',public:false,created:Date.now()});game30.lastBootstrap=Date.now();game30Save()}
function game30AddCanon(text,source='play',visibility='player'){if(!text)return null;const norm=String(text).trim();if(game30.canon.some(x=>x.text===norm))return game30.canon.find(x=>x.text===norm);const row={id:game30Id('ca'),text:norm,source,visibility,stamp:Date.now()};game30.canon.unshift(row);game30.canon=game30.canon.slice(0,160);game30Save();return row}
function game30AddSecret(text,source='master'){if(!text)return null;const row={id:game30Id('se'),text:String(text).trim(),source,revealed:false,stamp:Date.now()};game30.secrets.unshift(row);game30.secrets=game30.secrets.slice(0,120);game30Save();return row}
function game30RevealSecret(id){const s=game30.secrets.find(x=>x.id===id);if(!s||s.revealed)return null;s.revealed=true;s.revealedAt=Date.now();game30AddCanon(s.text,s.source,'player');game30Emit('campaign.secret.revealed',{id:s.id,text:s.text,source:s.source});game30Save();return s}
function game30AddClue(text,{source='scene',threadId='',visibility='player',strength=1}={}){if(!text)return null;const row={id:game30Id('cl'),text:String(text).trim(),source,threadId,visibility,strength:Number(strength||1),stamp:Date.now()};game30.clues.unshift(row);game30.clues=game30.clues.slice(0,180);if(threadId){const t=game30.threads.find(x=>x.id===threadId);if(t)t.progress=Math.min(Number(t.max||4),Number(t.progress||0)+Math.max(0,Number(strength||1)))}game30Save();game30Emit('campaign.clue',{id:row.id,threadId,text:row.text,visibility});return row}
function game30ThreadScore(t){if(t.status!=='open')return-999;let s=Number(t.urgency||1)*10;const p=Number(t.progress||0),m=Math.max(1,Number(t.max||4));s+=Math.round((p/m)*8);const place=game30CurrentPlace().toLowerCase(),src=String(t.source||'').toLowerCase();if(place&&src&&place.includes(src.split(' ')[0]))s+=8;if(t.type==='quest')s+=6;if(t.type==='faction'&&!t.public)s-=2;return s}
function game30NextThread(){game30Bootstrap();return game30.threads.slice().sort((a,b)=>game30ThreadScore(b)-game30ThreadScore(a))[0]||null}
function game30SceneCandidates(){game30Bootstrap();const open=game30.threads.filter(t=>t.status==='open').sort((a,b)=>game30ThreadScore(b)-game30ThreadScore(a));const place=game30CurrentPlace();const out=[];for(const t of open.slice(0,4)){out.push({id:game30Id('sc'),threadId:t.id,type:t.type==='faction'?'social':t.type==='location'?'discovery':'progress',title:t.title,goal:`Mover a thread “${t.title}” sem contradizer o cânone.`,place,score:game30ThreadScore(t),public:t.public})}if(!out.length)out.push({id:game30Id('sc'),threadId:'',type:'exploration',title:'Exploração aberta',goal:'Apresentar uma situação concreta sem criar fatos mecânicos.',place,score:1,public:true});return out.sort((a,b)=>b.score-a.score)}
function game30ChooseScene(){const sc=game30SceneCandidates()[0];game30.lastScene=sc;game30.sceneHistory.unshift({...sc,stamp:Date.now(),status:'chosen'});game30.sceneHistory=game30.sceneHistory.slice(0,80);game30Save();game30Emit('campaign.scene.chosen',sc);return sc}
function game30ResolveScene(sceneId,outcome={}){const sc=game30.sceneHistory.find(x=>x.id===sceneId)||game30.lastScene;if(!sc)return;sc.status='resolved';sc.resolvedAt=Date.now();sc.outcome=game30Clone(outcome);const t=game30.threads.find(x=>x.id===sc.threadId);if(t&&Number(outcome.progress||0)){t.progress=Math.max(0,Math.min(Number(t.max||4),Number(t.progress||0)+Number(outcome.progress)));if(t.progress>=Number(t.max||4)){t.status='resolved';t.resolvedAt=Date.now();game30AddCanon(`Thread resolvida: ${t.title}.`,'director','player')}}if(outcome.clue)game30AddClue(outcome.clue,{source:sc.title,threadId:sc.threadId,visibility:outcome.visibility||'player',strength:Number(outcome.clueStrength||1)});if(outcome.canon)game30AddCanon(outcome.canon,sc.title,outcome.visibility||'player');game30Save();game30CompactSummary()}
function game30CompactSummary(){const playerCanon=game30.canon.filter(x=>x.visibility==='player').slice(0,20),clues=game30.clues.filter(x=>x.visibility==='player').slice(0,12),threads=game30.threads.filter(x=>x.status==='open'&&x.public).slice(0,8);game30.summary=[threads.length?`Threads abertas: ${threads.map(t=>`${t.title} (${t.progress}/${t.max})`).join('; ')}`:'',playerCanon.length?`Cânone conhecido: ${playerCanon.map(x=>x.text).join(' | ')}`:'',clues.length?`Pistas conhecidas: ${clues.map(x=>x.text).join(' | ')}`:''].filter(Boolean).join('\n').slice(0,6500);game30Save();return game30.summary}
function game30PublicContext(){game30Bootstrap();return{campaignDirector:{nextThread:(()=>{const t=game30NextThread();return t?{title:t.title,premise:t.premise,type:t.type,urgency:t.urgency,progress:t.progress,max:t.max}:null})(),canon:game30.canon.filter(x=>x.visibility==='player').slice(0,20).map(x=>x.text),clues:game30.clues.filter(x=>x.visibility==='player').slice(0,12).map(x=>x.text),openQuestions:game30.questions.filter(x=>x.status==='open'&&x.public).slice(0,8).map(x=>x.text),summary:game30CompactSummary(),instruction:'Segredos não revelados e threads privadas não estão neste contexto. Não os invente nem os revele.'}}}
function game30MasterContext(){return{threads:game30Clone(game30.threads),secrets:game30Clone(game30.secrets),questions:game30Clone(game30.questions),nextScene:game30Clone(game30.lastScene)}}
function game30SyncFromGame(){const q=game30CurrentQuest();if(q){let t=game30.threads.find(x=>x.type==='quest'&&x.title===q.title);if(!t){t={id:game30Id('th'),title:q.title,premise:q.desc||'',type:'quest',urgency:3,progress:Number(q.progress||0),max:Number(q.max||4),status:'open',public:true,source:'quest'};game30.threads.push(t)}else{t.progress=Number(q.progress||t.progress||0);t.max=Number(q.max||t.max||4);if(q.status==='done'||q.done)t.status='resolved'}}for(const f of window.gameState?.factions||[]){let t=game30.threads.find(x=>x.type==='faction'&&x.source===f.name);if(!t){t={id:game30Id('th'),title:`Projeto de ${f.name}`,premise:f.goal||'',type:'faction',urgency:2,progress:Number(f.clock||0),max:Number(f.max||6),status:'open',public:false,source:f.name};game30.threads.push(t)}else{t.progress=Number(f.clock||0);t.max=Number(f.max||6);if(t.progress>=t.max)t.status='resolved'}}game30Save()}
function game30Hook(){if(window.__game30Hook)return;window.__game30Hook=true;try{window.WWN_ENGINE?.on?.('transaction.committed',evt=>{game30SyncFromGame();const tx=evt.payload||{},diff=tx.diff||[];for(const d of diff){if(d.path==='world.knownPois'&&Number(d.after)>Number(d.before))game30AddCanon('Um novo local de interesse foi descoberto.','exploração','player');if(d.path==='player.xp'&&Number(d.after)>Number(d.before))game30AddCanon('O personagem recebeu experiência por um resultado confirmado.','motor','player')}if(/player\.action|skill\.check|saving\.throw|combat/.test(tx.kind||'')){const sc=game30.lastScene||game30ChooseScene();if(sc)game30ResolveScene(sc.id,{progress:tx.diff?.length?1:0})}})}catch(e){}try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(...a){return Object.assign({},old.apply(this,a),game30PublicContext())}}}catch(e){}}
function game30Api(){window.WWN_DIRECTOR=Object.assign(window.WWN_DIRECTOR||{},{version:30,bootstrap:game30Bootstrap,nextThread:game30NextThread,chooseScene:game30ChooseScene,resolveScene:game30ResolveScene,addClue:game30AddClue,addCanon:game30AddCanon,addSecret:game30AddSecret,revealSecret:game30RevealSecret,publicContext:game30PublicContext,masterContext:game30MasterContext,getState:()=>game30})}
function game30Init(){game30Bootstrap();game30SyncFromGame();game30CompactSummary();game30Hook();game30Api();game30Emit('campaign.director.ready',{version:30})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game30Init);else game30Init();
