'use strict';
/* GAME_RUNTIME_V12 — VTT geral: sessão, ficha, combate, contatos, facções e continuidade. */
const GAME12_STORAGE='wwn_game_runtime_v12';
const game12Default={
  activeSession:{id:'s8',title:'Sombras de Gelo e Ferro',status:'ativa',startedAt:Date.now(),checkpoints:0},
  sessions:[],
  characterNotes:'',
  equipmentState:{},
  relations:{},
  sceneFlags:[],
  lastCheckpoint:null
};
function game12Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game12Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game12=game12Merge(game12Default,JSON.parse(localStorage.getItem(GAME12_STORAGE)||'null'));
function game12Save(){localStorage.setItem(GAME12_STORAGE,JSON.stringify(game12))}
function game12Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game12Toast(s){if(typeof toast==='function')toast(s)}
function game12Log(kind,title,detail=''){if(typeof gameLog==='function')gameLog(kind,title,detail)}
function game12Clock(){try{return typeof clockLabel==='function'?clockLabel():'Sessão ativa'}catch(e){return'Sessão ativa'}}
function game12Journal(){return window.gameState?.journal||[]}
function game12Char(){return window.gameState?.character||{}}
function game12Combat(){return window.gameState?.combat||{enemies:[]}}
function game12Npcs(){return window.gameState?.npcs||[]}
function game12Factions(){return window.gameState?.factions||[]}
function game12WorldTurns(){return Number(window.gameState?.campaign?.worldTurns)||0}
function game12Seen(){try{return world.filter(t=>t.seen).length}catch(e){return 0}}
function game12Pois(){try{return knownPOIs.size}catch(e){return 0}}
function game12Gemini(){try{if(typeof gemini11GenerateScene==='function')setTimeout(()=>gemini11GenerateScene(false),60)}catch(e){}}
function game12Fmt(ts){try{return new Date(ts).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(e){return''}}
function game12Inject(){
  const home=document.getElementById('inicio');
  if(home&&!document.getElementById('game12Home')){const a=document.getElementById('game10Console')||document.getElementById('game9Play')||document.getElementById('game8Home')||document.getElementById('gameCampaignState');a?.insertAdjacentHTML('afterend','<div id="game12Home" class="game12-runtime"></div>')}
  const ch=document.getElementById('personagem');
  if(ch&&!document.getElementById('game12Character')){const a=document.getElementById('game8Character')||document.getElementById('gameCharacterRuntime');a?.insertAdjacentHTML('afterend','<div id="game12Character" class="game12-runtime"></div>')}
  const co=document.getElementById('confronto');
  if(co&&!document.getElementById('game12Combat')){const a=document.getElementById('gameCombatRuntime');a?.insertAdjacentHTML('afterend','<div id="game12Combat" class="game12-runtime"></div>')}
  const ma=document.getElementById('mestre');
  if(ma&&!document.getElementById('game12Master')){const a=document.getElementById('game10Master')||document.getElementById('game9Master')||document.getElementById('game8Master')||document.getElementById('gameMasterRuntime');a?.insertAdjacentHTML('afterend','<div id="game12Master" class="game12-runtime"></div>')}
  const se=document.getElementById('sessoes');
  if(se&&!document.getElementById('game12Sessions')){const a=document.getElementById('game9Recap')||document.getElementById('game8Quests')||document.getElementById('gameSessionRuntime');a?.insertAdjacentHTML('afterend','<div id="game12Sessions" class="game12-runtime"></div>')}
}
function game12RenderHome(){const el=document.getElementById('game12Home');if(!el)return;const s=game12.activeSession,c=game12Char(),q=typeof game8ActiveQuest==='function'?game8ActiveQuest():null;el.innerHTML=`<div class="section-cap">Central do VTT</div><div class="game12-sessionbar orn-card"><div><span class="game12-label">Sessão ${game12Esc(s?.status||'inativa')}</span><h3>${game12Esc(s?.title||'Nenhuma sessão')}</h3><small>${s?`iniciada ${game12Fmt(s.startedAt)} • ${s.checkpoints||0} checkpoints`:'Crie uma sessão para começar.'}</small></div><span class="game12-status">${game12Esc(game12Clock())}</span></div><div class="game12-kpis"><div class="game12-kpi"><b>${c.hp??0}/${c.maxHp??0}</b><small>PV</small></div><div class="game12-kpi"><b>${game12Seen()}</b><small>hexes</small></div><div class="game12-kpi"><b>${game12Pois()}</b><small>POIs</small></div><div class="game12-kpi"><b>${game12WorldTurns()}</b><small>turnos mundo</small></div></div><div class="game12-grid" style="margin-top:8px"><div class="game12-card orn-card game12-wide"><span>Objetivo atual</span><b>${game12Esc(q?.title||window.gameState?.campaign?.objective||'Sem objetivo ativo')}</b><small>${game12Esc(q?.desc||'O Mestre mantém a continuidade da campanha e do mundo vivo.')}</small><div class="game12-actions"><button class="primary" onclick="game12Go('explorar')">Continuar aventura</button><button onclick="game12Go('personagem')">Ficha</button><button onclick="game12Go('sessoes')">Diário</button><button onclick="game12Checkpoint()">Checkpoint</button></div></div></div>`}
function game12RenderCharacter(){const el=document.getElementById('game12Character');if(!el)return;const c=game12Char(),inv=Array.isArray(c.inventory)?c.inventory:[];el.innerHTML=`<div class="section-cap">Ficha persistente</div><div class="game12-grid"><div class="game12-card orn-card game12-wide"><span>Anotações do personagem</span><textarea id="game12CharNotes" class="game12-note" placeholder="Ferimentos narrativos, pistas pessoais, juramentos, contatos...">${game12Esc(game12.characterNotes)}</textarea><div class="game12-actions"><button class="primary" onclick="game12SaveNotes()">Salvar notas</button></div></div><div class="game12-card orn-card game12-wide"><span>Equipamento em uso</span><div class="game12-equip">${inv.map((it,i)=>{const name=Array.isArray(it)?it[0]:String(it),load=Array.isArray(it)?it[1]:'',ready=game12.equipmentState[i]==='ready';return`<div class="game12-equiprow"><div><b>${game12Esc(name)}</b><small>${game12Esc(load)}</small></div><button class="game12-toggle ${ready?'ready':''}" onclick="game12ToggleEquip(${i})">${ready?'Preparado':'Guardado'}</button></div>`}).join('')||'<div class="game12-empty">Nenhum equipamento registrado.</div>'}</div></div></div>`}
function game12RenderCombat(){const el=document.getElementById('game12Combat');if(!el)return;const co=game12Combat(),c=game12Char(),en=Array.isArray(co.enemies)?co.enemies:[],alive=en.filter(x=>x.hp>0);el.innerHTML=`<div class="section-cap">Diretor de encontro</div><div class="game12-combat orn-card"><div class="game12-combat-head"><div><span class="game12-label">Rodada ${window.appState?.combatRound||1}</span><h3>${alive.length?`${alive.length} ameaças ativas`:'Encontro encerrado'}</h3><small>Herói ${c.hp??0}/${c.maxHp??0} PV</small></div><span class="game12-status">${alive.length?'combate':'resolvido'}</span></div><div class="game12-enemies">${en.map(x=>`<div class="game12-enemy ${x.hp<=0?'dead':''}"><div><b>${game12Esc(x.name)}</b><small>PV ${Math.max(0,x.hp)}/${x.maxHp} • CA ${x.ac}</small></div><span class="game12-pill">${x.hp>0?'ativo':'fora'}</span></div>`).join('')}</div><div class="game12-actions"><button class="primary" onclick="game12NextRound()" ${!alive.length?'disabled':''}>Resolver próxima rodada</button><button onclick="game12NarrateCombat()">Narrar situação</button><button class="danger" onclick="game12EndCombat()">Encerrar encontro</button></div></div>`}
function game12Relation(n){return Number(game12.relations[n]||0)}
function game12RenderMaster(){const el=document.getElementById('game12Master');if(!el)return;const npcs=game12Npcs(),factions=game12Factions();el.innerHTML=`<div class="section-cap">Memória do Mestre</div><div class="game12-master-state"><div class="game12-card orn-card"><span>Contatos & relações</span><div style="margin-top:8px;display:grid;gap:6px">${npcs.map(n=>`<div class="game12-contact"><div><b>${game12Esc(n.name)}</b><small>${game12Esc(n.role)} • ${game12Esc(n.location)} • ${game12Esc(n.intent||n.status||'')}</small></div><div class="game12-rel"><button onclick="game12Rel('${game12Esc(n.name)}',-1)">−</button><strong>${game12Relation(n.name)}</strong><button onclick="game12Rel('${game12Esc(n.name)}',1)">+</button></div></div>`).join('')||'<div class="game12-empty">Nenhum NPC registrado.</div>'}</div></div><div class="game12-card orn-card"><span>Facções & projetos</span>${factions.map((f,i)=>`<div class="game12-faction"><div class="game12-faction-head"><div><b>${game12Esc(f.name)}</b><small>${game12Esc(f.goal)} • postura ${game12Esc(f.stance)}</small></div><div class="game12-rel"><button onclick="game12Faction(${i},-1)">−</button><strong>${f.clock}/${f.max}</strong><button onclick="game12Faction(${i},1)">+</button></div></div><div class="game12-clock">${Array.from({length:f.max},(_,k)=>`<i class="${k<f.clock?'on':''}"></i>`).join('')}</div></div>`).join('')||'<div class="game12-empty">Nenhuma facção registrada.</div>'}<div class="game12-actions"><button class="primary" onclick="game12WorldPulse()">Avançar mundo vivo</button></div></div></div>`}
function game12RenderSessions(){const el=document.getElementById('game12Sessions');if(!el)return;const s=game12.activeSession,rows=game12Journal().slice(0,12);el.innerHTML=`<div class="section-cap">Controle da sessão</div><div class="game12-card orn-card"><span>Sessão atual</span><b>${game12Esc(s?.title||'Nenhuma')}</b><small>${s?`${game12Esc(s.status)} • ${game12Fmt(s.startedAt)} • ${s.checkpoints||0} checkpoints`:'Sem sessão ativa.'}</small><div class="game12-actions"><button class="primary" onclick="game12Checkpoint()">Criar checkpoint</button><button onclick="game12NewSession()">Nova sessão</button><button class="danger" onclick="game12EndSession()">Encerrar sessão</button></div></div><div class="section-cap">Linha do tempo</div><div class="game12-card orn-card"><div class="game12-timeline">${rows.map(r=>`<div class="game12-entry"><b>${game12Esc(r.title||r.kind||'Registro')}</b><small>${game12Esc(r.detail||'')} ${r.time?'• '+game12Esc(r.time):''}</small></div>`).join('')||'<div class="game12-empty">A sessão ainda não possui registros.</div>'}</div></div>${game12.sessions.length?`<div class="section-cap">Sessões encerradas</div><div class="game12-card orn-card">${game12.sessions.slice(0,8).map(x=>`<div class="game12-entry"><b>${game12Esc(x.title)}</b><small>${game12Fmt(x.startedAt)} → ${game12Fmt(x.endedAt)} • ${x.entries||0} registros</small></div>`).join('')}</div>`:''}`}
function game12RenderAll(){game12Inject();game12RenderHome();game12RenderCharacter();game12RenderCombat();game12RenderMaster();game12RenderSessions();game12Save()}
function game12Go(v){if(typeof appGo==='function')appGo(v)}
function game12SaveNotes(){const t=document.getElementById('game12CharNotes');if(!t)return;game12.characterNotes=t.value;game12Save();game12Log('character','Anotações atualizadas',game12.characterNotes.slice(0,120));game12Toast('Anotações salvas.')}
function game12ToggleEquip(i){game12.equipmentState[i]=game12.equipmentState[i]==='ready'?'stowed':'ready';game12Save();game12Log('character','Equipamento alterado',`${game12Char().inventory?.[i]?.[0]||'Item'}: ${game12.equipmentState[i]==='ready'?'preparado':'guardado'}`);game12RenderCharacter()}
function game12Rel(name,d){game12.relations[name]=Math.max(-3,Math.min(3,game12Relation(name)+d));game12Save();game12Log('npc',`Relação com ${name}`,`nível ${game12.relations[name]}`);game12RenderMaster()}
function game12Faction(i,d){const f=game12Factions()[i];if(!f)return;f.clock=Math.max(0,Math.min(f.max,Number(f.clock||0)+d));if(typeof gameSave==='function')gameSave();game12Log('faction',`Projeto de ${f.name}`,`${f.clock}/${f.max} • ${f.goal}`);game12RenderMaster();game12RenderHome()}
function game12WorldPulse(){try{if(typeof gameWorldTurn==='function')gameWorldTurn('pulso manual do VTT')}catch(e){}game12Log('world','Mundo vivo avançou','NPCs, facções e projetos receberam um novo pulso.');game12Gemini();game12RenderAll()}
function game12Checkpoint(){const s=game12.activeSession;if(!s)return;const snap={stamp:Date.now(),journal:game12Journal().slice(0,20),game:window.gameState||null,world:{clock:window.clock||null,current:window.current||0}};localStorage.setItem('wwn_game12_checkpoint',JSON.stringify(snap));s.checkpoints=(s.checkpoints||0)+1;game12.lastCheckpoint=snap.stamp;game12Save();try{if(typeof game8Autosave==='function')game8Autosave('checkpoint manual')}catch(e){}game12Log('session','Checkpoint criado',`Checkpoint ${s.checkpoints} • ${game12Clock()}`);game12Toast('Checkpoint salvo.');game12RenderAll()}
function game12NewSession(){if(game12.activeSession?.status==='ativa'){game12.sessions.unshift({...game12.activeSession,status:'encerrada',endedAt:Date.now(),entries:game12Journal().length})}const n=game12.sessions.length+9;game12.activeSession={id:`s${n}`,title:`Sombras de Gelo e Ferro — Sessão ${n}`,status:'ativa',startedAt:Date.now(),checkpoints:0};game12Save();game12Log('session',`Sessão ${n} iniciada`,'Nova sessão de campanha.');game12Gemini();game12RenderAll()}
function game12EndSession(){const s=game12.activeSession;if(!s)return;s.status='encerrada';s.endedAt=Date.now();s.entries=game12Journal().length;game12.sessions.unshift({...s});game12.activeSession={id:`s${game12.sessions.length+9}`,title:'Próxima sessão',status:'inativa',startedAt:Date.now(),checkpoints:0};game12Save();game12Log('session','Sessão encerrada',`${s.title} • ${s.entries} registros`);game12Toast('Sessão encerrada e arquivada.');game12RenderAll()}
function game12NextRound(){try{if(typeof gameNextRound==='function'){gameNextRound();game12Log('combat','Rodada resolvida',`Rodada ${window.appState?.combatRound||1}`);game12Gemini();game12RenderAll();return}}catch(e){}game12Toast('Motor de rodada indisponível.')}
function game12NarrateCombat(){if(typeof gemini11Ready==='function'&&gemini11Ready()){try{gemini11GenerateScene(true)}catch(e){}}else if(typeof game9Tts==='function'){const co=game12Combat(),alive=(co.enemies||[]).filter(x=>x.hp>0);game9Tts(`Combate em andamento. ${alive.length} ameaças continuam ativas. O personagem possui ${game12Char().hp} pontos de vida.`)}}
function game12EndCombat(){const co=game12Combat();if(Array.isArray(co.enemies))co.enemies.forEach(e=>{if(e.hp<0)e.hp=0});if(typeof gameSave==='function')gameSave();game12Log('combat','Encontro encerrado','O Mestre encerrou o encontro e devolveu o controle à cena.');if(typeof appGo==='function')appGo('inicio');game12Gemini();game12RenderAll()}
function game12Hook(){if(window.__game12Hooked)return;window.__game12Hooked=true;try{if(typeof showView==='function'){const old=showView;showView=function(v){old(v);requestAnimationFrame(game12RenderAll)}}}catch(e){}try{if(typeof gameRefreshAll==='function'){const old=gameRefreshAll;gameRefreshAll=function(){old();game12RenderAll()}}}catch(e){}try{if(typeof game9RenderAll==='function'){const old=game9RenderAll;game9RenderAll=function(){old();game12RenderAll()}}}catch(e){}}
function game12Init(){game12Hook();game12RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game12Init);else game12Init();
