'use strict';
/* GAME_RUNTIME_V32 — adjudicador: intenção -> necessidade de regra -> evidência -> resolução -> consequência. Sem UI. */
const GAME32_STORAGE='wwn_game_runtime_v32';
const game32Default={seq:0,queue:[],history:[],policies:{blockUnsupportedMechanics:true,autoNarrate:true,requireEvidenceForConfiguredRules:false},metrics:{requests:0,resolved:0,blocked:0,delegated:0},last:null};
let game32=Object.assign({},game32Default,JSON.parse(localStorage.getItem(GAME32_STORAGE)||'null')||{});
function game32Save(){try{localStorage.setItem(GAME32_STORAGE,JSON.stringify(game32))}catch(e){}}
function game32Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game32Emit(t,p){try{window.WWN_ENGINE?.emit?.(t,p)}catch(e){}}
function game32Intent(text){try{if(typeof game10Intent==='function')return game10Intent(text)}catch(e){}const s=String(text||'').toLowerCase();if(/atac|golpe|lutar/.test(s))return'combate';if(/viaj|seguir|mover|ir para/.test(s))return'viagem';if(/investig|examinar|pista/.test(s))return'investigar';if(/explor|vasculh|mapear/.test(s))return'explorar';if(/falar|pergunt|convers/.test(s))return'conversar';if(/descans|acampar|dormir/.test(s))return'descanso';if(/observar|vigiar|escutar/.test(s))return'observar';if(/ração|racao|comida|água|agua|forrage/.test(s))return'recursos';return'livre'}
function game32RuleQuery(intent,text){const map={combate:'combat attack damage shock armor class initiative WWN',investigar:'skill check investigation notice know WWN',explorar:'skill check exploration survive notice travel WWN',conversar:'reaction roll talk connect persuade WWN',descanso:'rest healing system strain recovery WWN',observar:'skill check notice perception WWN',recursos:'foraging survival supplies travel WWN',viagem:'overland travel hex movement time supplies WWN'};return`${map[intent]||'general action resolution WWN'} ${String(text||'').slice(0,180)}`}
function game32Evidence(query,limit=6){try{if(typeof game26Search==='function')return game26Search(query,limit).map((x,i)=>({id:`E${i+1}`,source:x.row.sourceName,page:x.row.page||0,text:x.row.text.slice(0,1000),score:x.score}))}catch(e){}return[]}
function game32NeedsMechanic(intent){return['combate','investigar','explorar','observar','recursos'].includes(intent)}
function game32Delegates(intent){return{combate:['game15ConfiguredAttack','gameCombatAttack'],investigar:['game15RequestCheck'],explorar:['game15RequestCheck','explore'],observar:['game15RequestCheck','game8Scout'],recursos:['game15RequestCheck','game8Forage'],descanso:['game15Rest','camp'],conversar:['game25Talk','game9Talk'],viagem:['wwnTravelSelected']}[intent]||[]}
function game32New(text,source='player'){const intent=game32Intent(text),query=game32RuleQuery(intent,text),evidence=game32Evidence(query),r={id:`ar${Date.now()}_${++game32.seq}`,text:String(text||''),intent,source,query,evidence,requiresMechanic:game32NeedsMechanic(intent),status:'queued',created:Date.now(),resolution:null,delegate:null,reason:''};game32.queue.push(r);game32.queue=game32.queue.slice(-80);game32.metrics.requests++;game32.last=r;game32Save();game32Emit('adjudication.requested',game32Clone(r));return r}
function game32FindDelegate(r){for(const name of game32Delegates(r.intent))if(typeof window[name]==='function')return name;return null}
function game32Unsupported(r){if(!r.requiresMechanic)return false;if(r.evidence.length)return false;const configured=r.intent==='combate'&&!!window.gameState?.character?.combatProfile?.enabled;if(configured&&!game32.policies.requireEvidenceForConfiguredRules)return false;return !!game32.policies.blockUnsupportedMechanics}
function game32Resolve(rOrId,{execute=false,args=[]}={}){const r=typeof rOrId==='string'?game32.queue.find(x=>x.id===rOrId):rOrId;if(!r||r.status!=='queued')return r;if(game32Unsupported(r)){r.status='blocked';r.reason='Sem evidência suficiente nos manuais para automatizar esta resolução mecânica.';r.resolvedAt=Date.now();game32.metrics.blocked++;game32History(r);game32Emit('adjudication.blocked',game32Clone(r));return r}const delegate=game32FindDelegate(r);r.delegate=delegate;if(!delegate){r.status=r.requiresMechanic?'pending-manual':'resolved';r.reason=r.requiresMechanic?'Ação mecânica sem resolvedor automático; aguarda decisão/configuração do Mestre.':'Ação narrativa/administrativa registrada sem mutação mecânica automática.';r.resolvedAt=Date.now();if(r.status==='resolved')game32.metrics.resolved++;game32History(r);game32Emit(`adjudication.${r.status==='resolved'?'resolved':'pending'}`,game32Clone(r));return r}r.status='delegated';game32.metrics.delegated++;game32Save();if(!execute){game32Emit('adjudication.delegated',game32Clone(r));return r}const tx=window.WWN_ENGINE?.begin?.(`adjudication.${r.intent}`,{action:r.text,intent:r.intent,delegate},source)||null;try{let result;if(delegate==='game15RequestCheck'){result=window[delegate](r.intent,r.text)}else result=window[delegate](...args);r.resolution=result??{delegated:true};r.status='resolved';r.resolvedAt=Date.now();game32.metrics.resolved++;if(tx){window.WWN_ENGINE?.attachRuleEvidence?.(tx.id,r.query);window.WWN_ENGINE?.commit?.(tx,{label:`Adjudicação ${r.intent}`,delegate,result:r.resolution})}game32History(r);game32Emit('adjudication.resolved',game32Clone(r));return r}catch(e){r.status='error';r.reason=e?.message||String(e);r.resolvedAt=Date.now();if(tx)window.WWN_ENGINE?.abort?.(tx,r.reason);game32History(r);game32Emit('adjudication.error',game32Clone(r));return r}}
function game32History(r){game32.history.unshift(game32Clone(r));game32.history=game32.history.slice(0,120);game32.queue=game32.queue.filter(x=>x.id!==r.id);game32.last=r;game32Save()}
function game32Adjudicate(text,opts={}){const r=game32New(text,opts.source||'player');return game32Resolve(r,opts)}
function game32Pending(){return game32.queue.filter(x=>['queued','delegated','pending-manual'].includes(x.status))}
function game32NarrativeContext(){const r=game32.last;if(!r)return null;return{adjudication:{intent:r.intent,status:r.status,action:r.text,resolution:r.resolution||null,reason:r.reason||'',evidence:r.evidence.map(x=>({source:x.source,page:x.page,text:x.text.slice(0,700)}))},instruction:'Se status for blocked ou pending-manual, não narre uma resolução mecânica. Narre apenas a situação e a necessidade de decisão/resolução.'}}
function game32Hook(){if(window.__game32Hook)return;window.__game32Hook=true;try{window.WWN_ENGINE?.on?.('transaction.opened',evt=>{if(evt.payload?.kind!=='player.action')return;const tx=window.WWN_ENGINE?.getState?.().tx?.find(x=>x.id===evt.payload.id);const text=tx?.payload?.text;if(text)game32Adjudicate(text,{source:'player',execute:false})})}catch(e){}try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(...a){const c=old.apply(this,a),ctx=game32NarrativeContext();return ctx?Object.assign({},c,ctx):c}}}catch(e){}}
function game32Api(){window.WWN_ADJUDICATOR={version:32,adjudicate:game32Adjudicate,resolve:game32Resolve,pending:game32Pending,evidence:game32Evidence,intent:game32Intent,getState:()=>game32}}
function game32Init(){game32Hook();game32Api();game32Emit('adjudicator.ready',{version:32})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game32Init);else game32Init();
