'use strict';
/* GAME_RUNTIME_V18 — calendário persistente, eventos agendados e downtime. */
const GAME18_STORAGE='wwn_game_runtime_v18';
const game18Default={events:[],downtime:[],lastStamp:0,serial:0,completed:0};
function game18Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game18Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game18=game18Merge(game18Default,JSON.parse(localStorage.getItem(GAME18_STORAGE)||'null'));
function game18Save(){localStorage.setItem(GAME18_STORAGE,JSON.stringify(game18))}
function game18Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game18Now(){try{return(Math.max(1,Number(clock.day||1))-1)*1440+Number(clock.hour||0)*60+Number(clock.min||0)}catch(e){return 0}}
function game18ClockLabel(mins){const d=Math.floor(mins/1440)+1,r=mins%1440,h=Math.floor(r/60),m=r%60;return`Dia ${d} • ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function game18Toast(s){try{if(typeof toast==='function')toast(s)}catch(e){}}
function game18Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game18Schedule({title,detail='',inHours=0,inDays=0,visibility='master',kind='evento',recurringDays=0,scene=false}={}){const now=game18Now(),delay=Math.max(0,Math.round(Number(inHours||0)*60+Number(inDays||0)*1440));const ev={id:`e18_${Date.now()}_${++game18.serial}`,title:title||'Evento futuro',detail,visibility,kind,due:now+delay,status:'scheduled',created:now,recurringDays:Math.max(0,Number(recurringDays||0)),scene:!!scene,triggeredAt:null};game18.events.push(ev);game18.events.sort((a,b)=>a.due-b.due);game18Save();game18RenderAll();return ev}
function game18QueueScene(ev){try{if(!ev.scene||typeof game14==='undefined'||!Array.isArray(game14.sceneQueue))return;game14.sceneQueue.push({id:`scene_${Date.now()}`,title:ev.title,type:ev.kind||'evento',detail:ev.detail||'Evento agendado da campanha.',status:'queued',stamp:Date.now()});if(typeof game14Save==='function')game14Save()}catch(e){}}
function game18Publish(ev){const detail=ev.detail||'O evento chegou ao momento de acontecer.';if(ev.visibility==='player'){try{if(typeof game16News==='function')game16News(ev.title,detail,ev.kind==='perigo'?'hot':'info','player')}catch(e){}}else{try{if(typeof game16News==='function')game16News(ev.title,detail,ev.kind==='perigo'?'hot':'info','master')}catch(e){}}game18Log('calendar',ev.title,`${detail} • ${game18ClockLabel(ev.due)} • ${ev.visibility==='player'?'público':'Mestre'}`);game18QueueScene(ev);try{if(typeof gemini11GenerateScene==='function'&&ev.visibility==='player')setTimeout(()=>gemini11GenerateScene(false),100)}catch(e){}
}
function game18Process(){const now=game18Now();if(!game18.lastStamp)game18.lastStamp=now;const delta=Math.max(0,now-game18.lastStamp);if(delta>0)game18AdvanceDowntime(delta);for(const ev of game18.events){if(ev.status!=='scheduled'||ev.due>now)continue;ev.status='done';ev.triggeredAt=now;game18.completed++;game18Publish(ev);if(ev.recurringDays>0){game18.events.push({...ev,id:`e18_${Date.now()}_${++game18.serial}`,due:ev.due+ev.recurringDays*1440,status:'scheduled',triggeredAt:null})}}game18.events.sort((a,b)=>a.due-b.due);game18.lastStamp=now;game18Save();game18RenderAll()}
function game18AddDowntime(name,owner,hours,notes=''){const task={id:`d18_${Date.now()}_${++game18.serial}`,name:name||'Atividade',owner:owner||'Grupo',hours:Math.max(1,Number(hours||1)),progress:0,status:'active',notes,created:game18Now(),completedAt:null};game18.downtime.unshift(task);game18Save();game18RenderAll();return task}
function game18AdvanceDowntime(minutes){if(minutes<=0)return;for(const d of game18.downtime){if(d.status!=='active')continue;d.progress=Math.min(d.hours*60,d.progress+minutes);if(d.progress>=d.hours*60){d.status='done';d.completedAt=game18Now();game18Log('downtime',`${d.name} concluída`,`${d.owner}${d.notes?' • '+d.notes:''}`);try{if(typeof game16News==='function')game16News(`${d.name} concluída`,`${d.owner} terminou a atividade.`,'good','player')}catch(e){}}}}
function game18CancelEvent(id){const e=game18.events.find(x=>x.id===id);if(e&&e.status==='scheduled')e.status='cancelled';game18Save();game18RenderAll()}
function game18RemoveDowntime(id){game18.downtime=game18.downtime.filter(x=>x.id!==id);game18Save();game18RenderAll()}
function game18CreateFromForm(){const g=id=>document.getElementById(id);const title=g('g18Title')?.value.trim(),detail=g('g18Detail')?.value.trim()||'',hours=Number(g('g18Hours')?.value||0),days=Number(g('g18Days')?.value||0),visibility=g('g18Visibility')?.value||'master',kind=g('g18Kind')?.value||'evento',rec=Number(g('g18Repeat')?.value||0),scene=!!g('g18Scene')?.checked;if(!title){game18Toast('Dê um título ao evento.');return}game18Schedule({title,detail,inHours:hours,inDays:days,visibility,kind,recurringDays:rec,scene});game18Toast('Evento agendado.');if(g('g18Title'))g('g18Title').value='';if(g('g18Detail'))g('g18Detail').value=''}
function game18CreateDowntime(){const g=id=>document.getElementById(id),name=g('g18DownName')?.value.trim(),owner=g('g18DownOwner')?.value.trim()||'Grupo',hours=Number(g('g18DownHours')?.value||1),notes=g('g18DownNotes')?.value.trim()||'';if(!name){game18Toast('Dê um nome à atividade.');return}game18AddDowntime(name,owner,hours,notes);game18Toast('Atividade adicionada.');if(g('g18DownName'))g('g18DownName').value=''}
function game18ManualAdvance(hours){const h=Math.max(1,Number(hours||1));try{if(typeof advance==='function'){advance(h);if(typeof updateWeather==='function')updateWeather(false);if(typeof render==='function')render();game18Process();return}}catch(e){}game18Toast('Relógio do mundo indisponível.')}
function game18Upcoming(publicOnly=false){const now=game18Now();return game18.events.filter(e=>e.status==='scheduled'&&(!publicOnly||e.visibility==='player')).sort((a,b)=>a.due-b.due).map(e=>({...e,remaining:Math.max(0,e.due-now)}))}
function game18FmtRemaining(mins){if(mins<60)return`${mins} min`;if(mins<1440)return`${Math.ceil(mins/60)}h`;return`${Math.ceil(mins/1440)} dias`}
function game18Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game18Home')){const a=document.getElementById('game16Home')||document.getElementById('game14Home');a?.insertAdjacentHTML('afterend','<div id="game18Home" class="game18-runtime"></div>')}const master=document.getElementById('mestre');if(master&&!document.getElementById('game18Master')){const a=document.getElementById('game16Master')||document.getElementById('game14Master');a?.insertAdjacentHTML('afterend','<div id="game18Master" class="game18-runtime"></div>')}const ses=document.getElementById('sessoes');if(ses&&!document.getElementById('game18Sessions')){const a=document.getElementById('game16Sessions')||document.getElementById('game14Sessions');a?.insertAdjacentHTML('afterend','<div id="game18Sessions" class="game18-runtime"></div>')}}
function game18RenderHome(){const el=document.getElementById('game18Home');if(!el)return;const up=game18Upcoming(true).slice(0,3),active=game18.downtime.filter(x=>x.status==='active');el.innerHTML=`<div class="section-cap">Calendário da campanha</div><div class="game18-card orn-card"><span>${game18Esc(typeof clockLabel==='function'?clockLabel():'Tempo da campanha')}</span><h3>${up[0]?game18Esc(up[0].title):'Nenhum evento público iminente'}</h3><small>${up[0]?`${game18FmtRemaining(up[0].remaining)} • ${game18Esc(up[0].detail)}`:'O Mestre continua acompanhando eventos ocultos e consequências futuras.'}</small><div class="game18-kpis"><div class="game18-kpi"><b>${game18Upcoming(false).length}</b><small>futuros</small></div><div class="game18-kpi"><b>${active.length}</b><small>downtime</small></div><div class="game18-kpi"><b>${game18.completed}</b><small>resolvidos</small></div></div>${up.length?`<div class="game18-list">${up.map(e=>`<div class="game18-row"><div class="game18-row-head"><div><b>${game18Esc(e.title)}</b><small>${game18ClockLabel(e.due)}</small></div><span class="game18-chip public">${game18FmtRemaining(e.remaining)}</span></div></div>`).join('')}</div>`:''}</div>`}
function game18RenderMaster(){const el=document.getElementById('game18Master');if(!el)return;const upcoming=game18Upcoming(false).slice(0,12);el.innerHTML=`<div class="section-cap">Agenda do Mestre</div><div class="game18-card orn-card"><span>Agendar consequência futura</span><div class="game18-form"><label class="game18-field wide"><span>Título</span><input id="g18Title" placeholder="A facção conclui o ritual"></label><label class="game18-field wide"><span>Detalhe</span><textarea id="g18Detail" placeholder="O que acontece quando chegar a hora..."></textarea></label><label class="game18-field"><span>Em horas</span><input id="g18Hours" type="number" min="0" value="0"></label><label class="game18-field"><span>Em dias</span><input id="g18Days" type="number" min="0" value="1"></label><label class="game18-field"><span>Visibilidade</span><select id="g18Visibility"><option value="master">Somente Mestre</option><option value="player">Jogador conhece</option></select></label><label class="game18-field"><span>Tipo</span><select id="g18Kind"><option>evento</option><option>perigo</option><option>social</option><option>descoberta</option><option>facção</option></select></label><label class="game18-field"><span>Repetir a cada N dias</span><input id="g18Repeat" type="number" min="0" value="0"></label><label class="game18-field"><span>Criar cena ao disparar</span><select onchange="document.getElementById('g18Scene').checked=this.value==='sim'"><option>não</option><option>sim</option></select><input id="g18Scene" type="checkbox" hidden></label></div><div class="game18-actions"><button class="primary" onclick="game18CreateFromForm()">Agendar evento</button><button onclick="game18ManualAdvance(1)">+1 hora</button><button onclick="game18ManualAdvance(24)">+1 dia</button></div><div class="game18-timeline">${upcoming.map(e=>`<div class="game18-event ${e.remaining===0?'due':''}"><div class="game18-row-head"><div><b>${game18Esc(e.title)}</b><small>${game18ClockLabel(e.due)} • ${game18Esc(e.detail)}</small></div><span class="game18-chip ${e.visibility}">${game18FmtRemaining(e.remaining)}</span></div><div class="game18-actions"><button onclick="game18CancelEvent('${e.id}')">Cancelar</button></div></div>`).join('')||'<div class="game18-note">Nenhum evento futuro agendado.</div>'}</div></div>`}
function game18RenderSessions(){const el=document.getElementById('game18Sessions');if(!el)return;const tasks=game18.downtime.slice(0,12);el.innerHTML=`<div class="section-cap">Downtime & projetos pessoais</div><div class="game18-card orn-card"><div class="game18-form"><label class="game18-field"><span>Atividade</span><input id="g18DownName" placeholder="Pesquisar o mapa antigo"></label><label class="game18-field"><span>Responsável</span><input id="g18DownOwner" placeholder="Personagem ou NPC"></label><label class="game18-field"><span>Duração em horas</span><input id="g18DownHours" type="number" min="1" value="8"></label><label class="game18-field wide"><span>Nota</span><input id="g18DownNotes" placeholder="Resultado será decidido pela ficção/regra apropriada"></label></div><div class="game18-actions"><button class="primary" onclick="game18CreateDowntime()">Adicionar atividade</button></div><div class="game18-list">${tasks.map(d=>{const pct=Math.round((d.progress/Math.max(1,d.hours*60))*100);return`<div class="game18-row"><div class="game18-row-head"><div><b>${game18Esc(d.name)}</b><small>${game18Esc(d.owner)} • ${d.hours}h ${d.notes?'• '+game18Esc(d.notes):''}</small></div><span class="game18-chip ${d.status==='done'?'done':''}">${d.status==='done'?'concluída':Math.floor(d.progress/60)+'h'}</span></div><div class="game18-progress"><i style="width:${pct}%"></i></div><div class="game18-actions"><button onclick="game18RemoveDowntime('${d.id}')">Remover</button></div></div>`}).join('')||'<div class="game18-note">Nenhuma atividade de downtime em andamento.</div>'}</div><div class="game18-note">O relógio avança por viagens, exploração, descanso ou avanço manual. A conclusão da atividade não inventa um resultado mecânico; apenas informa que o tempo necessário terminou.</div></div>`}
function game18RenderAll(){game18Inject();game18RenderHome();game18RenderMaster();game18RenderSessions();game18Save()}
function game18HookAdvance(){if(window.__game18AdvanceHooked||typeof advance!=='function')return;window.__game18AdvanceHooked=true;const old=advance;window.advance=function(h){const out=old(h);game18Process();return out}}
function game18HookWorld(){if(window.__game18WorldHooked||typeof gameWorldTurn!=='function')return;window.__game18WorldHooked=true;const old=gameWorldTurn;window.gameWorldTurn=function(reason){const out=old(reason);game18Process();return out}}
function game18HookViews(){if(window.__game18ViewHooked||typeof showView!=='function')return;window.__game18ViewHooked=true;const old=showView;window.showView=function(v){old(v);requestAnimationFrame(game18RenderAll)}}
function game18HookGemini(){if(window.__game18GeminiHooked||typeof g11Ctx!=='function')return;window.__game18GeminiHooked=true;const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action);c.calendar={now:typeof clockLabel==='function'?clockLabel():'',publicUpcoming:game18Upcoming(true).slice(0,3).map(e=>({title:e.title,detail:e.detail,due:game18ClockLabel(e.due)})),activeDowntime:game18.downtime.filter(d=>d.status==='active').slice(0,4).map(d=>({name:d.name,owner:d.owner,progressHours:Math.floor(d.progress/60),hours:d.hours}))};return c}}
function game18Init(){game18HookAdvance();game18HookWorld();game18HookViews();game18HookGemini();const now=game18Now();if(!game18.lastStamp)game18.lastStamp=now;game18Process();game18RenderAll();setInterval(()=>{game18HookAdvance();game18HookWorld();game18HookGemini()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game18Init);else game18Init();
