'use strict';
/* GAME_RUNTIME_V9 — o sistema atua como Mestre: cena, escolhas, memória social, rota e recapitulação. */
const GAME9_STORAGE='wwn_game_runtime_v9';
const game9Default={turn:0,scene:1,mode:'exploracao',narration:'',lastResolution:'',rumors:[],npcMemory:{},route:null,lastWorldPulse:0};
function game9Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game9Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game9=game9Merge(game9Default,JSON.parse(localStorage.getItem(GAME9_STORAGE)||'null'));
function game9Save(){localStorage.setItem(GAME9_STORAGE,JSON.stringify(game9))}
function game9Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game9Tile(){try{return currentTile()}catch(e){return null}}
function game9PoiKnown(t){try{return !!(t?.poi&&knownPOIs.has(key(t.q,t.r)))}catch(e){return false}}
function game9Poi(t){return game9PoiKnown(t)&&window.POIS?.[t.poi]?POIS[t.poi]:null}
function game9Terrain(t){return t&&window.BASES?.[t.base]?BASES[t.base].name:'território desconhecido'}
function game9Feature(t){return t?.feature&&window.FEATURES?.[t.feature]?FEATURES[t.feature].name:''}
function game9Region(t){try{return labelRegion(t.region)}catch(e){return t?.region||'região'} }
function game9Clock(){try{return clockLabel()}catch(e){return'Sessão ativa'}}
function game9Quest(){try{return typeof game8ActiveQuest==='function'?game8ActiveQuest():null}catch(e){return null}}
function game9LastEvent(){try{return window.lastEvent||null}catch(e){return null}}
function game9LastEncounter(){try{return window.game8?.lastEncounter||null}catch(e){return null}}
function game9Journal(){try{return window.gameState?.journal||[]}catch(e){return[]}}
function game9NpcList(){try{return window.gameState?.npcs||[]}catch(e){return[]}}
function game9FactionList(){try{return window.gameState?.factions||[]}catch(e){return[]}}
function game9Tts(text){try{if(window.appState&&appState.tts===false)return;if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='pt-BR';u.rate=.96;u.pitch=.92;speechSynthesis.speak(u)}catch(e){}}
function game9Log(kind,title,detail=''){if(typeof gameLog==='function')gameLog(kind,title,detail);else if(typeof note==='function')note(title+(detail?' — '+detail:''))}
function game9Toast(s){if(typeof toast==='function')toast(s)}
function game9SceneMode(){const t=game9Tile(),p=game9Poi(t),enc=game9LastEncounter();if(enc?.hostile)return'perigo';if(p?.type==='habitado')return'social';if(p?.type==='perigoso')return'perigo';if((window.game8?.expedition?.fatigue||0)>=4)return'descanso';return'exploracao'}
function game9Compose(){const t=game9Tile();if(!t)return'O mundo está sendo preparado.';const p=game9Poi(t),f=game9Feature(t),q=game9Quest(),ev=game9LastEvent();let lead='';const mode=game9SceneMode();if(mode==='social')lead=`O caminho leva você até ${p.name}. Há movimento, vozes e oportunidades de obter informação antes de seguir viagem.`;else if(mode==='perigo')lead=p?`${p.name} domina a cena. O lugar parece exigir cautela; qualquer decisão aqui pode mudar o rumo da expedição.`:`A região transmite perigo imediato. Há sinais de presença hostil nas proximidades.`;else if(mode==='descanso')lead=`A jornada começa a pesar. ${game9Terrain(t)} oferece um momento para decidir entre avançar ou recuperar o fôlego.`;else lead=`Você está em ${game9Terrain(t)}${f?' entre '+f.toLowerCase():''}. A região está aberta, mas nem tudo ao redor foi compreendido.`;if(ev?.title)lead+=` O acontecimento mais recente foi “${ev.title}”.`;if(q?.title&&!q.done)lead+=` Seu objetivo atual continua sendo: ${q.title}.`;return lead}
function game9ContextChips(){const t=game9Tile(),p=game9Poi(t),e=window.game8?.expedition||{};return [`Cena ${game9.scene}`,game9Clock(),game9Region(t),p?.name||game9Terrain(t),`fadiga ${e.fatigue??0}/${e.maxFatigue??6}`]}
function game9NpcForScene(){const n=game9NpcList();if(!n.length)return null;const p=game9Poi(game9Tile());if(p){const exact=n.find(x=>String(x.location||'').toLowerCase().includes(p.name.split(' ')[0].toLowerCase()));if(exact)return exact}return n[(game9.turn+game9.scene)%n.length]}
function game9ChoiceSet(){const t=game9Tile(),p=game9Poi(t),enc=game9LastEncounter(),choices=[];if(enc?.hostile)choices.push({id:'fight',title:'Enfrentar a ameaça',desc:'Abrir o confronto e deixar o Mestre conduzir a oposição.',cls:'warn'});choices.push({id:'explore',title:'Explorar',desc:'Investigar o hex atual e procurar novas pistas.',cls:'primary'});if(t?.poi&&!p)choices.push({id:'inspect',title:'Investigar sinais',desc:'Tentar identificar o local de interesse deste hex.'});if(p?.type==='habitado')choices.push({id:'talk',title:'Conversar',desc:'Falar com alguém do local e buscar informação.'});else choices.push({id:'observe',title:'Observar região',desc:'Ler o terreno antes de agir.'});choices.push({id:'travel',title:'Planejar jornada',desc:'Abrir o Atlas e escolher o próximo hex.'});if((window.game8?.expedition?.fatigue||0)>1)choices.push({id:'rest',title:'Acampar',desc:'Encerrar um período de jornada e descansar.'});return choices.slice(0,4)}
function game9Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game9Play')){const anchor=document.getElementById('game8Home')||document.getElementById('gameCampaignState')||home.querySelector('.hero-campaign');anchor?.insertAdjacentHTML('afterend','<div id="game9Play" class="game9-runtime"></div>')}const exp=document.getElementById('explorar');if(exp&&!document.getElementById('game9Route')){const anchor=document.getElementById('game8Explore')||document.getElementById('selectedHexPanel')||document.getElementById('locationPanel');anchor?.insertAdjacentHTML('afterend','<div id="game9Route" class="game9-runtime"></div>')}const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game9Master')){const a=document.getElementById('game8Master')||document.getElementById('gameMasterRuntime');a?.insertAdjacentHTML('afterend','<div id="game9Master" class="game9-runtime"></div>')}const se=document.getElementById('sessoes');if(se&&!document.getElementById('game9Recap')){const a=document.getElementById('game8Quests')||document.getElementById('gameSessionRuntime');a?.insertAdjacentHTML('afterend','<div id="game9Recap" class="game9-runtime"></div>')}}
function game9RenderPlay(){const el=document.getElementById('game9Play');if(!el)return;if(!game9.narration)game9.narration=game9Compose();const q=game9Quest(),choices=game9ChoiceSet();el.innerHTML=`<div class="section-cap">Jogar</div><div class="game9-director orn-card"><div class="game9-head"><div><span>Mestre automático • ${game9Esc(game9.sceneMode||game9SceneMode())}</span><h2>${game9Esc(game9Poi(game9Tile())?.name||game9Terrain(game9Tile()))}</h2></div><div class="game9-top-actions"><button class="game9-icon" onclick="game9Narrate()" title="Ouvir narração">◖</button><button class="game9-icon" onclick="game9NewScene()" title="Atualizar cena">↻</button></div></div><div class="game9-context">${game9ContextChips().map(x=>`<i>${game9Esc(x)}</i>`).join('')}</div><div class="game9-narration">${game9Esc(game9.narration)}</div>${q?`<div class="game9-label">Objetivo: ${game9Esc(q.title)}</div>`:''}<div class="game9-choices">${choices.map(c=>`<button class="game9-choice ${c.cls||''}" onclick="game9Act('${c.id}')"><b>${game9Esc(c.title)}</b><small>${game9Esc(c.desc)}</small></button>`).join('')}</div>${game9.lastResolution?`<div class="game9-resolution"><b>Resultado:</b> ${game9Esc(game9.lastResolution)}</div>`:''}</div>`}
function game9RenderRoute(){const el=document.getElementById('game9Route');if(!el)return;let selected=null;try{selected=typeof wwnSelectedTile==='function'?wwnSelectedTile():null}catch(e){}const here=game9Tile();if(!selected||!here){el.innerHTML='';return}let d=0;try{d=dist(here,selected)}catch(e){}const cost=window.BASES?.[selected.base]?.cost||0;const eta=d?Math.max(cost,Math.round(cost*d)):0;const unknown=!selected.seen;el.innerHTML=`<div class="section-cap">Planejamento de jornada</div><div class="game9-route orn-card"><div class="game9-route-head"><div><span class="game9-label">Destino selecionado</span><h3>${game9Esc(unknown?'Território desconhecido':game9Poi(selected)?.name||game9Terrain(selected))}</h3><small>Q ${selected.q} • R ${selected.r} • ${d} hex${d===1?'':'es'} de distância</small></div><div class="game9-status">${d===1?'adjacente':d===0?'atual':'distante'}</div></div><div class="game9-context"><i>estimativa ~${eta}h</i><i>${game9Esc(unknown?'composição desconhecida':game9Feature(selected)||'sem relevo marcante')}</i></div><div class="game9-route-actions"><button class="primary" onclick="game9RouteAction()">${d===1?'Viajar para este hex':'Usar como destino'}</button><button onclick="game9CenterCurrent()">Voltar ao grupo</button></div></div>`}
function game9RenderMaster(){const el=document.getElementById('game9Master');if(!el)return;const npc=game9NpcForScene(),factions=game9FactionList(),rumor=game9.rumors[0];el.innerHTML=`<div class="section-cap">Direção da aventura</div><div class="game9-card orn-card game9-wide"><span class="game9-label">Cena atual</span><b>${game9Esc(game9Compose())}</b><div class="game9-master-controls"><button onclick="game9NewScene()"><b>Nova cena</b><small>recontextualizar</small></button><button onclick="game9PulseWorld()"><b>Avançar mundo</b><small>NPCs e facções</small></button><button onclick="game9Talk(true)"><b>Gerar rumor</b><small>informação local</small></button></div></div><div class="game9-grid" style="margin-top:8px"><div class="game9-card orn-card"><span class="game9-label">NPC em foco</span><b>${game9Esc(npc?.name||'Nenhum')}</b><small>${game9Esc(npc?`${npc.role} • ${npc.location}`:'Sem NPC em foco')}</small></div><div class="game9-card orn-card"><span class="game9-label">Facções ativas</span><b>${factions.length}</b><small>${game9Esc(factions.map(f=>`${f.name} ${f.clock}/${f.max}`).join(' • '))}</small></div></div>${rumor?`<div class="game9-rumor"><b>Rumor recente</b><small>${game9Esc(rumor.text)} • ${game9Esc(rumor.source)}</small></div>`:''}`}
function game9RenderRecap(){const el=document.getElementById('game9Recap');if(!el)return;const rows=game9Journal().slice(0,8),q=game9Quest();el.innerHTML=`<div class="section-cap">Recapitulação automática</div><div class="game9-recap orn-card"><h3>${game9Esc(q?.title||'Campanha em andamento')}</h3><div class="game9-label">${game9Esc(game9Clock())} • cena ${game9.scene} • ${game9.turn} decisões do jogador</div>${rows.length?rows.map(r=>`<div class="game9-recap-item"><b>${game9Esc(r.title)}</b><small>${game9Esc(r.detail||r.time||'')}</small></div>`).join(''):'<div class="game9-recap-item"><small>A sessão ainda não possui registros suficientes.</small></div>'}<div class="game9-route-actions"><button class="primary" onclick="game9Resume()">Continuar jogando</button><button onclick="game9NarrateRecap()">Ouvir resumo</button></div></div>`}
function game9RenderAll(){game9Inject();game9RenderPlay();game9RenderRoute();game9RenderMaster();game9RenderRecap();game9Save()}
function game9Narrate(){game9Tts(game9.narration||game9Compose())}
function game9NarrateRecap(){const rows=game9Journal().slice(0,5);game9Tts(`Resumo da sessão. ${rows.map(r=>r.title+'. '+(r.detail||'')).join(' ')}`)}
function game9NewScene(reason='mudança de situação'){game9.scene++;game9.sceneMode=game9SceneMode();game9.narration=game9Compose();game9.lastResolution='';game9Save();game9Log('scene',`Cena ${game9.scene}`,reason);game9RenderAll()}
function game9AfterAction(label,detail){game9.turn++;game9.lastResolution=detail;game9.sceneMode=game9SceneMode();game9.narration=game9Compose();if(game9.turn-game9.lastWorldPulse>=3){game9.lastWorldPulse=game9.turn;try{if(typeof gameWorldTurn==='function')gameWorldTurn('avanço automático após decisões do jogador')}catch(e){}}game9Save();game9Log('player',label,detail);try{if(typeof game8UpdateQuests==='function')game8UpdateQuests('ação do jogador')}catch(e){}game9RenderAll()}
function game9Act(id){if(id==='fight'){try{if(typeof game8StartEncounter==='function'){game8StartEncounter();game9AfterAction('Confronto iniciado','A ameaça foi aceita e o combate começou.');return}}catch(e){}if(typeof appGo==='function')appGo('confronto');game9AfterAction('Confronto iniciado','A cena mudou para combate.');return}if(id==='explore'){try{if(typeof explore==='function')explore();game9AfterAction('Exploração','Você dedicou tempo a investigar o hex e seus arredores.');return}catch(e){}}if(id==='inspect'){try{if(typeof inspectPOI==='function')inspectPOI();game9AfterAction('Investigação local','Os sinais do local foram examinados.');return}catch(e){}}if(id==='observe'){try{if(typeof game8Scout==='function')game8Scout();game9AfterAction('Observação','Você leu o terreno antes de tomar a próxima decisão.');return}catch(e){}}if(id==='talk'){game9Talk(false);return}if(id==='travel'){if(typeof appGo==='function')appGo('explorar');game9.lastResolution='Escolha um hex no Atlas. O Mestre calculará o alcance e a estimativa de viagem.';game9Save();game9RenderAll();return}if(id==='rest'){try{if(typeof camp==='function')camp()}catch(e){}try{if(window.game8?.expedition){game8.expedition.fatigue=Math.max(0,game8.expedition.fatigue-2);if(typeof game8Save==='function')game8Save()}}catch(e){}game9AfterAction('Acampamento','O grupo encerrou um período da jornada e recuperou parte do fôlego.')}}
function game9Talk(masterOnly=false){const npc=game9NpcForScene();const pool=window.ORACLES?.rumor||['Uma rota antiga voltou a ser usada','Há movimento estranho além das colinas','Uma facção local procura ajuda'];const text=pool[Math.floor(Math.random()*pool.length)];const src=npc?.name||game9Poi(game9Tile())?.name||'viajantes locais';game9.rumors.unshift({text,source:src,stamp:Date.now()});game9.rumors=game9.rumors.slice(0,16);if(npc){const k=npc.name;const m=game9.npcMemory[k]||{talks:0,last:''};m.talks++;m.last=text;game9.npcMemory[k]=m}game9Save();if(masterOnly){game9Log('rumor','Rumor gerado',`${src}: ${text}`);game9RenderAll()}else game9AfterAction(`Conversa com ${src}`,`Você ouviu: “${text}”`)}
function game9RouteAction(){let selected=null,idx=-1;try{selected=wwnSelectedTile();idx=wwnSelectedIndex}catch(e){}const here=game9Tile();if(!selected||!here)return;let d=99;try{d=dist(here,selected)}catch(e){}if(d===1){try{if(typeof wwnTravelSelected==='function'){wwnTravelSelected();game9AfterAction('Jornada',`O grupo viajou para ${game9Terrain(selected)}.`);return}}catch(e){}}game9.route={q:selected.q,r:selected.r,name:selected.seen?(game9Poi(selected)?.name||game9Terrain(selected)):'Território desconhecido'};game9Save();game9.lastResolution=`Destino marcado: ${game9.route.name}. Selecione hexes adjacentes para avançar pela rota.`;game9RenderAll();game9Toast('Destino de jornada marcado.')}
function game9CenterCurrent(){try{if(typeof wwnCenterOn==='function')wwnCenterOn(current)}catch(e){}}
function game9PulseWorld(){try{if(typeof gameWorldTurn==='function')gameWorldTurn('pulso do diretor de cena')}catch(e){}game9.lastWorldPulse=game9.turn;game9AfterAction('Mundo vivo','NPCs e facções avançaram fora da cena do jogador.')}
function game9Resume(){if(typeof appGo==='function')appGo('inicio');window.scrollTo({top:0,behavior:'smooth'});game9NewScene('retomada da sessão')}
function game9Hook(){if(window.__game9Hooked)return;window.__game9Hooked=true;try{if(typeof showView==='function'){const old=showView;showView=function(v){old(v);requestAnimationFrame(game9RenderAll)}}}catch(e){}try{if(typeof wwnRenderMap==='function'){const oldMap=wwnRenderMap;wwnRenderMap=function(){oldMap();requestAnimationFrame(game9RenderAll)};render=wwnRenderMap}}catch(e){}try{if(typeof gameRefreshAll==='function'){const oldRefresh=gameRefreshAll;gameRefreshAll=function(){oldRefresh();game9RenderAll()}}}catch(e){}}
function game9Init(){game9Hook();game9Inject();if(!game9.narration)game9.narration=game9Compose();game9RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game9Init);else game9Init();
