'use strict';
/* GAME_RUNTIME_V24 — integra PLAYER_ACTION, resolução local, estado, Gemini, imagem e checkpoints. */
const GAME24_STORAGE='wwn_game_runtime_v24';
const game24Default={turns:[],stage:'idle',lastAction:'',lastIntent:'',lastMechanical:'',lastNarrative:'',lastDelta:[],pendingSince:0,autoCheckpointEvery:4,lastCheckpointTurn:0,lastError:'',stamp:0};
function game24Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game24Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game24=game24Merge(game24Default,JSON.parse(localStorage.getItem(GAME24_STORAGE)||'null'));
function game24Save(){localStorage.setItem(GAME24_STORAGE,JSON.stringify(game24))}
function game24Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game24Toast(s){try{if(typeof toast==='function')toast(s)}catch(e){}}
function game24Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game24Char(){try{return gameState?.character||{}}catch(e){return{}}}
function game24Combat(){try{return gameState?.combat||{enemies:[]}}catch(e){return{enemies:[]}}}
function game24Quest(){try{return typeof game14ActiveQuest==='function'?game14ActiveQuest():typeof game8ActiveQuest==='function'?game8ActiveQuest():null}catch(e){return null}}
function game24Time(){try{return typeof clockLabel==='function'?clockLabel():'Sessão ativa'}catch(e){return'Sessão ativa'}}
function game24Tile(){try{return typeof currentTile==='function'?currentTile():null}catch(e){return null}}
function game24Pos(){const t=game24Tile();return t?`${t.q},${t.r}`:''}
function game24Snapshot(){const c=game24Char(),co=game24Combat(),q=game24Quest();return{hp:Number(c.hp||0),maxHp:Number(c.maxHp||0),effort:Number(c.effort||0),strain:Number(c.strain||0),silver:Number(c.silver||0),xp:Number(c.xp||0),pos:game24Pos(),time:game24Time(),quest:q?`${q.id||q.title}:${q.progress||0}/${q.max||0}:${q.status||''}`:'',enemies:(co.enemies||[]).map(x=>({name:x.name,hp:Number(x.hp||0)}))}}
function game24Diff(a,b){const out=[];const push=(label,from,to,cls='')=>{if(String(from)!==String(to))out.push({label,from,to,cls})};push('PV',a.hp,b.hp,b.hp<a.hp?'bad':'good');push('Esforço',a.effort,b.effort,b.effort<a.effort?'bad':'good');push('Strain',a.strain,b.strain,b.strain>a.strain?'bad':'good');push('Prata',a.silver,b.silver,b.silver<a.silver?'bad':'good');push('XP',a.xp,b.xp,b.xp>a.xp?'good':'');push('Posição',a.pos,b.pos,'');push('Tempo',a.time,b.time,'');push('Missão',a.quest,b.quest,'');const am=new Map((a.enemies||[]).map(x=>[x.name,x.hp]));for(const e of b.enemies||[]){const old=am.get(e.name);if(old!==undefined&&old!==e.hp)out.push({label:e.name,from:old,to:e.hp,cls:e.hp<old?'good':'bad'})}return out.slice(0,12)}
function game24Pending(){try{return !!game15?.pending}catch(e){return false}}
function game24PendingLabel(){try{const p=game15?.pending;return p?`${p.label||'Teste'} • ${p.skill||''} / ${p.attr||''} • dificuldade ${p.diff||'?'}`:''}catch(e){return''}}
function game24LatestMechanical(){try{const r=game15?.lastRoll;if(!r)return'';if(r.kind==='skill')return`${r.label||'Teste'}: ${r.total} contra ${r.dc} — ${r.success?'sucesso':'falha'}`;if(r.kind==='save')return`${r.label}: ${r.total} contra ${r.target}+ — ${r.success?'sucesso':'falha'}`;if(r.kind==='reaction')return`${r.label}: ${r.total} — ${r.band}`;if(r.kind==='initiative')return`${r.label}: ${r.winner} agem primeiro`;return r.label||r.kind||''}catch(e){return''}}
function game24LatestNarrative(){try{if(game10?.lastResponse)return game10.lastResponse;if(game9?.narration)return game9.narration}catch(e){}return''}
function game24StageLabel(){return{idle:'pronto',action:'ação recebida',rules:'checando regra',resolve:'resolução pendente',narrate:'Gemini narrando',aftermath:'consequências',done:'turno concluído',error:'atenção'}[game24.stage]||game24.stage}
function game24Steps(){const order=['action','rules','resolve','narrate'];const idx={idle:-1,action:0,rules:1,resolve:2,narrate:3,aftermath:4,done:5,error:5}[game24.stage]??-1;return order.map((s,i)=>({name:s,label:{action:'Ação',rules:'Regra',resolve:'Estado',narrate:'Narrativa'}[s],state:i<idx?'done':i===idx?'on':''}))}
function game24Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game24Home')){const a=document.getElementById('game10Console')||document.getElementById('game9Play')||document.getElementById('game14Home');a?.insertAdjacentHTML('afterend','<div id="game24Home" class="game24-runtime"></div>')}const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game24Master')){const a=document.getElementById('game23Master')||document.getElementById('game22Rules')||document.getElementById('game14Master');a?.insertAdjacentHTML('afterend','<div id="game24Master" class="game24-runtime"></div>')}const se=document.getElementById('sessoes');if(se&&!document.getElementById('game24Sessions')){const a=document.getElementById('game23Ledger')||document.getElementById('game21Progress')||document.getElementById('game16Sessions');a?.insertAdjacentHTML('afterend','<div id="game24Sessions" class="game24-runtime"></div>')}}
function game24RenderHome(){const el=document.getElementById('game24Home');if(!el)return;const steps=game24Steps(),c=game24Char(),pending=game24Pending(),alive=(game24Combat().enemies||[]).filter(x=>x.hp>0).length;el.innerHTML=`<div class="section-cap">Orquestrador do turno</div><div class="game24-card orn-card"><div class="game24-head"><div><span class="game24-label">Fluxo automático do VTT</span><h3>${game24Esc(game24StageLabel())}</h3></div><span class="game24-state ${game24.stage==='done'?'ok':pending?'warn':game24.stage==='narrate'?'busy':''}">${game24Esc(game24StageLabel())}</span></div><div class="game24-flow">${steps.map(x=>`<div class="game24-step ${x.state}"><b>${x.label}</b><small>${x.state==='done'?'ok':x.state==='on'?'agora':'aguardando'}</small></div>`).join('')}</div><div class="game24-kpis"><div class="game24-kpi"><b>${c.hp??0}/${c.maxHp??0}</b><small>PV</small></div><div class="game24-kpi"><b>${c.strain??0}/${c.maxStrain??0}</b><small>Strain</small></div><div class="game24-kpi"><b>${alive}</b><small>ameaças</small></div><div class="game24-kpi"><b>${game24.turns.length}</b><small>turnos</small></div></div>${pending?`<div class="game24-alert"><b>Resolução mecânica pendente:</b> ${game24Esc(game24PendingLabel())}</div>`:''}${game24.lastMechanical?`<div class="game24-resolution"><b>Mecânica:</b> ${game24Esc(game24.lastMechanical)}</div>`:''}${game24.lastDelta.length?`<div class="game24-delta">${game24.lastDelta.map(d=>`<span class="${d.cls||''}">${game24Esc(d.label)}: ${game24Esc(d.from)} → ${game24Esc(d.to)}</span>`).join('')}</div>`:''}<div class="game24-actions">${pending?'<button class="primary" onclick="game24ResolvePending()">Resolver teste pendente</button>':''}<button onclick="game24NarrateNow()">Narrar estado atual</button><button onclick="game24Checkpoint()">Checkpoint</button><button onclick="game24Continue()">Continuar cena</button></div>${game24.lastError?`<div class="game24-alert">${game24Esc(game24.lastError)}</div>`:''}</div>`}
function game24RenderMaster(){const el=document.getElementById('game24Master');if(!el)return;el.innerHTML=`<div class="section-cap">Auditoria dos turnos</div><div class="game24-card orn-card"><div class="game24-head"><div><span class="game24-label">Ação → regra → estado → Gemini</span><h3>${game24.turns.length} turnos rastreados</h3></div><span class="game24-state ${game24.lastError?'warn':'ok'}">${game24.lastError?'atenção':'íntegro'}</span></div><div class="game24-master-list">${game24.turns.slice(0,8).map(t=>`<div class="game24-master-row"><b>#${t.n} • ${game24Esc(t.action||'ação')}</b><small>${game24Esc(t.mechanical||'sem resolução mecânica registrada')}</small>${t.delta?.length?`<small>${t.delta.map(d=>`${d.label} ${d.from}→${d.to}`).join(' • ')}</small>`:''}<small>${game24Esc(t.time||'')}</small></div>`).join('')||'<div class="game24-note">Nenhum turno foi fechado pelo orquestrador ainda.</div>'}</div><div class="game24-note">O orquestrador não decide regras novas. Ele apenas encadeia os motores já existentes, registra o que mudou e garante que o Gemini narre depois da resolução local.</div></div>`}
function game24RenderSessions(){const el=document.getElementById('game24Sessions');if(!el)return;const rows=game24.turns.slice(0,12);el.innerHTML=`<div class="section-cap">Transcrição de jogo</div><div class="game24-card orn-card">${rows.length?`<div class="game24-transcript">${rows.map(t=>`<div class="game24-turn"><div class="game24-turn-head"><b>#${t.n} ${game24Esc(t.intent||'ação')}</b><span>${game24Esc(t.time||'')}</span></div><small><b>Você:</b> ${game24Esc(t.action||'')}</small>${t.mechanical?`<small><b>Motor:</b> ${game24Esc(t.mechanical)}</small>`:''}${t.narrative?`<small class="gm"><b>Mestre:</b> ${game24Esc(t.narrative.slice(0,360))}${t.narrative.length>360?'…':''}</small>`:''}</div>`).join('')}</div>`:'<div class="game24-note">A transcrição automática começa quando você envia ações pelo campo “Sua ação”.</div>'}</div>`}
function game24RenderAll(){game24Inject();game24RenderHome();game24RenderMaster();game24RenderSessions();game24Save()}
function game24FinalizeTurn(action,intent,before,after){const mechanical=game24LatestMechanical(),narrative=game24LatestNarrative(),delta=game24Diff(before,after),n=game24.turns.length?game24.turns[0].n+1:1;const row={n,action,intent,mechanical,narrative,delta,time:game24Time(),stamp:Date.now()};game24.turns.unshift(row);game24.turns=game24.turns.slice(0,80);game24.lastAction=action;game24.lastIntent=intent;game24.lastMechanical=mechanical;game24.lastNarrative=narrative;game24.lastDelta=delta;game24.stage='done';game24.stamp=Date.now();game24Save();game24Log('turn',`Turno ${n} concluído`,`${action} • ${mechanical||'sem teste'} • ${delta.length} mudanças`);if(game24.autoCheckpointEvery>0&&n-game24.lastCheckpointTurn>=game24.autoCheckpointEvery){game24.lastCheckpointTurn=n;try{if(typeof game16AutoSnapshot==='function')game16AutoSnapshot(`turno ${n}`)}catch(e){}game24Save()}try{if(typeof game19RefreshPrompt==='function')setTimeout(()=>game19RefreshPrompt(),120)}catch(e){}game24RenderAll()}
async function game24ResolvePending(){if(!game24Pending())return;const before=game24Snapshot();game24.stage='resolve';game24.lastError='';game24Save();game24RenderAll();try{if(typeof game15RollPending==='function')game15RollPending();game24.lastMechanical=game24LatestMechanical();game24.stage='narrate';game24RenderAll();if(typeof g11Scene==='function'&&typeof g11Ready==='function'&&g11Ready())await g11Scene(false);const after=game24Snapshot();game24FinalizeTurn(game24.lastAction||'resolução pendente',game24.lastIntent||'teste',before,after)}catch(e){game24.stage='error';game24.lastError=e?.message||String(e);game24Save();game24RenderAll()}}
async function game24NarrateNow(){game24.stage='narrate';game24.lastError='';game24Save();game24RenderAll();try{if(typeof g11Scene==='function'){await g11Scene(true);game24.lastNarrative=game24LatestNarrative();game24.stage='done'}else throw new Error('Gerador narrativo indisponível.')}catch(e){game24.stage='error';game24.lastError=e?.message||String(e)}game24Save();game24RenderAll()}
function game24Checkpoint(){try{if(typeof game16AutoSnapshot==='function')game16AutoSnapshot('checkpoint do orquestrador');if(typeof game12Checkpoint==='function')game12Checkpoint();game24Toast('Checkpoint criado.')}catch(e){game24Toast('Não foi possível criar o checkpoint.')}}
function game24Continue(){try{if(typeof game9NewScene==='function')game9NewScene('continuação solicitada pelo jogador');else if(typeof g11Scene==='function')g11Scene(true)}catch(e){} }
function game24HookAction(){if(window.__game24ActionHooked)return;if(typeof game10Submit!=='function')return;window.__game24ActionHooked=true;const old=game10Submit;window.game10Submit=async function(...args){const input=document.getElementById('game10Action'),action=input?.value.trim()||'';if(!action)return old.apply(this,args);const intent=typeof game10Intent==='function'?game10Intent(action):'livre',before=game24Snapshot();game24.lastAction=action;game24.lastIntent=intent;game24.stage='action';game24.lastError='';game24.lastDelta=[];game24.lastMechanical='';game24Save();game24RenderAll();try{game24.stage='rules';game24RenderAll();const result=old.apply(this,args);if(result&&typeof result.then==='function')await result;await new Promise(r=>setTimeout(r,80));if(game24Pending()){game24.stage='resolve';game24.pendingSince=Date.now();game24.lastMechanical='Teste mecânico solicitado pelo motor e ainda não resolvido.';game24Save();game24RenderAll();return}game24.stage='narrate';game24RenderAll();await new Promise(r=>setTimeout(r,120));const after=game24Snapshot();game24FinalizeTurn(action,intent,before,after)}catch(e){game24.stage='error';game24.lastError=e?.message||String(e);game24Save();game24RenderAll()}}}
function game24HookCombat(){if(window.__game24CombatHooked)return;window.__game24CombatHooked=true;try{if(typeof gameNextRound==='function'){const old=gameNextRound;window.gameNextRound=function(...a){const before=game24Snapshot(),r=old.apply(this,a),after=game24Snapshot();const n=game24.turns.length?game24.turns[0].n+1:1;game24.turns.unshift({n,action:'resolver próxima rodada de combate',intent:'combate',mechanical:'Fase da oposição e avanço de rodada resolvidos pelo motor local.',narrative:game24LatestNarrative(),delta:game24Diff(before,after),time:game24Time(),stamp:Date.now()});game24.turns=game24.turns.slice(0,80);game24Save();setTimeout(()=>{try{if(typeof g11Scene==='function')g11Scene(false)}catch(e){}game24RenderAll()},50);return r}}}catch(e){}}
function game24Hook(){if(window.__game24Hooked)return;window.__game24Hooked=true;game24HookAction();game24HookCombat();try{if(typeof showView==='function'){const old=showView;window.showView=function(v){old(v);if(['inicio','mestre','sessoes'].includes(v))requestAnimationFrame(game24RenderAll)}}}catch(e){}setInterval(()=>{game24HookAction();game24HookCombat()},1000)}
function game24Init(){game24Hook();game24RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game24Init);else game24Init();
