'use strict';
/* GAME_RUNTIME_V35 — supervisor de combate: ciclo, fases, objetivos, moral pendente e auditoria. Sem UI. */
const GAME35_STORAGE='wwn_game_runtime_v35';
const game35Default={battle:null,history:[],seq:0,metrics:{started:0,ended:0,rounds:0,moraleRequests:0}};
let game35=Object.assign({},game35Default,JSON.parse(localStorage.getItem(GAME35_STORAGE)||'null')||{});
function game35Save(){try{localStorage.setItem(GAME35_STORAGE,JSON.stringify(game35))}catch(e){}}
function game35Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game35Emit(t,p){try{window.WWN_ENGINE?.emit?.(t,p)}catch(e){}}
function game35Combat(){try{return window.gameState?.combat||{enemies:[]}}catch(e){return{enemies:[]}}}
function game35AliveEnemies(){return (game35Combat().enemies||[]).filter(e=>Number(e.hp||0)>0)}
function game35Char(){return window.gameState?.character||{}}
function game35Round(){return Math.max(1,Number(window.appState?.combatRound||1))}
function game35Snapshot(){const co=game35Combat(),c=game35Char();return{round:game35Round(),player:{hp:Number(c.hp||0),maxHp:Number(c.maxHp||0),mortal:!!window.game15?.injury?.mortallyWounded,dead:!!window.game15?.injury?.dead},enemies:(co.enemies||[]).map(e=>({name:e.name,hp:Number(e.hp||0),maxHp:Number(e.maxHp||0),ac:Number(e.ac||0)})),target:Number(co.target||0),range:window.game20?.range||'',cover:window.game20?.cover||''}}
function game35Start(title='Encontro'){if(game35.battle&&game35.battle.status==='active')return game35.battle;const snap=game35Snapshot();if(!snap.enemies.some(e=>e.hp>0))return null;const b={id:`b${Date.now()}_${++game35.seq}`,title,status:'active',startedAt:Date.now(),startRound:snap.round,phase:'setup',initiative:null,rounds:[],moralePending:[],objective:'sobreviver e resolver a ameaça',start:snap,last:snap,result:null};game35.battle=b;game35.metrics.started++;game35Save();game35Emit('combat.started',game35Clone(b));try{window.WWN_RESILIENCE?.checkpoint?.('combat',`início ${title}`)}catch(e){}return b}
function game35Ensure(){if(game35.battle?.status==='active')return game35.battle;if(game35AliveEnemies().length)return game35Start('Encontro em andamento');return null}
function game35SetObjective(text){const b=game35Ensure();if(!b)return null;b.objective=String(text||'').trim()||b.objective;game35Save();return b}
function game35Initiative(){const b=game35Ensure();if(!b)return null;if(b.initiative)return b.initiative;let r=null;try{if(typeof game15Initiative==='function')r=game15Initiative()}catch(e){}b.initiative=r?game35Clone(r):{kind:'pending',reason:'iniciativa não resolvida'};b.phase=r?.winner==='oposição'?'enemy-turn':'player-turn';game35Save();game35Emit('combat.initiative',game35Clone(b.initiative));return b.initiative}
function game35OpenRound(){const b=game35Ensure();if(!b)return null;const n=game35Round();let row=b.rounds.find(x=>x.round===n);if(!row){row={round:n,openedAt:Date.now(),before:game35Snapshot(),events:[],after:null,closedAt:0};b.rounds.push(row);b.rounds=b.rounds.slice(-40);game35.metrics.rounds++}b.phase=b.phase==='setup'?'player-turn':b.phase;game35Save();return row}
function game35Record(type,detail,payload={}){const b=game35Ensure();if(!b)return null;const row=game35OpenRound();const e={stamp:Date.now(),type,detail:String(detail||''),payload:game35Clone(payload)};row.events.push(e);row.events=row.events.slice(-30);b.last=game35Snapshot();game35Save();game35Emit('combat.event',{battleId:b.id,round:row.round,...e});return e}
function game35EnemyLosses(before,after){const a=new Map((before?.enemies||[]).map(e=>[e.name,e])),out=[];for(const e of after?.enemies||[]){const old=a.get(e.name);if(old&&old.hp>0&&e.hp<=0)out.push(e.name)}return out}
function game35RequestMorale(reason,names=[]){const b=game35Ensure();if(!b)return null;const q=`morale check combat enemy morale Worlds Without Number ${reason}`;let evidence=[];try{if(typeof game26Search==='function')evidence=game26Search(q,5).map(x=>({source:x.row.sourceName,page:x.row.page||0,text:x.row.text.slice(0,800),score:x.score}))}catch(e){}const req={id:`mor${Date.now()}_${Math.random().toString(36).slice(2,6)}`,reason,names:names.slice(),evidence,status:evidence.length?'pending':'unsupported',stamp:Date.now()};b.moralePending.push(req);b.moralePending=b.moralePending.slice(-20);game35.metrics.moraleRequests++;game35Save();game35Emit('combat.morale.requested',game35Clone(req));return req}
function game35ResolveMorale(id,outcome){const b=game35Ensure();const r=b?.moralePending?.find(x=>x.id===id);if(!r)return null;r.status='resolved';r.outcome=String(outcome||'').trim();r.resolvedAt=Date.now();game35Save();game35Record('morale',r.outcome||'moral resolvida',{request:id,names:r.names});return r}
function game35CloseRound(){const b=game35Ensure();if(!b)return null;const row=game35OpenRound(),after=game35Snapshot();row.after=after;row.closedAt=Date.now();const losses=game35EnemyLosses(row.before,after);if(losses.length&&!b.moralePending.some(x=>x.status==='pending'&&x.reason.includes(`rodada ${row.round}`)))game35RequestMorale(`perdas na rodada ${row.round}`,losses);b.last=after;const state=game35CheckEnd();if(state)b.result=state;game35Save();return row}
function game35CheckEnd(){const b=game35.battle;if(!b||b.status!=='active')return null;const c=game35Char(),alive=game35AliveEnemies();if(!alive.length)return game35End('victory','Todas as ameaças registradas ficaram fora de combate.');if(window.game15?.injury?.dead)return game35End('death','O personagem morreu.');if(Number(c.hp||0)<=0)return{status:'critical',detail:'Personagem a 0 PV; siga o estado de Ferimento Mortal do motor.'};return null}
function game35End(outcome='ended',detail='Encontro encerrado'){const b=game35.battle;if(!b||b.status!=='active')return b;b.status='ended';b.outcome=outcome;b.detail=detail;b.endedAt=Date.now();b.last=game35Snapshot();game35.history.unshift(game35Clone(b));game35.history=game35.history.slice(0,40);game35.metrics.ended++;game35Save();game35Emit('combat.ended',{id:b.id,outcome,detail,last:b.last});try{window.WWN_RESILIENCE?.checkpoint?.('combat',`fim ${b.title} • ${outcome}`)}catch(e){}return b}
function game35Audit(){const b=game35.battle,issues=[],warn=[];const co=game35Combat();if(b?.status==='active'&&!co.enemies?.length)issues.push('combate ativo sem inimigos');if(Number(co.target||0)>=Number(co.enemies?.length||0)&&co.enemies?.length)warn.push('alvo fora da faixa');if(game35Round()<1)issues.push('rodada inválida');if(game35Char().hp>game35Char().maxHp)issues.push('PV acima do máximo');return{ok:!issues.length,issues,warn,battleId:b?.id||'',round:game35Round(),stamp:Date.now()}}
function game35Context(){const b=game35.battle;if(!b||b.status!=='active')return{};return{combatSupervisor:{battleId:b.id,objective:b.objective,phase:b.phase,initiative:b.initiative,round:game35Round(),aliveEnemies:game35AliveEnemies().map(e=>({name:e.name,hp:e.hp,maxHp:e.maxHp})),moralePending:b.moralePending.filter(x=>x.status==='pending').map(x=>({reason:x.reason,names:x.names})),instruction:'Não resolva moral pendente, iniciativa pendente ou efeitos não registrados. Narre o estado e aguarde o motor.'}}}
function game35Hook(){if(window.__game35Hook)return;window.__game35Hook=true;try{window.WWN_ENGINE?.on?.('transaction.committed',evt=>{const k=evt.payload?.kind||'';if(/^combat\./.test(k)){const b=game35Ensure();if(!b)return;game35Record(k,'Transação de combate confirmada',evt.payload);game35CheckEnd()}})}catch(e){}try{if(typeof game20NextRound==='function'&&!game20NextRound.__g35){const old=game20NextRound;const wrapped=function(...a){game35CloseRound();const r=old.apply(this,a);game35OpenRound();game35CheckEnd();return r};wrapped.__g35=true;window.game20NextRound=wrapped}}catch(e){}try{if(typeof game20End==='function'&&!game20End.__g35){const old=game20End;const wrapped=function(...a){game35End('manual','Encontro encerrado manualmente.');return old.apply(this,a)};wrapped.__g35=true;window.game20End=wrapped}}catch(e){}try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(...a){return Object.assign({},old.apply(this,a),game35Context())}}}catch(e){}}
function game35Api(){window.WWN_COMBAT={version:35,start:game35Start,initiative:game35Initiative,openRound:game35OpenRound,closeRound:game35CloseRound,record:game35Record,requestMorale:game35RequestMorale,resolveMorale:game35ResolveMorale,end:game35End,audit:game35Audit,setObjective:game35SetObjective,getState:()=>game35}}
function game35Init(){game35Hook();game35Api();if(game35AliveEnemies().length){game35Ensure();game35OpenRound()}game35Emit('combat.supervisor.ready',{version:35,audit:game35Audit()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game35Init);else game35Init();
