'use strict';
/* GAME_RUNTIME_V33 — companhia: agentes aliados, lealdade, fadiga, ferimentos, tarefas e retorno. Sem UI. */
const GAME33_STORAGE='wwn_game_runtime_v33';
const game33Default={members:{},missions:[],history:[],tick:0,lastSync:0,metrics:{assigned:0,completed:0,failed:0,departures:0}};
let game33=Object.assign({},game33Default,JSON.parse(localStorage.getItem(GAME33_STORAGE)||'null')||{});
function game33Save(){try{localStorage.setItem(GAME33_STORAGE,JSON.stringify(game33))}catch(e){}}
function game33Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game33Emit(t,p){try{window.WWN_ENGINE?.emit?.(t,p)}catch(e){}}
function game33Npcs(){try{return Array.isArray(gameState?.npcs)?gameState.npcs:[]}catch(e){return[]}}
function game33PartyNames(){try{return Array.isArray(game13?.party)?game13.party.slice():[]}catch(e){return[]}}
function game33Rel(name){try{return Number(game12?.relations?.[name]||0)}catch(e){return 0}}
function game33Seed(){const party=new Set(game33PartyNames());for(const n of game33Npcs()){if(!n?.name)continue;if(!game33.members[n.name])game33.members[n.name]={name:n.name,role:n.role||'Aliado',location:n.location||'',status:party.has(n.name)?'with-party':'contact',loyalty:Math.max(-3,Math.min(3,game33Rel(n.name))),morale:3,fatigue:0,wounds:0,assignment:'',returnAt:0,notes:'',lastSeen:Date.now()};const m=game33.members[n.name];m.role=n.role||m.role;m.location=n.location||m.location;if(party.has(n.name)&&!['away','incapacitated'].includes(m.status))m.status='with-party';else if(!party.has(n.name)&&m.status==='with-party')m.status='contact';m.loyalty=Math.max(-3,Math.min(3,game33Rel(n.name)||m.loyalty||0))}for(const name of Object.keys(game33.members))if(!game33Npcs().some(n=>n.name===name))game33.members[name].orphan=true;game33.lastSync=Date.now();game33Save()}
function game33Abs(){try{return typeof game28AbsTime==='function'?game28AbsTime():0}catch(e){return 0}}
function game33Member(name){game33Seed();return game33.members[name]||null}
function game33SetStatus(name,status){const m=game33Member(name);if(!m)return null;m.status=status;m.lastSeen=Date.now();game33Save();game33Emit('party.member.status',{name,status});return m}
function game33Assign(name,{title='Tarefa',detail='',durationHours=24,visibility='player',risk='unknown',authority='configured'}={}){const m=game33Member(name);if(!m)throw new Error('Aliado inexistente.');if(m.status==='away')throw new Error('Aliado já está fora de cena.');const mission={id:`pm${Date.now()}_${Math.random().toString(36).slice(2,6)}`,member:name,title,detail,startedAt:game33Abs(),dueAt:game33Abs()+Math.max(1,Number(durationHours||1))*60,status:'active',visibility,risk,authority,result:null};m.status='away';m.assignment=title;m.returnAt=mission.dueAt;game33.missions.unshift(mission);game33.metrics.assigned++;game33Save();game33Emit('party.mission.started',game33Clone(mission));return mission}
function game33ResolveMission(mission,{success=null,result='',location=''}={}){if(!mission||mission.status!=='active')return mission;const m=game33Member(mission.member);mission.status=success===false?'failed':'completed';mission.completedAt=Date.now();mission.result=result||'';if(m){m.status=m.wounds>=3?'incapacitated':'contact';m.assignment='';m.returnAt=0;if(location)m.location=location;if(success===false){m.morale=Math.max(0,m.morale-1);m.fatigue=Math.min(6,m.fatigue+1)}else if(success===true)m.morale=Math.min(6,m.morale+1)}if(success===false)game33.metrics.failed++;else game33.metrics.completed++;game33.history.unshift({stamp:Date.now(),member:mission.member,title:mission.title,status:mission.status,result:mission.result});game33.history=game33.history.slice(0,100);game33Save();game33Emit('party.mission.resolved',game33Clone(mission));return mission}
function game33Due(){const now=game33Abs();for(const mission of game33.missions.filter(x=>x.status==='active'&&x.dueAt<=now)){if(mission.authority==='configured'&&mission.result){game33ResolveMission(mission,{success:true,result:mission.result});continue}mission.status='awaiting-resolution';const m=game33Member(mission.member);if(m){m.status='away';m.returnAt=mission.dueAt}game33Emit('party.mission.awaiting',{id:mission.id,member:mission.member,title:mission.title})}game33Save()}
function game33SetMissionOutcome(id,success,result=''){const mission=game33.missions.find(x=>x.id===id);if(!mission)return null;if(!['active','awaiting-resolution'].includes(mission.status))return mission;mission.status='active';return game33ResolveMission(mission,{success:!!success,result})}
function game33Pulse(reason='avanço da companhia'){game33.tick++;game33Seed();game33Due();for(const m of Object.values(game33.members)){if(m.orphan)continue;if(m.status==='with-party'){m.fatigue=Math.min(6,Math.max(0,Number(m.fatigue||0)+(game33.tick%3===0?1:0)));if(m.fatigue>=5)m.morale=Math.max(0,m.morale-1)}if(m.wounds>=3)m.status='incapacitated';if(m.loyalty<=-3&&m.status==='with-party'){m.status='contact';game33.metrics.departures++;game33Emit('party.member.departed',{name:m.name,reason:'lealdade muito baixa'})}}game33Save();game33Emit('party.pulse',{tick:game33.tick,reason})}
function game33Rest(hours=8){for(const m of Object.values(game33.members)){if(m.status!=='with-party')continue;if(hours>=8){m.fatigue=Math.max(0,m.fatigue-2);m.morale=Math.min(6,m.morale+1)}else m.fatigue=Math.max(0,m.fatigue-1)}game33Save();game33Emit('party.rest',{hours})}
function game33Wound(name,delta=1){const m=game33Member(name);if(!m)return;m.wounds=Math.max(0,Math.min(4,Number(m.wounds||0)+Number(delta||0)));if(m.wounds>=3)m.status='incapacitated';game33Save();game33Emit('party.member.wounds',{name,wounds:m.wounds})}
function game33Context(){game33Seed();return{company:{present:Object.values(game33.members).filter(m=>m.status==='with-party'&&!m.orphan).map(m=>({name:m.name,role:m.role,loyalty:m.loyalty,morale:m.morale,fatigue:m.fatigue,wounds:m.wounds})),away:Object.values(game33.members).filter(m=>m.status==='away'&&!m.orphan).map(m=>({name:m.name,assignment:m.assignment,returnAt:m.returnAt})),knownMissionResults:game33.history.slice(0,8),instruction:'Aliados presentes podem participar narrativamente, mas não conceda bônus mecânicos sem resolução explícita do motor.'}}}
function game33Hook(){if(window.__game33Hook)return;window.__game33Hook=true;try{window.WWN_ENGINE?.on?.('transaction.committed',evt=>{const k=evt.payload?.kind||'';if(k==='time.advance'||k==='player.action')game33Due();if(k==='time.advance')game33Pulse('tempo avançou')})}catch(e){}try{if(typeof game15Rest==='function'&&!game15Rest.__g33){const old=game15Rest;const wrapped=function(...a){const r=old.apply(this,a);game33Rest(8);return r};wrapped.__g33=true;window.game15Rest=wrapped}}catch(e){}try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(...a){return Object.assign({},old.apply(this,a),game33Context())}}}catch(e){}}
function game33Api(){window.WWN_PARTY={version:33,seed:game33Seed,member:game33Member,assign:game33Assign,setMissionOutcome:game33SetMissionOutcome,pulse:game33Pulse,rest:game33Rest,wound:game33Wound,getState:()=>game33}}
function game33Init(){game33Seed();game33Due();game33Hook();game33Api();game33Emit('party.ready',{version:33})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game33Init);else game33Init();
