'use strict';
/* GAME_RUNTIME_V15 — resolução mecânica WWN baseada no SRD: testes, saves, iniciativa, reação e ferimentos. */
const GAME15_STORAGE='wwn_game_runtime_v15';
const game15Default={pending:null,lastRoll:null,history:[],injury:{mortallyWounded:false,frail:false,dead:false,downRound:0,deathRound:0,stabilized:false},initiative:null,lastReaction:null};
function game15Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game15Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game15=game15Merge(game15Default,JSON.parse(localStorage.getItem(GAME15_STORAGE)||'null'));
function game15Save(){localStorage.setItem(GAME15_STORAGE,JSON.stringify(game15));try{if(typeof gameSave==='function')gameSave()}catch(e){}}
function game15Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game15Toast(s){if(typeof toast==='function')toast(s)}
function game15Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game15Char(){return window.gameState?.character||{}}
function game15EnsureChar(){const c=game15Char();if(!c.attributes)c.attributes={str:10,dex:10,con:10,int:10,wis:10,cha:10};for(const k of ['str','dex','con','int','wis','cha'])if(!Number.isFinite(Number(c.attributes[k])))c.attributes[k]=10;if(!c.combatProfile)c.combatProfile={enabled:false,baseAttack:0,skill:0,attr:'str',weapon:'Arma preparada',damage:'1d8',shock:0,shockAC:0,meleeAC:15,rangedAC:15};return c}
function game15Mod(score){const n=Number(score)||10;if(n<=3)return-2;if(n<=7)return-1;if(n<=13)return 0;if(n<=17)return 1;return 2}
function game15Level(){return Math.max(1,Number(game15Char().level||1))}
function game15SaveTargets(){const c=game15EnsureChar(),a=c.attributes,l=game15Level();return{physical:16-l-Math.max(game15Mod(a.str),game15Mod(a.con)),evasion:16-l-Math.max(game15Mod(a.dex),game15Mod(a.int)),mental:16-l-Math.max(game15Mod(a.wis),game15Mod(a.cha)),luck:16-l}}
function game15Skills(){const s=game15Char().skills;return Array.isArray(s)?s:[]}
function game15SkillLevel(name){const n=String(name||'').toLowerCase();const row=game15Skills().find(x=>String(Array.isArray(x)?x[0]:'').toLowerCase()===n);return row?Number(row[1]||0):null}
function game15FindSkill(names){const rows=game15Skills();for(const wanted of names){const w=wanted.toLowerCase();const row=rows.find(x=>String(x[0]||'').toLowerCase().includes(w));if(row)return row[0]}return rows[0]?.[0]||'Sem perícia'}
function game15Die(sides){return 1+Math.floor(Math.random()*sides)}
function game15PushHistory(r){game15.lastRoll=r;game15.history.unshift(r);game15.history=game15.history.slice(0,24);game15Save()}
function game15RollSkill(skill,attr,diff,sit=0,label='Teste de perícia'){const c=game15EnsureChar(),level=game15SkillLevel(skill),untrained=level===null,skillBonus=untrained?-1:level,am=game15Mod(c.attributes[attr]??10),d1=game15Die(6),d2=game15Die(6),total=d1+d2+skillBonus+am+Number(sit||0),dc=Number(diff||8),ok=total>=dc;const r={kind:'skill',label,skill,attr,dice:[d1,d2],skillBonus,attrMod:am,sit:Number(sit||0),total,dc,success:ok,stamp:Date.now()};game15PushHistory(r);game15Log('roll',label,`${d1}+${d2}${skillBonus>=0?'+':''}${skillBonus}${am>=0?'+':''}${am}${sit?`${sit>=0?'+':''}${sit}`:''} = ${total} contra ${dc} — ${ok?'sucesso':'falha'}`);game15.pending=null;game15Save();game15RenderAll();game15NarrateResolution(r);return r}
function game15RollPending(){const p=game15.pending;if(!p)return;game15RollSkill(p.skill,p.attr,p.diff,p.sit||0,p.label||'Teste solicitado pelo Mestre')}
function game15RollSave(type,bonus=0){const labels={physical:'Físico',evasion:'Evasão',mental:'Mental',luck:'Sorte'},targets=game15SaveTargets(),target=targets[type],die=game15Die(20),b=Number(bonus||0),total=die+b,success=die===20?true:die===1?false:total>=target;const r={kind:'save',label:`Salvamento ${labels[type]||type}`,type,die,bonus:b,total,target,success,stamp:Date.now()};game15PushHistory(r);game15Log('save',r.label,`d20 ${die}${b?`${b>=0?'+':''}${b}`:''} = ${total} contra ${target}+ — ${success?'sucesso':'falha'}`);game15RenderAll();game15NarrateResolution(r);return r}
function game15Reaction(){const c=game15EnsureChar(),cha=game15Mod(c.attributes.cha),d1=game15Die(6),d2=game15Die(6),total=d1+d2+cha;let band='previsível';if(total<=2)band='agressivamente hostil';else if(total<=5)band='mais hostil que o esperado';else if(total<=8)band='previsível para a situação';else if(total<=11)band='mais amigável que o esperado';else band='tão amigável quanto a situação permite';const r={kind:'reaction',label:'Reação do encontro',dice:[d1,d2],cha,total,band,stamp:Date.now()};game15.lastReaction=r;game15PushHistory(r);game15Log('oracle','Reação do encontro',`${d1}+${d2}${cha>=0?'+':''}${cha} = ${total} • ${band}`);game15RenderAll();game15NarrateResolution(r);return r}
function game15Initiative(){const c=game15EnsureChar(),dex=game15Mod(c.attributes.dex),pc=game15Die(8)+dex,npc=game15Die(8),winner=pc>=npc?'jogadores':'oposição';const r={kind:'initiative',label:'Iniciativa por lados',pc,npc,dex,winner,stamp:Date.now()};game15.initiative=r;game15PushHistory(r);game15Log('combat','Iniciativa',`Jogadores ${pc} vs oposição ${npc} — ${winner} agem primeiro`);game15RenderAll();return r}
function game15Suggested(intent,action=''){const map={explorar:{skill:game15FindSkill(['observ','notice','explor']),attr:'wis',diff:8,label:'Exploração cuidadosa'},investigar:{skill:game15FindSkill(['saber','know','notice','observ']),attr:'int',diff:8,label:'Investigação'},conversar:{skill:game15FindSkill(['convenc','talk','connect']),attr:'cha',diff:8,label:'Interação social'},observar:{skill:game15FindSkill(['observ','notice']),attr:'wis',diff:8,label:'Observação'},recursos:{skill:game15FindSkill(['sobreviv','survive']),attr:'wis',diff:8,label:'Busca de recursos'}};const s=map[intent];if(!s)return null;return{...s,sit:0,action}}
function game15RequestCheck(intent,action=''){const p=game15Suggested(intent,action);if(!p)return;game15.pending=p;game15Save();game15RenderAll()}
function game15SaveAttributes(){const c=game15EnsureChar();for(const k of ['str','dex','con','int','wis','cha']){const el=document.getElementById('g15_'+k);if(el)c.attributes[k]=Math.max(3,Math.min(18,Number(el.value||10)))}const p=c.combatProfile;const get=(id,fallback='')=>document.getElementById(id)?.value??fallback;p.baseAttack=Number(get('g15_bab',p.baseAttack)||0);p.skill=Number(get('g15_cskill',p.skill)||0);p.attr=get('g15_cattr',p.attr)||'str';p.weapon=get('g15_weapon',p.weapon)||'Arma preparada';p.damage=get('g15_damage',p.damage)||'1d8';p.shock=Math.max(0,Number(get('g15_shock',p.shock)||0));p.shockAC=Math.max(0,Number(get('g15_shockac',p.shockAC)||0));p.meleeAC=Math.max(1,Number(get('g15_mac',p.meleeAC)||15));p.rangedAC=Math.max(1,Number(get('g15_rac',p.rangedAC)||15));p.enabled=document.getElementById('g15_combatEnabled')?.checked||false;game15Save();game15Log('character','Atributos e combate atualizados','Modificadores, saves e perfil de arma recalculados.');game15RenderAll();game15Toast('Mecânica da ficha salva.')}
function game15ParseDice(expr){const m=String(expr||'1d6').toLowerCase().match(/^(\d+)d(\d+)([+-]\d+)?$/);if(!m)return{n:1,s:6,flat:0};return{n:Number(m[1]),s:Number(m[2]),flat:Number(m[3]||0)}}
function game15DamageRoll(expr,mod=0){const d=game15ParseDice(expr);let total=d.flat+Number(mod||0),rolls=[];for(let i=0;i<d.n;i++){const r=game15Die(d.s);rolls.push(r);total+=r}return{rolls,total}}
function game15ConfiguredAttack(){const c=game15EnsureChar(),p=c.combatProfile;if(!p.enabled)return false;const co=window.gameState?.combat;let target=co?.enemies?.[co.target];if(!target||target.hp<=0){const idx=co?.enemies?.findIndex(e=>e.hp>0)??-1;if(idx<0){game15Toast('Não há alvo ativo.');return true}co.target=idx;target=co.enemies[idx]}const die=game15Die(20),attr=game15Mod(c.attributes[p.attr]??10),skill=Number(p.skill||0),bab=Number(p.baseAttack||0),total=die+bab+attr+skill,hit=total>=target.ac;co.lastAttack={roll:die,bonus:bab+attr+skill,total,hit,target:co.target,game15:true};if(!hit&&Number(p.shock||0)>0&&(!p.shockAC||target.ac<=Number(p.shockAC))){const dmg=Math.max(0,Number(p.shock)+attr);target.hp=Math.max(0,target.hp-dmg);game15Log('combat',`Shock em ${target.name}`,`${dmg} de dano apesar do erro.`)}game15Save();try{document.getElementById('combatDie').textContent=die;document.getElementById('combatTotal').textContent=total;const out=document.getElementById('combatOutcome');if(out){out.textContent=hit?'ACERTO!':'ERRO';out.className=hit?'hit':'muted'}}catch(e){}game15Log('combat',`Ataque com ${p.weapon}`,`${die} + BAB ${bab} + atributo ${attr} + perícia ${skill} = ${total} contra CA ${target.ac}`);try{if(typeof gameRenderCombat==='function')gameRenderCombat()}catch(e){}game15RenderAll();return true}
function game15ConfiguredDamage(){const c=game15EnsureChar(),p=c.combatProfile,co=window.gameState?.combat,a=co?.lastAttack;if(!p.enabled)return false;if(!a||!a.hit){game15Toast('É preciso acertar antes de rolar dano.');return true}const target=co.enemies[a.target];if(!target||target.hp<=0){game15Toast('O alvo já está fora de combate.');return true}const attr=game15Mod(c.attributes[p.attr]??10),r=game15DamageRoll(p.damage,attr),minimum=Number(p.shock||0)+attr,total=Math.max(r.total,minimum>0?minimum:0);target.hp=Math.max(0,target.hp-total);co.lastAttack=null;game15Save();try{document.getElementById('damageTotal').textContent=total;if(typeof gameRenderCombat==='function')gameRenderCombat()}catch(e){}game15Log('combat',`Dano com ${p.weapon}`,`${r.rolls.join('+')}${attr>=0?'+':''}${attr} = ${total}; ${target.name} ${target.hp}/${target.maxHp} PV`);game15RenderAll();return true}
function game15FirstAid(){const c=game15EnsureChar();if(Number(c.strain||0)>=Number(c.maxStrain||0)){game15Toast('System Strain no máximo: o alvo não pode receber mais cura deste tipo.');return}const heal=game15SkillLevel(game15FindSkill(['curar','heal'])),bonus=heal===null?-1:heal,r=game15Die(6),amount=Math.max(0,r+bonus);c.hp=Math.min(Number(c.maxHp||1),Number(c.hp||0)+amount);c.strain=Math.min(Number(c.maxStrain||0),Number(c.strain||0)+1);game15Save();game15Log('healing','Primeiros socorros',`1d6 ${r}${bonus>=0?'+':''}${bonus} = ${amount} PV • System Strain ${c.strain}/${c.maxStrain}`);game15RenderAll()}
function game15Rest(privation=false){const c=game15EnsureChar(),lvl=game15Level();if(privation){game15Log('rest','Noite sob privação','Sem cura natural nem recuperação de System Strain.');game15Toast('Privação registrada.');return}if(!game15.injury.frail)c.hp=Math.min(Number(c.maxHp||1),Number(c.hp||0)+lvl);c.strain=Math.max(0,Number(c.strain||0)-1);game15Save();game15Log('rest','Boa noite de descanso',`+${game15.injury.frail?0:lvl} PV • -1 System Strain`);game15RenderAll()}
function game15SyncInjury(){const c=game15EnsureChar(),round=Number(window.appState?.combatRound||1);if(Number(c.hp||0)<=0&&!game15.injury.mortallyWounded&&!game15.injury.dead){game15.injury.mortallyWounded=true;game15.injury.downRound=round;game15.injury.deathRound=round+6;game15.injury.stabilized=false;game15Log('injury','Ferimento mortal',`Caiu na rodada ${round}; morte ao fim da rodada ${round+6} se não estabilizado.`)}if(game15.injury.mortallyWounded&&!game15.injury.stabilized&&round>=game15.injury.deathRound){game15.injury.dead=true;game15.injury.mortallyWounded=false;game15Log('injury','Personagem morreu','A janela de estabilização terminou.')}game15Save();game15RenderAll()}
function game15Stabilize(){if(!game15.injury.mortallyWounded||game15.injury.dead)return;const c=game15EnsureChar(),round=Number(window.appState?.combatRound||1),elapsed=Math.max(0,round-game15.injury.downRound),heal=game15SkillLevel(game15FindSkill(['curar','heal'])),skill=heal===null?-1:heal,attr=Math.max(game15Mod(c.attributes.dex),game15Mod(c.attributes.int)),dc=8+elapsed,d1=game15Die(6),d2=game15Die(6),total=d1+d2+skill+attr,ok=total>=dc;const r={kind:'stabilize',label:'Estabilização',dice:[d1,d2],skillBonus:skill,attrMod:attr,total,dc,success:ok,stamp:Date.now()};game15PushHistory(r);if(ok){game15.injury.mortallyWounded=false;game15.injury.stabilized=true;game15.injury.frail=true;c.hp=1;game15Log('injury','Estabilização bem-sucedida',`Após recuperação, retorna com 1 PV e condição Frágil.`)}else game15Log('injury','Estabilização falhou',`${total} contra dificuldade ${dc}.`);game15Save();game15RenderAll();game15NarrateResolution(r)}
function game15ClearFrail(){game15.injury.frail=false;game15.injury.stabilized=false;game15Save();game15Log('healing','Condição Frágil removida','Recuperação registrada pelo Mestre.');game15RenderAll()}
function game15NarrateResolution(r){try{if(typeof g11Ready==='function'&&g11Ready()&&typeof g11Generate==='function'){const old=window.game15LastNarrativeContext;window.game15LastNarrativeContext=r;setTimeout(async()=>{try{const text=await g11Generate('scene');if(window.game9&&text){game9.narration=text;if(typeof game9Save==='function')game9Save();if(typeof game9RenderAll==='function')game9RenderAll()}}catch(e){}finally{window.game15LastNarrativeContext=old}},0)}}catch(e){}}
function game15Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game15Resolution')){const a=document.getElementById('game14Home')||document.getElementById('game10Console')||document.getElementById('game9Play');a?.insertAdjacentHTML('afterend','<div id="game15Resolution" class="game15-runtime"></div>')}const ch=document.getElementById('personagem');if(ch&&!document.getElementById('game15Character')){const a=document.getElementById('game14Character')||document.getElementById('game13Party')||document.getElementById('game12Character');a?.insertAdjacentHTML('afterend','<div id="game15Character" class="game15-runtime"></div>')}const co=document.getElementById('confronto');if(co&&!document.getElementById('game15Combat')){const a=document.getElementById('game14Combat')||document.getElementById('game12Combat')||document.getElementById('gameCombatRuntime');a?.insertAdjacentHTML('afterend','<div id="game15Combat" class="game15-runtime"></div>')}const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game15Master')){const a=document.getElementById('game14Master')||document.getElementById('game12Master');a?.insertAdjacentHTML('afterend','<div id="game15Master" class="game15-runtime"></div>')}}
function game15RenderHome(){const el=document.getElementById('game15Resolution');if(!el)return;const p=game15.pending,r=game15.lastRoll;el.innerHTML=`<div class="section-cap">Resolução do Mestre</div><div class="game15-card orn-card"><span>Motor de regras WWN</span><b>${p?'Teste solicitado':'Aguardando sua ação'}</b><small>O sistema usa 2d6 para perícias, d20 para salvamentos e registra o resultado antes da narrativa Gemini.</small>${p?`<div class="game15-pending"><b>${game15Esc(p.label)}</b><small>${game15Esc(p.skill)} + ${String(p.attr).toUpperCase()} • dificuldade ${p.diff}${p.action?` • “${game15Esc(p.action)}”`:''}</small><div class="game15-actions"><button class="primary" onclick="game15RollPending()">Rolar teste</button><button onclick="game15.pending=null;game15Save();game15RenderAll()">Dispensar</button></div></div>`:''}${r?`<div class="game15-result ${r.success===true?'success':r.success===false?'fail':''}"><b>${game15Esc(r.label||r.kind)}</b><small>${game15DescribeRoll(r)}</small></div>`:''}</div>`}
function game15DescribeRoll(r){if(!r)return'';if(r.kind==='skill')return`${r.dice.join('+')} + perícia ${r.skillBonus} + atributo ${r.attrMod}${r.sit?` + ajuste ${r.sit}`:''} = ${r.total} contra ${r.dc} • ${r.success?'sucesso':'falha'}`;if(r.kind==='save')return`d20 ${r.die}${r.bonus?` + ${r.bonus}`:''} = ${r.total} contra ${r.target}+ • ${r.success?'sucesso':'falha'}`;if(r.kind==='reaction')return`${r.dice.join('+')} + Carisma ${r.cha} = ${r.total} • ${r.band}`;if(r.kind==='initiative')return`Jogadores ${r.pc} vs oposição ${r.npc} • ${r.winner} primeiro`;if(r.kind==='stabilize')return`${r.dice.join('+')} + perícia ${r.skillBonus} + atributo ${r.attrMod} = ${r.total} contra ${r.dc} • ${r.success?'estabilizado':'falha'}`;return JSON.stringify(r)}
function game15RenderCharacter(){const el=document.getElementById('game15Character');if(!el)return;const c=game15EnsureChar(),a=c.attributes,s=game15SaveTargets(),p=c.combatProfile;el.innerHTML=`<div class="section-cap">Atributos & salvamentos</div><div class="game15-card orn-card"><div class="game15-attrs">${[['str','FOR'],['dex','DES'],['con','CON'],['int','INT'],['wis','SAB'],['cha','CAR']].map(([k,l])=>`<label class="game15-attr"><small>${l}</small><input id="g15_${k}" type="number" min="3" max="18" value="${a[k]}"><b>${game15Mod(a[k])>=0?'+':''}${game15Mod(a[k])}</b></label>`).join('')}</div><div class="game15-saves"><button class="game15-save" onclick="game15RollSave('physical')"><b>${s.physical}+</b><small>Físico</small></button><button class="game15-save" onclick="game15RollSave('evasion')"><b>${s.evasion}+</b><small>Evasão</small></button><button class="game15-save" onclick="game15RollSave('mental')"><b>${s.mental}+</b><small>Mental</small></button><button class="game15-save" onclick="game15RollSave('luck')"><b>${s.luck}+</b><small>Sorte</small></button></div><div class="game15-combatcfg"><label class="game15-field"><span>Bônus base de ataque</span><input id="g15_bab" type="number" value="${p.baseAttack}"></label><label class="game15-field"><span>Perícia de combate</span><input id="g15_cskill" type="number" min="-2" max="4" value="${p.skill}"></label><label class="game15-field"><span>Atributo da arma</span><select id="g15_cattr"><option value="str" ${p.attr==='str'?'selected':''}>FOR</option><option value="dex" ${p.attr==='dex'?'selected':''}>DES</option></select></label><label class="game15-field"><span>Arma</span><input id="g15_weapon" value="${game15Esc(p.weapon)}"></label><label class="game15-field"><span>Dano</span><input id="g15_damage" value="${game15Esc(p.damage)}" placeholder="1d8"></label><label class="game15-field"><span>Shock</span><input id="g15_shock" type="number" min="0" value="${p.shock}"></label><label class="game15-field"><span>CA alvo do Shock</span><input id="g15_shockac" type="number" min="0" value="${p.shockAC}"></label><label class="game15-field"><span>CA corpo a corpo</span><input id="g15_mac" type="number" value="${p.meleeAC}"></label><label class="game15-field"><span>CA à distância</span><input id="g15_rac" type="number" value="${p.rangedAC}"></label></div><label class="game15-status ${p.enabled?'good':''}" style="margin-top:9px"><input id="g15_combatEnabled" type="checkbox" ${p.enabled?'checked':''}> usar perfil mecânico da ficha no combate</label><div class="game15-actions"><button class="primary" onclick="game15SaveAttributes()">Salvar mecânica</button></div></div>`}
function game15RenderCombat(){const el=document.getElementById('game15Combat');if(!el)return;const c=game15EnsureChar(),inj=game15.injury,round=Number(window.appState?.combatRound||1),init=game15.initiative;el.innerHTML=`<div class="section-cap">Regras do encontro</div><div class="game15-card orn-card"><div class="game15-grid"><div><span class="game15-label">Iniciativa</span><b>${init?`${init.pc} × ${init.npc}`:'não rolada'}</b><small>${init?`${init.winner} agem primeiro`:'1d8 + melhor DES do lado dos PJs'}</small></div><div><span class="game15-label">Estado do herói</span><b>${inj.dead?'morto':inj.mortallyWounded?'ferimento mortal':inj.frail?'frágil':'capaz'}</b><small>Rodada ${round}</small></div></div><div class="game15-actions"><button class="primary" onclick="game15Initiative()">Rolar iniciativa</button><button onclick="game15FirstAid()">Primeiros socorros</button></div>${inj.mortallyWounded?`<div class="game15-injury"><b>Ferimento mortal</b><small>Queda na rodada ${inj.downRound}. Se não for estabilizado, morte ao fim da rodada ${inj.deathRound}.</small><div class="game15-actions"><button class="primary" onclick="game15Stabilize()">Tentar estabilizar</button></div></div>`:''}${inj.frail&&!inj.dead?`<div class="game15-pending"><b>Condição Frágil</b><small>A cura natural não remove esta condição. Remova apenas quando a recuperação adequada tiver sido resolvida.</small><div class="game15-actions"><button onclick="game15ClearFrail()">Registrar remoção da condição</button></div></div>`:''}</div>`}
function game15RenderMaster(){const el=document.getElementById('game15Master');if(!el)return;const r=game15.lastReaction;el.innerHTML=`<div class="section-cap">Ferramentas mecânicas do Mestre</div><div class="game15-card orn-card"><div class="game15-mastertools"><button onclick="game15Reaction()"><b>Reação 2d6</b><small>Inclui modificador de Carisma do porta-voz</small></button><button onclick="game15Initiative()"><b>Iniciativa por lados</b><small>1d8 + DES dos jogadores</small></button><button onclick="game15Rest(false)"><b>Descanso adequado</b><small>Cura natural e recuperação de Strain</small></button><button onclick="game15Rest(true)"><b>Registrar privação</b><small>Sem recuperação noturna</small></button></div>${r?`<div class="game15-result"><b>Última reação: ${r.total}</b><small>${game15Esc(r.band)}</small></div>`:''}<div class="game15-history">${game15.history.slice(0,6).map(x=>`<div class="game15-history-item"><b>${game15Esc(x.label||x.kind)}</b><small>${game15Esc(game15DescribeRoll(x))}</small></div>`).join('')}</div></div>`}
function game15RenderAll(){game15EnsureChar();game15Inject();game15RenderHome();game15RenderCharacter();game15RenderCombat();game15RenderMaster();game15Save()}
function game15HookGemini(){if(window.__game15GeminiHooked||typeof g11Ctx!=='function')return;window.__game15GeminiHooked=true;const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action);c.mechanics={pending:game15.pending,lastRoll:game15.lastRoll,initiative:game15.initiative,reaction:game15.lastReaction,injury:game15.injury,saves:game15SaveTargets()};return c}}
function game15Hook(){if(window.__game15Hooked)return;window.__game15Hooked=true;try{if(typeof showView==='function'){const old=showView;showView=function(v){old(v);requestAnimationFrame(game15RenderAll)}}}catch(e){}try{if(typeof game10Submit==='function'){const old10=game10Submit;game10Submit=function(){const input=document.getElementById('game10Action'),action=input?.value.trim()||'',intent=typeof game10Intent==='function'?game10Intent(action):'';const out=old10.apply(this,arguments);if(action)game15RequestCheck(intent,action);return out}}}catch(e){}try{if(typeof gameNextRound==='function'){const oldRound=gameNextRound;gameNextRound=function(){const r=oldRound.apply(this,arguments);game15SyncInjury();return r}}}catch(e){}try{if(typeof gameCombatAttack==='function'){const oldAtk=gameCombatAttack;gameCombatAttack=function(){if(game15ConfiguredAttack())return;return oldAtk.apply(this,arguments)}}}catch(e){}try{if(typeof gameCombatDamage==='function'){const oldDmg=gameCombatDamage;gameCombatDamage=function(){if(game15ConfiguredDamage())return;return oldDmg.apply(this,arguments)}}}catch(e){}setInterval(game15HookGemini,800)}
function game15Init(){game15EnsureChar();game15Hook();game15HookGemini();game15SyncInjury();game15RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game15Init);else game15Init();
