'use strict';
/* GAME_RUNTIME_V29 — consequências, agenda do mundo, difusão de rumores e assentamentos. Sem UI. */
const GAME29_STORAGE='wwn_game_runtime_v29';
const game29Default={tick:0,settlements:{},consequences:[],rumors:[],npcSchedules:{},factionProjects:{},lastPulse:0,metrics:{pulses:0,consequences:0,rumors:0,moves:0}};
let game29=Object.assign({},game29Default,JSON.parse(localStorage.getItem(GAME29_STORAGE)||'null')||{});
function game29Save(){try{localStorage.setItem(GAME29_STORAGE,JSON.stringify(game29))}catch(e){}}
function game29Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game29Abs(){try{return typeof game28AbsTime==='function'?game28AbsTime():0}catch(e){return 0}}
function game29Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game29Emit(t,p){try{if(window.WWN_ENGINE?.emit)WWN_ENGINE.emit(t,p)}catch(e){}}
function game29KnownSettlements(){const rows=[];try{for(const t of world||[]){if(!t?.poi||!knownPOIs?.has(key(t.q,t.r)))continue;const p=POIS?.[t.poi];if(p?.type==='habitado')rows.push({id:key(t.q,t.r),name:p.name,q:t.q,r:t.r,poi:t.poi})}}catch(e){}return rows}
function game29SeedSettlements(){for(const s of game29KnownSettlements()){if(!game29.settlements[s.id])game29.settlements[s.id]={id:s.id,name:s.name,q:s.q,r:s.r,safety:3,supply:3,prosperity:3,unrest:1,attention:0,lastTick:game29.tick,history:[]};else Object.assign(game29.settlements[s.id],{name:s.name,q:s.q,r:s.r})}game29Save()}
function game29ScheduleConsequence({kind='world',title='Consequência',detail='',delayHours=24,visibility='master',payload={}}={}){const c={id:`c${Date.now()}_${Math.random().toString(36).slice(2,6)}`,kind,title,detail,due:game29Abs()+Math.max(0,Number(delayHours||0))*60,visibility,status:'pending',payload:game29Clone(payload),created:Date.now()};game29.consequences.push(c);game29.consequences.sort((a,b)=>a.due-b.due);game29Save();return c}
function game29ConsequenceEffect(c){if(c.kind==='settlement'){const s=game29.settlements[c.payload?.settlementId];if(s){for(const k of ['safety','supply','prosperity','unrest','attention'])if(Number.isFinite(Number(c.payload?.delta?.[k])))s[k]=Math.max(0,Math.min(6,Number(s[k]||0)+Number(c.payload.delta[k])));s.history.unshift({title:c.title,detail:c.detail,stamp:Date.now()});s.history=s.history.slice(0,24)}}if(c.kind==='faction'){const f=(window.gameState?.factions||[]).find(x=>x.name===c.payload?.faction);if(f&&Number.isFinite(Number(c.payload?.clockDelta)))f.clock=Math.max(0,Math.min(Number(f.max||6),Number(f.clock||0)+Number(c.payload.clockDelta)))}if(c.kind==='npc'){const n=(window.gameState?.npcs||[]).find(x=>x.name===c.payload?.npc);if(n&&c.payload?.location)n.location=c.payload.location}try{if(typeof gameSave==='function')gameSave()}catch(e){}c.status='resolved';c.resolvedAt=Date.now();game29.metrics.consequences++;game29Log('world',c.title,c.detail);game29Emit('world.consequence',{id:c.id,kind:c.kind,title:c.title,detail:c.detail,visibility:c.visibility,payload:c.payload})}
function game29ResolveDue(){const now=game29Abs();for(const c of game29.consequences)if(c.status==='pending'&&c.due<=now)game29ConsequenceEffect(c);game29.consequences=game29.consequences.slice(-160);game29Save()}
function game29AddRumor(text,source='mundo',visibility='player',truth='unknown'){if(!text)return null;const r={id:`r${Date.now()}_${Math.random().toString(36).slice(2,6)}`,text:String(text),source,visibility,truth,age:0,reaches:[],stamp:Date.now()};game29.rumors.unshift(r);game29.rumors=game29.rumors.slice(0,100);game29.metrics.rumors++;game29Save();game29Emit('world.rumor',r);return r}
function game29DiffuseRumors(){const places=Object.values(game29.settlements);for(const r of game29.rumors){r.age++;if(!places.length)continue;const idx=(r.age+r.source.length)%places.length;const place=places[idx];if(!r.reaches.includes(place.name))r.reaches.push(place.name);r.reaches=r.reaches.slice(-12)}game29Save()}
function game29NpcRows(){try{return Array.isArray(gameState?.npcs)?gameState.npcs:[]}catch(e){return[]}}
function game29SeedNpcSchedules(){const places=Object.values(game29.settlements).map(s=>s.name);for(const n of game29NpcRows()){if(!n?.name)continue;if(!game29.npcSchedules[n.name])game29.npcSchedules[n.name]={name:n.name,goal:n.intent||'agir conforme seus interesses',location:n.location||places[0]||'desconhecido',target:n.location||places[0]||'desconhecido',phase:'idle',eta:0,completed:0};const s=game29.npcSchedules[n.name];s.goal=n.intent||s.goal;s.location=n.location||s.location}game29Save()}
function game29ChooseNpcTarget(s){const places=Object.values(game29.settlements).map(x=>x.name).filter(x=>x!==s.location);if(!places.length)return s.location;return places[(game29.tick+s.name.length+s.completed)%places.length]}
function game29AdvanceNpcs(){game29SeedNpcSchedules();for(const n of game29NpcRows()){const s=game29.npcSchedules[n.name];if(!s)continue;if(s.phase==='idle'){s.target=game29ChooseNpcTarget(s);s.eta=4+((s.name.length+game29.tick)%12);s.phase=s.target!==s.location?'travel':'idle'}else if(s.phase==='travel'){s.eta=Math.max(0,s.eta-4);if(s.eta<=0){s.location=s.target;n.location=s.location;s.phase='idle';s.completed++;game29.metrics.moves++;game29AddRumor(`${n.name} foi visto em ${s.location}.`,n.name,Math.random()<.55?'player':'master','true')}}}try{if(typeof gameSave==='function')gameSave()}catch(e){}game29Save()}
function game29SeedFactionProjects(){for(const f of window.gameState?.factions||[]){if(!f?.name)continue;if(!game29.factionProjects[f.name])game29.factionProjects[f.name]={name:f.name,goal:f.goal||'',pressure:0,lastClock:Number(f.clock||0),milestones:[]};const p=game29.factionProjects[f.name];p.goal=f.goal||p.goal;p.lastClock=Number(f.clock||p.lastClock||0)}game29Save()}
function game29AdvanceFactions(){game29SeedFactionProjects();for(const f of window.gameState?.factions||[]){const p=game29.factionProjects[f.name];if(!p)continue;p.pressure=Math.min(6,Number(p.pressure||0)+1);if(p.pressure>=3){p.pressure=0;const before=Number(f.clock||0);if(before<Number(f.max||6))f.clock=before+1;if(Number(f.clock||0)!==before){p.milestones.unshift({clock:f.clock,stamp:Date.now()});p.milestones=p.milestones.slice(0,12);game29Log('faction',`${f.name} avançou seu projeto`,`${f.goal||'Projeto'} • ${f.clock}/${f.max}`);if(Number(f.clock)>=Number(f.max||6))game29ScheduleConsequence({kind:'faction',title:`Projeto concluído: ${f.name}`,detail:f.goal||'Projeto concluído',delayHours:0,visibility:'master',payload:{faction:f.name}})}}}try{if(typeof gameSave==='function')gameSave()}catch(e){}game29Save()}
function game29SettlementPressure(){game29SeedSettlements();for(const s of Object.values(game29.settlements)){const hostile=(window.gameState?.factions||[]).filter(f=>String(f.stance).includes('hostil')).length;s.attention=Math.max(0,Math.min(6,Number(s.attention||0)+(hostile?1:0)));if(s.attention>=5){s.attention=2;s.unrest=Math.min(6,s.unrest+1);game29ScheduleConsequence({kind:'settlement',title:`Tensão cresce em ${s.name}`,detail:'A pressão regional começa a afetar a rotina local.',delayHours:8,visibility:'master',payload:{settlementId:s.id,delta:{safety:-1,unrest:1}}})}}game29Save()}
function game29Pulse(reason='pulso de mundo'){if(!game29.lastPulse)game29.lastPulse=game29Abs();game29.tick++;game29.metrics.pulses++;game29SeedSettlements();game29AdvanceNpcs();game29AdvanceFactions();game29SettlementPressure();game29DiffuseRumors();game29ResolveDue();game29.lastPulse=game29Abs();game29Save();game29Emit('world.pulse',{tick:game29.tick,reason});return game29.tick}
function game29CatchUp(){const now=game29Abs(),elapsed=Math.max(0,now-Number(game29.lastPulse||now)),pulses=Math.min(8,Math.floor(elapsed/(6*60)));for(let i=0;i<pulses;i++)game29Pulse('catch-up temporal');game29ResolveDue()}
function game29PlayerNews(limit=8){return game29.rumors.filter(r=>r.visibility==='player').slice(0,limit)}
function game29MasterSecrets(limit=12){return{rumors:game29.rumors.filter(r=>r.visibility!=='player').slice(0,limit),consequences:game29.consequences.filter(c=>c.status==='pending').slice(0,limit)}}
function game29GeminiContext(){return{livingWorld:{settlements:Object.values(game29.settlements).map(s=>({name:s.name,safety:s.safety,supply:s.supply,prosperity:s.prosperity,unrest:s.unrest})).slice(0,12),knownRumors:game29PlayerNews(6).map(r=>({text:r.text,source:r.source,reaches:r.reaches})),instruction:'Use apenas knownRumors; não revele consequências master nem rumores ocultos.'}}}
function game29Hook(){if(window.__game29Hook)return;window.__game29Hook=true;try{if(window.WWN_ENGINE?.on)WWN_ENGINE.on('transaction.committed',evt=>{const k=evt.payload?.kind||'';if(/time\.advance|player\.action|combat|skill|saving/.test(k)){const now=game29Abs();if(now-Number(game29.lastPulse||0)>=360)game29Pulse(`ação: ${k}`);else game29ResolveDue()}})}catch(e){}try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(...a){return Object.assign({},old.apply(this,a),game29GeminiContext())}}}catch(e){}try{if(typeof game16Pulse==='function'&&!game16Pulse.__g29){const old=game16Pulse;const wrapped=function(...a){const r=old.apply(this,a);game29Pulse('sincronizado ao mundo vivo v16');return r};wrapped.__g29=true;window.game16Pulse=wrapped}}catch(e){}}
function game29Api(){window.WWN_WORLD=Object.assign(window.WWN_WORLD||{},{version:29,pulse:game29Pulse,catchUp:game29CatchUp,schedule:game29ScheduleConsequence,addRumor:game29AddRumor,playerNews:game29PlayerNews,masterSecrets:game29MasterSecrets,getState:()=>game29})}
function game29Init(){game29SeedSettlements();game29SeedNpcSchedules();game29SeedFactionProjects();game29CatchUp();game29Hook();game29Api();game29Emit('world.ready',{version:29})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game29Init);else game29Init();
