'use strict';
/* GAME_RUNTIME_V19 — imagem principal da cena: sistema gera prompt, usuário gera no Gemini e devolve a imagem ao VTT. */
const GAME19_STORAGE='wwn_game_runtime_v19';
const game19Default={visualNotes:'fantasia sombria de baixa magia, pintura digital cinematográfica, iluminação natural dramática, textura realista, sem texto, sem interface, sem molduras',prompt:'',promptStamp:0,currentImageId:'',history:[],lastError:''};
function game19Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game19Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game19=game19Merge(game19Default,JSON.parse(localStorage.getItem(GAME19_STORAGE)||'null'));
function game19Save(){localStorage.setItem(GAME19_STORAGE,JSON.stringify(game19))}
function game19Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game19Toast(s){try{if(typeof toast==='function')toast(s)}catch(e){}}
function game19Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game19SceneId(){const scene=window.game9?.scene||1;let day='1',hour='0';try{day=clock.day;hour=clock.hour}catch(e){}return`scene_${scene}_${day}_${hour}`}
function game19Ctx(){let t=null;try{t=currentTile()}catch(e){}let poi=null;try{if(t?.poi&&knownPOIs.has(key(t.q,t.r)))poi=POIS[t.poi]}catch(e){}const area=(()=>{try{return typeof game17Area==='function'?game17Area():null}catch(e){return null}})();const char=window.gameState?.character||{};const party=(()=>{try{return Array.isArray(game13?.party)?game13.party:[]}catch(e){return[]}})();return{scene:window.game9?.scene||1,time:(()=>{try{return clockLabel()}catch(e){return'Sessão ativa'}})(),weather:(()=>{try{return WEATHERS[weather]?.name||weather}catch(e){return''}})(),terrain:(()=>{try{return t&&BASES[t.base]?BASES[t.base].name:''}catch(e){return''}})(),feature:(()=>{try{return t?.feature&&FEATURES[t.feature]?FEATURES[t.feature].name:''}catch(e){return''}})(),poi:poi?.name||'',poiType:poi?.type||'',area:area?.name||'',character:char.name||'personagem do jogador',party,narration:window.game9?.narration||'',objective:(()=>{try{const q=typeof game14ActiveQuest==='function'?game14ActiveQuest():null;return q?.title||window.gameState?.campaign?.objective||''}catch(e){return''}})()}}
function game19Prompt(){const c=game19Ctx();const parts=[`Crie uma ilustração horizontal 16:10 para a cena atual de um RPG de fantasia sombria.`];parts.push(`Direção visual: ${game19.visualNotes}.`);if(c.time)parts.push(`Horário: ${c.time}.`);if(c.weather)parts.push(`Clima: ${c.weather}.`);if(c.terrain)parts.push(`Terreno: ${c.terrain}.`);if(c.feature)parts.push(`Relevo: ${c.feature}.`);if(c.poi)parts.push(`Local: ${c.poi}${c.area?`, área atual: ${c.area}`:''}.`);if(c.character)parts.push(`Personagem principal: ${c.character}.`);if(c.party.length)parts.push(`Companhia presente: ${c.party.join(', ')}.`);if(c.objective)parts.push(`Contexto dramático: ${c.objective}.`);if(c.narration)parts.push(`Cena narrada pelo Mestre: ${c.narration.slice(0,1200)}`);parts.push('Mostre apenas elementos perceptíveis e já revelados. Não invente mapa, HUD, ícones, legendas, letras ou texto visível. Não revele segredos, locais ocultos ou criaturas que a narrativa não mostrou. Preserve um enquadramento cinematográfico legível em tela de celular.');return parts.join('\n')}
function game19EnsurePrompt(force=false){if(force||!game19.prompt){game19.prompt=game19Prompt();game19.promptStamp=Date.now();game19Save()}return game19.prompt}
function game19Db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('wwn_scene_images_v19',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('images'))db.createObjectStore('images')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function game19PutImage(id,file){const db=await game19Db();return new Promise((resolve,reject)=>{const tx=db.transaction('images','readwrite');tx.objectStore('images').put(file,id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function game19GetImage(id){if(!id)return null;const db=await game19Db();return new Promise((resolve,reject)=>{const tx=db.transaction('images','readonly'),r=tx.objectStore('images').get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function game19DeleteImage(id){if(!id)return;const db=await game19Db();return new Promise((resolve,reject)=>{const tx=db.transaction('images','readwrite');tx.objectStore('images').delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function game19Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game19Scene')){const a=document.getElementById('game9Play')||document.getElementById('game10Console')||document.getElementById('game14Home');a?.insertAdjacentHTML('beforebegin','<div id="game19Scene" class="game19-runtime"></div>')}const cfg=document.getElementById('configuracoes');if(cfg&&!document.getElementById('game19Config'))cfg.insertAdjacentHTML('beforeend','<div id="game19Config" class="game19-runtime"></div>')}
async function game19RenderScene(){const el=document.getElementById('game19Scene');if(!el)return;const prompt=game19EnsurePrompt(false),ctx=game19Ctx();let url='';try{const blob=await game19GetImage(game19.currentImageId);if(blob)url=URL.createObjectURL(blob)}catch(e){game19.lastError=String(e?.message||e)}el.innerHTML=`<div class="section-cap">Cena visual</div><div class="game19-card orn-card"><div class="game19-head"><div><span>Imagem principal da cena ${ctx.scene}</span><h3>${game19Esc(ctx.poi||ctx.area||ctx.terrain||'Cena atual')}</h3></div><span class="game19-chip ${url?'ok':''}">${url?'imagem recebida':'aguardando imagem'}</span></div><div class="game19-stage">${url?`<div class="game19-image" style="background-image:url('${url}')"></div>`:`<div class="game19-empty"><div><b>Gere a imagem no Gemini</b><small>O VTT prepara o prompt; depois devolva a imagem aqui.</small></div></div>`}<div class="game19-vignette"></div>${ctx.narration?`<div class="game19-caption">${game19Esc(ctx.narration.slice(0,240))}${ctx.narration.length>240?'…':''}</div>`:''}</div><div class="game19-actions"><button class="primary" onclick="game19CopyPrompt()">Copiar prompt</button><button onclick="game19RefreshPrompt()">Atualizar prompt</button><button onclick="document.getElementById('game19ImageFile').click()">Receber imagem</button>${url?'<button class="danger" onclick="game19RemoveImage()">Remover imagem</button>':''}</div><input id="game19ImageFile" class="game19-file" type="file" accept="image/*" onchange="game19ImportImage(this.files[0])"><div class="game19-prompt">${game19Esc(prompt)}</div><div class="game19-status ${game19.lastError?'bad':'good'}">${game19.lastError?game19Esc(game19.lastError):'Fluxo: Mestre/Gemini narra → VTT gera prompt visual → você gera a imagem no Gemini → retorna a imagem ao VTT.'}</div></div>`}
function game19RenderConfig(){const el=document.getElementById('game19Config');if(!el)return;el.innerHTML=`<div class="section-cap">Direção visual das cenas</div><div class="game19-card orn-card"><label class="game19-field wide"><span>Prompt-base visual</span><textarea id="game19VisualNotes">${game19Esc(game19.visualNotes)}</textarea></label><div class="game19-actions"><button class="primary" onclick="game19SaveVisualNotes()">Salvar direção visual</button><button onclick="game19RefreshPrompt()">Regenerar prompt da cena</button></div><div class="game19-note">A imagem não é enviada automaticamente para o Gemini. O VTT prepara um prompt fiel ao estado conhecido; você gera a imagem no Gemini e a importa de volta. As imagens ficam no armazenamento local do dispositivo, não no GitHub.</div>${game19.history.length?`<div class="game19-history">${game19.history.slice(0,8).map(x=>`<div class="game19-history-row"><div><b>${game19Esc(x.title)}</b><small>${game19Esc(x.time)} • cena ${x.scene}</small></div><span class="game19-chip ${x.hasImage?'ok':''}">${x.hasImage?'imagem':'texto'}</span></div>`).join('')}</div>`:''}</div>`}
async function game19RenderAll(){game19Inject();await game19RenderScene();game19RenderConfig();game19Save()}
async function game19CopyPrompt(){const p=game19EnsurePrompt(false);try{await navigator.clipboard.writeText(p);game19Toast('Prompt copiado. Abra o Gemini e gere a imagem.')}catch(e){const ta=document.createElement('textarea');ta.value=p;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();game19Toast('Prompt copiado.')}}
function game19RefreshPrompt(){game19.prompt=game19Prompt();game19.promptStamp=Date.now();game19.lastError='';game19Save();game19RenderAll();game19Toast('Prompt visual atualizado com o estado atual da cena.')}
function game19SaveVisualNotes(){const el=document.getElementById('game19VisualNotes');if(el)game19.visualNotes=el.value.trim()||game19Default.visualNotes;game19Save();game19RefreshPrompt()}
async function game19ImportImage(file){if(!file)return;if(!file.type.startsWith('image/')){game19Toast('Selecione uma imagem.');return}try{if(file.size>14*1024*1024){game19Toast('Imagem muito grande. Use até 14 MB.');return}const id=game19SceneId()+'_'+Date.now();await game19PutImage(id,file);if(game19.currentImageId)await game19DeleteImage(game19.currentImageId).catch(()=>{});game19.currentImageId=id;game19.lastError='';const c=game19Ctx();game19.history.unshift({id,title:c.poi||c.area||c.terrain||'Cena',time:c.time,scene:c.scene,hasImage:true,stamp:Date.now()});game19.history=game19.history.slice(0,20);game19Save();game19Log('scene','Imagem da cena recebida',`${c.poi||c.terrain||'Cena atual'} • cena ${c.scene}`);game19Toast('Imagem aplicada à cena atual.');await game19RenderAll()}catch(e){game19.lastError=e?.message||String(e);game19Save();await game19RenderAll()}}
async function game19RemoveImage(){try{await game19DeleteImage(game19.currentImageId)}catch(e){}game19.currentImageId='';game19Save();await game19RenderAll()}
function game19ArchiveScene(){const c=game19Ctx();game19.history.unshift({id:game19.currentImageId||'',title:c.poi||c.area||c.terrain||'Cena',time:c.time,scene:c.scene,hasImage:!!game19.currentImageId,stamp:Date.now()});game19.history=game19.history.slice(0,20);game19.currentImageId='';game19.prompt='';game19Save()}
function game19Hook(){if(window.__game19Hooked)return;window.__game19Hooked=true;try{if(typeof game9NewScene==='function'){const old=game9NewScene;window.game9NewScene=function(...a){game19ArchiveScene();const r=old.apply(this,a);setTimeout(()=>{game19RefreshPrompt();},120);return r}}}catch(e){}try{if(typeof g11Scene==='function'){const old=g11Scene;window.g11Scene=async function(...a){const r=await old.apply(this,a);setTimeout(()=>game19RefreshPrompt(),140);return r}}}catch(e){}try{if(typeof showView==='function'){const old=showView;window.showView=function(v){old(v);if(v==='inicio'||v==='configuracoes')requestAnimationFrame(game19RenderAll)}}}catch(e){}}
function game19Init(){game19Hook();game19EnsurePrompt(false);game19RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game19Init);else game19Init();
