'use strict';
/* GAME_RUNTIME_V14 — VTT completo: campanha, ficha, missões, cenas, encontros e editor do mundo. */
const GAME14_STORAGE='wwn_game_runtime_v14';
const game14Default={quests:[{id:'q_main',title:'Investigar as ruínas além das Colinas das Brumas',desc:'Descobrir o que existe nas ruínas e por que a região está inquieta.',status:'active',progress:0,max:4,priority:'principal'}],activeQuest:'q_main',sceneQueue:[],encounterDraft:{title:'Novo encontro',enemies:[]},alerts:[],lastWorldEdit:0};
function game14Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game14Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game14=game14Merge(game14Default,JSON.parse(localStorage.getItem(GAME14_STORAGE)||'null'));
function game14Save(){localStorage.setItem(GAME14_STORAGE,JSON.stringify(game14))}
function game14Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game14Toast(s){if(typeof toast==='function')toast(s)}
function game14Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game14Char(){return window.gameState?.character||{}}
function game14Npcs(){return window.gameState?.npcs||[]}
function game14Factions(){return window.gameState?.factions||[]}
function game14Combat(){return window.gameState?.combat||{enemies:[]}}
function game14ActiveQuest(){return game14.quests.find(q=>q.id===game14.activeQuest&&q.status!=='done')||game14.quests.find(q=>q.status==='active')||game14.quests.find(q=>q.status!=='done')||null}
function game14Now(){try{return typeof clockLabel==='function'?clockLabel():'Sessão ativa'}catch(e){return'Sessão ativa'}}
function game14Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game14Home')){const a=document.getElementById('game13Home')||document.getElementById('game12Home')||document.getElementById('game10Console');a?.insertAdjacentHTML('afterend','<div id="game14Home" class="game14-runtime"></div>')}const ch=document.getElementById('personagem');if(ch&&!document.getElementById('game14Character')){const a=document.getElementById('game13Party')||document.getElementById('game12Character')||document.getElementById('gameCharacterRuntime');a?.insertAdjacentHTML('afterend','<div id="game14Character" class="game14-runtime"></div>')}const co=document.getElementById('confronto');if(co&&!document.getElementById('game14Combat')){const a=document.getElementById('game12Combat')||document.getElementById('gameCombatRuntime');a?.insertAdjacentHTML('afterend','<div id="game14Combat" class="game14-runtime"></div>')}const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game14Master')){const a=document.getElementById('game12Master')||document.getElementById('game10Master')||document.getElementById('gameMasterRuntime');a?.insertAdjacentHTML('afterend','<div id="game14Master" class="game14-runtime"></div>')}const se=document.getElementById('sessoes');if(se&&!document.getElementById('game14Sessions')){const a=document.getElementById('game12Sessions')||document.getElementById('game9Recap')||document.getElementById('gameSessionRuntime');a?.insertAdjacentHTML('afterend','<div id="game14Sessions" class="game14-runtime"></div>')}}
function game14SyncVisibleCharacter(){const c=game14Char();const title=document.querySelector('#personagem .screen-title');if(title&&c.name)title.textContent=c.name;const sub=document.querySelector('#personagem .screen-sub');if(sub)sub.textContent=[c.ancestry||'Humano',c.classLabel||'Explorador',`Nível ${c.level||3}`].join(' • ')}
function game14RenderHome(){const el=document.getElementById('game14Home');if(!el)return;const q=game14ActiveQuest(),next=game14.sceneQueue.find(s=>s.status!=='done'),c=game14Char(),co=game14Combat(),alive=(co.enemies||[]).filter(e=>e.hp>0).length;el.innerHTML=`<div class="section-cap">Diretor da aventura</div><div class="game14-card orn-card"><div class="game14-heading"><div><span>Próximo foco</span><h3>${game14Esc(next?.title||q?.title||'Explorar o mundo')}</h3></div><span class="game14-badge ${alive?'hot':'good'}">${alive?`${alive} ameaças`:'mundo ativo'}</span></div><small>${game14Esc(next?.detail||q?.desc||'O Mestre acompanha a continuidade da campanha.')}</small><div class="game14-kpis"><div class="game14-kpi"><b>${game14.quests.filter(x=>x.status!=='done').length}</b><small>missões</small></div><div class="game14-kpi"><b>${game14.sceneQueue.filter(x=>x.status!=='done').length}</b><small>cenas</small></div><div class="game14-kpi"><b>${game14Npcs().length}</b><small>NPCs</small></div><div class="game14-kpi"><b>${game14Factions().length}</b><small>facções</small></div></div><div class="game14-actions"><button class="primary" onclick="game14PlayNextScene()">Jogar próxima cena</button><button onclick="game12Go&&game12Go('personagem')">Personagem</button><button onclick="game12Go&&game12Go('sessoes')">Missões</button><button onclick="game12Go&&game12Go('mestre')">Mundo vivo</button></div></div>${q?`<div class="game14-callout"><b>${game14Esc(q.title)}</b><small>${game14Esc(q.desc)} • progresso ${q.progress}/${q.max}</small><div class="game14-progress">${Array.from({length:q.max},(_,i)=>`<i class="${i<q.progress?'on':''}"></i>`).join('')}</div></div>`:''}`}
function game14RenderCharacter(){const el=document.getElementById('game14Character');if(!el)return;const c=game14Char(),inv=Array.isArray(c.inventory)?c.inventory:[];el.innerHTML=`<div class="section-cap">Editor do personagem</div><div class="game14-card orn-card"><div class="game14-form"><label class="game14-field wide"><span>Nome</span><input id="g14Name" value="${game14Esc(c.name||'')}"></label><label class="game14-field"><span>Nível</span><input id="g14Level" type="number" min="1" value="${Number(c.level||3)}"></label><label class="game14-field"><span>Classe / papel</span><input id="g14Class" value="${game14Esc(c.classLabel||'Explorador')}"></label><label class="game14-field"><span>PV atual</span><input id="g14Hp" type="number" min="0" value="${Number(c.hp||0)}"></label><label class="game14-field"><span>PV máximo</span><input id="g14MaxHp" type="number" min="1" value="${Number(c.maxHp||1)}"></label><label class="game14-field"><span>Esforço</span><input id="g14Effort" type="number" min="0" value="${Number(c.effort||0)}"></label><label class="game14-field"><span>Máx. Esforço</span><input id="g14MaxEffort" type="number" min="0" value="${Number(c.maxEffort||0)}"></label><label class="game14-field"><span>System Strain</span><input id="g14Strain" type="number" min="0" value="${Number(c.strain||0)}"></label><label class="game14-field"><span>Máx. Strain</span><input id="g14MaxStrain" type="number" min="1" value="${Number(c.maxStrain||1)}"></label><label class="game14-field"><span>Prata</span><input id="g14Silver" type="number" min="0" value="${Number(c.silver||0)}"></label><label class="game14-field"><span>XP</span><input id="g14Xp" type="number" min="0" value="${Number(c.xp||0)}"></label></div><div class="game14-actions"><button class="primary" onclick="game14SaveCharacter()">Salvar ficha</button></div></div><div class="game14-card orn-card" style="margin-top:8px"><span>Inventário persistente</span><div class="game14-list">${inv.map((it,i)=>`<div class="game14-row"><div><b>${game14Esc(Array.isArray(it)?it[0]:String(it))}</b><small>${game14Esc(Array.isArray(it)?it[1]:'')}</small></div><button class="game14-mini" onclick="game14RemoveItem(${i})">×</button></div>`).join('')||'<div class="game14-empty">Sem itens.</div>'}</div><div class="game14-form"><label class="game14-field"><span>Novo item</span><input id="g14Item" placeholder="Nome do item"></label><label class="game14-field"><span>Carga / nota</span><input id="g14Load" placeholder="1 carga"></label></div><div class="game14-actions"><button onclick="game14AddItem()">Adicionar item</button></div></div>`}
function game14RenderCombat(){const el=document.getElementById('game14Combat');if(!el)return;const d=game14.encounterDraft,en=d.enemies||[];el.innerHTML=`<div class="section-cap">Montar encontro</div><div class="game14-card orn-card"><label class="game14-field"><span>Título do encontro</span><input id="g14EncounterTitle" value="${game14Esc(d.title||'Novo encontro')}"></label><div class="game14-form"><label class="game14-field"><span>Inimigo</span><input id="g14EnemyName" placeholder="Nome"></label><label class="game14-field"><span>PV</span><input id="g14EnemyHp" type="number" min="1" value="8"></label><label class="game14-field"><span>CA</span><input id="g14EnemyAc" type="number" min="1" value="12"></label><label class="game14-field"><span>Bônus ataque</span><input id="g14EnemyAtk" type="number" value="2"></label><label class="game14-field"><span>Bônus dano</span><input id="g14EnemyDmg" type="number" value="0"></label></div><div class="game14-actions"><button onclick="game14AddEnemy()">Adicionar ameaça</button><button class="primary" onclick="game14StartEncounter()" ${en.length?'':'disabled'}>Iniciar encontro</button><button class="danger" onclick="game14ClearEncounter()">Limpar</button></div><div class="game14-list">${en.map((x,i)=>`<div class="game14-enemy"><div><b>${game14Esc(x.name)}</b><small>PV ${x.hp} • CA ${x.ac} • ataque ${x.attack>=0?'+':''}${x.attack}</small></div><button class="game14-mini" onclick="game14RemoveEnemy(${i})">×</button></div>`).join('')||'<div class="game14-empty">Adicione as ameaças que realmente participam do encontro.</div>'}</div><div class="game14-note">O construtor não cria estatísticas “oficiais” automaticamente: você define os valores ou usa dados já presentes na campanha.</div></div>`}
function game14RenderMaster(){const el=document.getElementById('game14Master');if(!el)return;const npcs=game14Npcs(),factions=game14Factions(),next=game14.sceneQueue.find(s=>s.status!=='done');el.innerHTML=`<div class="section-cap">Editor do mundo vivo</div><div class="game14-grid"><div class="game14-card orn-card game14-wide"><span>Fila de cenas</span>${next?`<div class="game14-scene active"><b>${game14Esc(next.title)}</b><small>${game14Esc(next.type)} • ${game14Esc(next.detail)}</small></div>`:'<div class="game14-empty">Nenhuma cena preparada.</div>'}<div class="game14-form"><label class="game14-field"><span>Título</span><input id="g14SceneTitle" placeholder="Chegada à ponte"></label><label class="game14-field"><span>Tipo</span><select id="g14SceneType"><option>exploração</option><option>social</option><option>perigo</option><option>descanso</option><option>descoberta</option></select></label><label class="game14-field wide"><span>Contexto</span><textarea id="g14SceneDetail" placeholder="O que o Mestre deve preservar nesta cena..."></textarea></label></div><div class="game14-actions"><button onclick="game14QueueScene()">Adicionar à fila</button><button class="primary" onclick="game14PlayNextScene()">Executar próxima</button></div>${game14.sceneQueue.filter(s=>s.status!=='done').slice(1,6).map(s=>`<div class="game14-scene"><b>${game14Esc(s.title)}</b><small>${game14Esc(s.type)} • ${game14Esc(s.detail)}</small></div>`).join('')}</div><div class="game14-card orn-card"><span>Adicionar NPC</span><div class="game14-form"><label class="game14-field wide"><span>Nome</span><input id="g14NpcName"></label><label class="game14-field"><span>Papel</span><input id="g14NpcRole"></label><label class="game14-field"><span>Local</span><input id="g14NpcLoc"></label><label class="game14-field wide"><span>Intenção</span><input id="g14NpcIntent"></label></div><div class="game14-actions"><button onclick="game14AddNpc()">Registrar NPC</button></div><small>${npcs.length} NPCs persistentes no mundo.</small></div><div class="game14-card orn-card"><span>Adicionar facção</span><div class="game14-form"><label class="game14-field wide"><span>Nome</span><input id="g14FactionName"></label><label class="game14-field wide"><span>Objetivo</span><input id="g14FactionGoal"></label><label class="game14-field"><span>Clock máximo</span><input id="g14FactionMax" type="number" min="2" max="12" value="6"></label><label class="game14-field"><span>Postura</span><select id="g14FactionStance"><option>neutra</option><option>cautelosa</option><option>favorável</option><option>hostil</option></select></label></div><div class="game14-actions"><button onclick="game14AddFaction()">Registrar facção</button></div><small>${factions.length} facções acompanhadas.</small></div></div>`}
function game14RenderSessions(){const el=document.getElementById('game14Sessions');if(!el)return;const qs=game14.quests;el.innerHTML=`<div class="section-cap">Missões & objetivos</div><div class="game14-card orn-card"><div class="game14-form"><label class="game14-field wide"><span>Título</span><input id="g14QuestTitle" placeholder="Novo objetivo"></label><label class="game14-field wide"><span>Descrição</span><textarea id="g14QuestDesc" placeholder="O que precisa ser alcançado"></textarea></label><label class="game14-field"><span>Etapas</span><input id="g14QuestMax" type="number" min="1" max="12" value="4"></label><label class="game14-field"><span>Prioridade</span><select id="g14QuestPriority"><option>principal</option><option>secundária</option><option>pessoal</option></select></label></div><div class="game14-actions"><button class="primary" onclick="game14AddQuest()">Criar missão</button></div><div class="game14-list">${qs.map(q=>`<div class="game14-quest ${q.status==='done'?'done':''}"><div class="game14-quest-head"><div><b>${game14Esc(q.title)}</b><span class="game14-chip ${q.id===game14.activeQuest?'active':''}">${game14Esc(q.priority||'objetivo')}</span></div><span class="game14-badge ${q.status==='done'?'good':''}">${q.status==='done'?'concluída':`${q.progress}/${q.max}`}</span></div><p>${game14Esc(q.desc||'')}</p><div class="game14-progress">${Array.from({length:q.max},(_,i)=>`<i class="${i<q.progress?'on':''}"></i>`).join('')}</div><div class="game14-actions">${q.status!=='done'?`<button onclick="game14SetActive('${q.id}')">Ativar</button><button onclick="game14QuestStep('${q.id}',1)">Avançar</button><button onclick="game14CompleteQuest('${q.id}')">Concluir</button>`:''}<button class="danger" onclick="game14DeleteQuest('${q.id}')">Excluir</button></div></div>`).join('')||'<div class="game14-empty">Nenhuma missão registrada.</div>'}</div></div>`}
function game14RenderAll(){game14Inject();game14SyncVisibleCharacter();game14RenderHome();game14RenderCharacter();game14RenderCombat();game14RenderMaster();game14RenderSessions();game14Save()}
function game14Num(id,fallback=0){const e=document.getElementById(id);const n=Number(e?.value);return Number.isFinite(n)?n:fallback}
function game14SaveCharacter(){const c=game14Char();if(!c)return;c.name=document.getElementById('g14Name')?.value.trim()||c.name;c.level=Math.max(1,game14Num('g14Level',c.level||1));c.classLabel=document.getElementById('g14Class')?.value.trim()||c.classLabel||'Aventureiro';c.maxHp=Math.max(1,game14Num('g14MaxHp',c.maxHp||1));c.hp=Math.max(0,Math.min(c.maxHp,game14Num('g14Hp',c.hp||0)));c.maxEffort=Math.max(0,game14Num('g14MaxEffort',c.maxEffort||0));c.effort=Math.max(0,Math.min(c.maxEffort,game14Num('g14Effort',c.effort||0)));c.maxStrain=Math.max(1,game14Num('g14MaxStrain',c.maxStrain||1));c.strain=Math.max(0,Math.min(c.maxStrain,game14Num('g14Strain',c.strain||0)));c.silver=Math.max(0,game14Num('g14Silver',c.silver||0));c.xp=Math.max(0,game14Num('g14Xp',c.xp||0));try{if(typeof gameSave==='function')gameSave()}catch(e){}game14Log('character','Ficha editada',`${c.name} • nível ${c.level} • ${c.hp}/${c.maxHp} PV`);game14Toast('Ficha atualizada.');game14RenderAll()}
function game14AddItem(){const c=game14Char(),name=document.getElementById('g14Item')?.value.trim(),load=document.getElementById('g14Load')?.value.trim()||'';if(!name)return;if(!Array.isArray(c.inventory))c.inventory=[];c.inventory.push([name,load]);try{gameSave&&gameSave()}catch(e){}game14Log('character','Item adicionado',name);game14RenderCharacter()}
function game14RemoveItem(i){const c=game14Char();if(!Array.isArray(c.inventory)||!c.inventory[i])return;const name=Array.isArray(c.inventory[i])?c.inventory[i][0]:String(c.inventory[i]);c.inventory.splice(i,1);try{gameSave&&gameSave()}catch(e){}game14Log('character','Item removido',name);game14RenderCharacter()}
function game14AddEnemy(){const name=document.getElementById('g14EnemyName')?.value.trim()||`Ameaça ${game14.encounterDraft.enemies.length+1}`;const hp=Math.max(1,game14Num('g14EnemyHp',8)),ac=Math.max(1,game14Num('g14EnemyAc',12)),attack=game14Num('g14EnemyAtk',2),damage=game14Num('g14EnemyDmg',0);game14.encounterDraft.title=document.getElementById('g14EncounterTitle')?.value.trim()||'Novo encontro';game14.encounterDraft.enemies.push({name,hp,maxHp:hp,ac,attack,damage});game14Save();game14RenderCombat()}
function game14RemoveEnemy(i){game14.encounterDraft.enemies.splice(i,1);game14Save();game14RenderCombat()}
function game14ClearEncounter(){game14.encounterDraft={title:'Novo encontro',enemies:[]};game14Save();game14RenderCombat()}
function game14StartEncounter(){const d=game14.encounterDraft;if(!d.enemies.length)return;const co=game14Combat();co.enemies=d.enemies.map(x=>({...x}));co.target=0;co.lastAttack=null;try{if(window.appState){appState.combatRound=1;if(typeof saveApp==='function')saveApp()}if(typeof gameSave==='function')gameSave()}catch(e){}game14Log('combat',d.title,`${d.enemies.length} ameaças entraram em cena.`);try{if(typeof appGo==='function')appGo('confronto')}catch(e){}try{if(typeof g11Scene==='function')setTimeout(()=>g11Scene(false),80)}catch(e){}game14RenderAll()}
function game14AddQuest(){const title=document.getElementById('g14QuestTitle')?.value.trim(),desc=document.getElementById('g14QuestDesc')?.value.trim()||'',max=Math.max(1,Math.min(12,game14Num('g14QuestMax',4))),priority=document.getElementById('g14QuestPriority')?.value||'secundária';if(!title)return;const q={id:`q_${Date.now()}`,title,desc,status:'active',progress:0,max,priority};game14.quests.push(q);if(!game14ActiveQuest())game14.activeQuest=q.id;game14Save();game14Log('quest','Nova missão',title);game14RenderAll()}
function game14SetActive(id){if(game14.quests.some(q=>q.id===id&&q.status!=='done'))game14.activeQuest=id;game14Save();game14RenderAll()}
function game14QuestStep(id,d){const q=game14.quests.find(x=>x.id===id);if(!q||q.status==='done')return;q.progress=Math.max(0,Math.min(q.max,q.progress+d));if(q.progress>=q.max)q.status='done';game14Save();game14Log('quest',q.status==='done'?'Missão concluída':'Missão avançou',`${q.title} • ${q.progress}/${q.max}`);game14RenderAll()}
function game14CompleteQuest(id){const q=game14.quests.find(x=>x.id===id);if(!q)return;q.progress=q.max;q.status='done';if(game14.activeQuest===id){const next=game14.quests.find(x=>x.status!=='done');game14.activeQuest=next?.id||''}game14Save();game14Log('quest','Missão concluída',q.title);try{if(typeof g11Scene==='function')setTimeout(()=>g11Scene(false),80)}catch(e){}game14RenderAll()}
function game14DeleteQuest(id){game14.quests=game14.quests.filter(x=>x.id!==id);if(game14.activeQuest===id)game14.activeQuest=game14.quests.find(x=>x.status!=='done')?.id||'';game14Save();game14RenderAll()}
function game14QueueScene(){const title=document.getElementById('g14SceneTitle')?.value.trim(),type=document.getElementById('g14SceneType')?.value||'exploração',detail=document.getElementById('g14SceneDetail')?.value.trim()||'';if(!title)return;game14.sceneQueue.push({id:`s_${Date.now()}`,title,type,detail,status:'queued',createdAt:Date.now()});game14Save();game14Log('scene','Cena preparada',title);game14RenderAll()}
function game14PlayNextScene(){const s=game14.sceneQueue.find(x=>x.status!=='done');if(s){s.status='done';game14Log('scene',`Cena: ${s.title}`,s.detail||s.type);if(window.game9){game9.scene=(game9.scene||1)+1;game9.sceneMode=s.type;game9.narration=s.detail||s.title;try{game9Save&&game9Save()}catch(e){}}game14Save();try{if(typeof appGo==='function')appGo('inicio')}catch(e){}try{if(typeof g11Scene==='function')setTimeout(()=>g11Scene(false),80)}catch(e){}game14RenderAll();return}try{if(typeof game9NewScene==='function')game9NewScene('continuação da aventura')}catch(e){}}
function game14AddNpc(){const name=document.getElementById('g14NpcName')?.value.trim(),role=document.getElementById('g14NpcRole')?.value.trim()||'Contato',location=document.getElementById('g14NpcLoc')?.value.trim()||'Local desconhecido',intent=document.getElementById('g14NpcIntent')?.value.trim()||'Observar a situação';if(!name)return;game14Npcs().push({name,role,location,status:'ativa',intent});try{gameSave&&gameSave()}catch(e){}game14.lastWorldEdit=Date.now();game14Save();game14Log('npc','NPC registrado',`${name} • ${role} • ${location}`);game14RenderAll()}
function game14AddFaction(){const name=document.getElementById('g14FactionName')?.value.trim(),goal=document.getElementById('g14FactionGoal')?.value.trim()||'Objetivo ainda indefinido',max=Math.max(2,Math.min(12,game14Num('g14FactionMax',6))),stance=document.getElementById('g14FactionStance')?.value||'neutra';if(!name)return;game14Factions().push({name,goal,clock:0,max,stance});try{gameSave&&gameSave()}catch(e){}game14.lastWorldEdit=Date.now();game14Save();game14Log('faction','Facção registrada',`${name} • ${goal}`);game14RenderAll()}
function game14HookGemini(){if(window.__game14GeminiHooked||typeof g11Ctx!=='function')return;window.__game14GeminiHooked=true;const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action),q=game14ActiveQuest(),scene=game14.sceneQueue.find(x=>x.status!=='done');c.vttCampaign={activeQuest:q?{title:q.title,desc:q.desc,progress:q.progress,max:q.max,priority:q.priority}:null,nextScene:scene?{title:scene.title,type:scene.type,detail:scene.detail}:null,questCount:game14.quests.filter(x=>x.status!=='done').length};return c}}
function game14Hook(){if(window.__game14Hooked)return;window.__game14Hooked=true;try{if(typeof showView==='function'){const old=showView;showView=function(v){old(v);requestAnimationFrame(game14RenderAll)}}}catch(e){}setInterval(game14HookGemini,900)}
function game14Init(){game14Hook();game14HookGemini();game14RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game14Init);else game14Init();