'use strict';
/* GAME_RUNTIME_V16 — continuidade longa, agentes de NPC, alertas, snapshots e integridade. */
const GAME16_STORAGE='wwn_game_runtime_v16';
const game16Default={tick:0,agents:{},news:[],slots:[null,null,null],auto:null,logCount:0,lastIntegrity:null,lastPulse:0};
function game16Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game16Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game16=game16Merge(game16Default,JSON.parse(localStorage.getItem(GAME16_STORAGE)||'null'));
function game16Save(){localStorage.setItem(GAME16_STORAGE,JSON.stringify(game16))}
function game16Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game16Toast(s){try{if(typeof toast==='function')toast(s)}catch(e){}}
function game16Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game16Npcs(){return Array.isArray(window.gameState?.npcs)?gameState.npcs:[]}
function game16Factions(){return Array.isArray(window.gameState?.factions)?gameState.factions:[]}
function game16Relations(){try{return window.game12?.relations||window.game12?.relations===0?game12.relations:(typeof game12!=='undefined'?game12.relations||{}:{})}catch(e){return{}}}
function game16Party(){try{return Array.isArray(game13?.party)?game13.party:[]}catch(e){return[]}}
function game16KnownPlaces(){const out=[];try{if(typeof world!=='undefined'&&typeof knownPOIs!=='undefined'&&typeof key==='function'){for(const t of world){if(!t?.poi||!knownPOIs.has(key(t.q,t.r)))continue;const p=window.POIS?.[t.poi];if(p?.name)out.push(p.name)}}}catch(e){}for(const n of game16Npcs())if(n.location)out.push(n.location);return [...new Set(out.filter(Boolean))].slice(0,32)}
function game16SeedAgents(){const places=game16KnownPlaces();for(const n of game16Npcs()){if(!n?.name)continue;if(!game16.agents[n.name]){const others=places.filter(x=>x!==n.location);game16.agents[n.name]={name:n.name,goal:n.intent||'Seguir seus próprios interesses',from:n.location||'local desconhecido',to:others[0]||n.location||'local desconhecido',progress:0,max:3+(Math.abs(n.name.length)%4),status:n.status||'ativa',lastTick:game16.tick,completed:0}}else{const a=game16.agents[n.name];a.goal=n.intent||a.goal;if(!a.from)a.from=n.location||'local desconhecido'}}for(const name of Object.keys(game16.agents))if(!game16Npcs().some(n=>n.name===name))delete game16.agents[name];game16Save()}
function game16VisibleAgent(name){if(game16Party().includes(name))return true;const r=game16Relations();return Number(r?.[name]||0)>0}
function game16News(title,detail,type='info',visibility='master'){const item={id:`n${Date.now()}_${Math.random().toString(36).slice(2,6)}`,title,detail,type,visibility,tick:game16.tick,stamp:Date.now()};game16.news.unshift(item);game16.news=game16.news.slice(0,80);game16Save();return item}
function game16ChooseDestination(agent){const places=game16KnownPlaces().filter(x=>x!==agent.to&&x!==agent.from);if(!places.length)return agent.to||agent.from;const seed=(game16.tick+agent.name.length+agent.completed)%places.length;return places[seed]}
function game16AdvanceAgents(){game16SeedAgents();for(const n of game16Npcs()){const a=game16.agents[n.name];if(!a)continue;const step=1+((game16.tick+n.name.length)%2);a.progress=Math.min(a.max,a.progress+step);a.lastTick=game16.tick;a.status='em movimento';if(a.progress>=a.max){a.completed++;a.progress=0;a.from=a.to||a.from;n.location=a.from;n.status='ativa';a.status='objetivo local alcançado';const vis=game16VisibleAgent(n.name)?'player':'master';game16News(`${n.name} mudou de situação`,`${n.name} chegou a ${a.from}. Intenção atual: ${a.goal}.`,'good',vis);a.to=game16ChooseDestination(a);a.max=3+((a.completed+n.name.length)%4)}}try{if(typeof gameSave==='function')gameSave()}catch(e){}game16Save()}
function game16FactionAlerts(){for(const f of game16Factions()){const clock=Number(f.clock||0),max=Math.max(1,Number(f.max||6));if(clock>=max)game16News(`Projeto concluído: ${f.name}`,f.goal||'A facção concluiu um projeto.','hot','master');else if(clock===max-1)game16News(`Projeto quase completo: ${f.name}`,`${f.goal||'Projeto'} • ${clock}/${max}.`,'hot','master')}}
function game16Pulse(reason='pulso do mundo vivo'){game16.tick++;game16.lastPulse=Date.now();game16AdvanceAgents();game16FactionAlerts();game16Integrity();game16Save();game16Log('world',`Mundo vivo • pulso ${game16.tick}`,reason);try{if(typeof gemini11GenerateScene==='function')setTimeout(()=>gemini11GenerateScene(false),80)}catch(e){}game16RenderAll()}
function game16SafeKeys(){const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||k===GAME16_STORAGE)continue;if(!/^wwn_/i.test(k))continue;if(/api.?key|gemini.*key|token|secret|credential/i.test(k))continue;keys.push(k)}return keys.sort()}
function game16Snapshot(label='snapshot'){const data={schema:16,label,stamp:Date.now(),tick:game16.tick,keys:{}};for(const k of game16SafeKeys())data.keys[k]=localStorage.getItem(k);data.meta={character:window.gameState?.character?.name||'',journal:Array.isArray(window.gameState?.journal)?gameState.journal.length:0,npcs:game16Npcs().length,factions:game16Factions().length};return data}
function game16SaveSlot(i){game16.slots[i]=game16Snapshot(`slot ${i+1}`);game16Save();game16Toast(`Backup ${i+1} salvo.`);game16RenderAll()}
function game16RestoreSnapshot(snap){if(!snap?.keys)return;for(const [k,v] of Object.entries(snap.keys)){if(!/^wwn_/i.test(k)||k===GAME16_STORAGE||/api.?key|gemini.*key|token|secret|credential/i.test(k))continue;localStorage.setItem(k,String(v))}game16Toast('Estado restaurado. Recarregando...');setTimeout(()=>location.reload(),250)}
function game16RestoreSlot(i){const s=game16.slots[i];if(!s){game16Toast('Este slot está vazio.');return}if(confirm(`Restaurar backup ${i+1}? O estado atual será substituído.`))game16RestoreSnapshot(s)}
function game16AutoSnapshot(reason='automático'){game16.auto=game16Snapshot(reason);game16Save()}
function game16RestoreAuto(){if(!game16.auto){game16Toast('Nenhum autosave disponível.');return}if(confirm('Restaurar o autosave mais recente?'))game16RestoreSnapshot(game16.auto)}
function game16Export(){const payload={format:'BRASEIRO_WWN_CAMPAIGN_BACKUP_V16',createdAt:new Date().toISOString(),snapshot:game16Snapshot('exportação'),runtime:{tick:game16.tick,agents:game16.agents,news:game16.news,slots:game16.slots.map(s=>s?{label:s.label,stamp:s.stamp,meta:s.meta}:null)}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`braseiro-wwn-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);game16Toast('Backup exportado.')}
function game16ImportFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result||''));const snap=p?.format==='BRASEIRO_WWN_CAMPAIGN_BACKUP_V16'?p.snapshot:p?.snapshot||p;if(!snap?.keys)throw new Error('formato inválido');if(confirm('Importar este backup e substituir o estado local atual?'))game16RestoreSnapshot(snap)}catch(e){alert('Não foi possível importar este backup.')}};r.readAsText(file,'utf-8')}
function game16Integrity(){const rows=[];const c=window.gameState?.character;if(!c)rows.push({level:'bad',name:'Personagem',detail:'estado ausente'});else{const hp=Number(c.hp),max=Number(c.maxHp);rows.push({level:Number.isFinite(hp)&&Number.isFinite(max)&&max>0&&hp<=max?'ok':'warn',name:'PV',detail:`${c.hp??'?'}/${c.maxHp??'?'}`});rows.push({level:Array.isArray(c.inventory)?'ok':'warn',name:'Inventário',detail:Array.isArray(c.inventory)?`${c.inventory.length} itens`:'estrutura inválida'});rows.push({level:Array.isArray(c.skills)?'ok':'warn',name:'Perícias',detail:Array.isArray(c.skills)?`${c.skills.length} registradas`:'estrutura inválida'})}rows.push({level:Array.isArray(window.gameState?.npcs)?'ok':'warn',name:'NPCs',detail:`${game16Npcs().length} persistentes`});rows.push({level:Array.isArray(window.gameState?.factions)?'ok':'warn',name:'Facções',detail:`${game16Factions().length} persistentes`});try{rows.push({level:typeof world!=='undefined'&&Array.isArray(world)?'ok':'warn',name:'Mundo',detail:typeof world!=='undefined'&&Array.isArray(world)?`${world.length} hexes`:'não carregado'})}catch(e){rows.push({level:'warn',name:'Mundo',detail:'não carregado'})}game16.lastIntegrity={stamp:Date.now(),rows};game16Save();return rows}
function game16Repair(){const c=window.gameState?.character;if(c){c.maxHp=Math.max(1,Number(c.maxHp||1));c.hp=Math.max(0,Math.min(c.maxHp,Number(c.hp||0)));c.maxEffort=Math.max(0,Number(c.maxEffort||0));c.effort=Math.max(0,Math.min(c.maxEffort,Number(c.effort||0)));c.maxStrain=Math.max(1,Number(c.maxStrain||1));c.strain=Math.max(0,Math.min(c.maxStrain,Number(c.strain||0)));if(!Array.isArray(c.inventory))c.inventory=[];if(!Array.isArray(c.skills))c.skills=[]}if(window.gameState){if(!Array.isArray(gameState.npcs))gameState.npcs=[];if(!Array.isArray(gameState.factions))gameState.factions=[];if(!Array.isArray(gameState.journal))gameState.journal=[]}try{if(typeof gameSave==='function')gameSave()}catch(e){}game16Integrity();game16AutoSnapshot('reparo de integridade');game16Log('system','Integridade reparada','Estruturas persistentes foram normalizadas sem alterar conteúdo narrativo.');game16Toast('Integridade verificada e normalizada.');game16RenderAll()}
function game16Fmt(ts){if(!ts)return'—';try{return new Date(ts).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(e){return'—'}}
function game16Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game16Home')){const a=document.getElementById('game14Home')||document.getElementById('game13Home')||document.getElementById('game12Home');a?.insertAdjacentHTML('afterend','<div id="game16Home" class="game16-runtime"></div>')}const master=document.getElementById('mestre');if(master&&!document.getElementById('game16Master')){const a=document.getElementById('game14Master')||document.getElementById('game12Master');a?.insertAdjacentHTML('afterend','<div id="game16Master" class="game16-runtime"></div>')}const ses=document.getElementById('sessoes');if(ses&&!document.getElementById('game16Sessions')){const a=document.getElementById('game14Sessions')||document.getElementById('game12Sessions');a?.insertAdjacentHTML('afterend','<div id="game16Sessions" class="game16-runtime"></div>')}const cfg=document.getElementById('configuracoes');if(cfg&&!document.getElementById('game16Config'))cfg.insertAdjacentHTML('beforeend','<div id="game16Config" class="game16-runtime"></div>')}
function game16RenderHome(){const el=document.getElementById('game16Home');if(!el)return;const pub=game16.news.filter(n=>n.visibility==='player').slice(0,3),agents=Object.values(game16.agents),active=agents.filter(a=>a.status==='em movimento').length;el.innerHTML=`<div class="section-cap">Continuidade da campanha</div><div class="game16-card orn-card"><span>Mundo vivo em segundo plano</span><h3>${game16Npcs().length} NPCs • ${game16Factions().length} facções • pulso ${game16.tick}</h3><small>NPCs mantêm objetivos e deslocamentos entre cenas. Informações ocultas ficam no painel do Mestre até se tornarem conhecidas.</small><div class="game16-kpis"><div class="game16-kpi"><b>${active}</b><small>em trânsito</small></div><div class="game16-kpi"><b>${game16.news.filter(n=>n.visibility==='master').length}</b><small>segredos</small></div><div class="game16-kpi"><b>${pub.length}</b><small>notícias</small></div><div class="game16-kpi"><b>${game16.auto?'✓':'—'}</b><small>autosave</small></div></div>${pub.length?`<div class="game16-news">${pub.map(n=>`<div class="game16-news-item ${n.type}"><b>${game16Esc(n.title)}</b><small>${game16Esc(n.detail)}</small></div>`).join('')}</div>`:''}<div class="game16-actions"><button class="primary" onclick="game16Pulse('avanço solicitado pelo jogador')">Avançar mundo</button><button onclick="game16AutoSnapshot('checkpoint rápido')">Checkpoint rápido</button></div></div>`}
function game16RenderMaster(){const el=document.getElementById('game16Master');if(!el)return;const agents=Object.values(game16.agents),news=game16.news.slice(0,10);el.innerHTML=`<div class="section-cap">Agentes do mundo vivo</div><div class="game16-card orn-card"><span>NPCs fora de cena</span><div class="game16-agents">${agents.map(a=>{const pct=Math.round((a.progress/Math.max(1,a.max))*100);return`<div class="game16-agent"><div class="game16-agent-head"><div><b>${game16Esc(a.name)}</b><small>${game16Esc(a.goal)}</small></div><span class="game16-status ${a.status==='objetivo local alcançado'?'good':''}">${game16Esc(a.status)}</span></div><div class="route">${game16Esc(a.from)} → ${game16Esc(a.to)}</div><div class="game16-progress"><i style="width:${pct}%"></i></div></div>`}).join('')||'<div class="game16-note">Nenhum agente persistente.</div>'}</div><div class="game16-actions"><button class="primary" onclick="game16Pulse('pulso manual do Mestre')">Executar pulso</button></div></div><div class="section-cap">Caixa-preta do Mestre</div><div class="game16-card orn-card"><div class="game16-news">${news.map(n=>`<div class="game16-news-item ${n.type}"><b>${game16Esc(n.title)}</b><small>${game16Esc(n.detail)} • ${n.visibility==='player'?'jogador informado':'oculto'}</small></div>`).join('')||'<div class="game16-note">Nenhum evento reservado.</div>'}</div></div>`}
function game16RenderSessions(){const el=document.getElementById('game16Sessions');if(!el)return;el.innerHTML=`<div class="section-cap">Backups da campanha</div><div class="game16-card orn-card"><span>Slots manuais</span><div class="game16-slots">${game16.slots.map((s,i)=>`<div class="game16-slot"><div><b>Backup ${i+1}</b><small>${s?`${game16Fmt(s.stamp)} • ${game16Esc(s.meta?.character||'campanha')} • ${s.meta?.journal||0} registros`:'vazio'}</small></div><div class="game16-slot-actions"><button onclick="game16SaveSlot(${i})">S</button><button onclick="game16RestoreSlot(${i})" ${s?'':'disabled'}>R</button></div></div>`).join('')}</div><div class="game16-sep"></div><span>Autosave</span><b>${game16.auto?game16Fmt(game16.auto.stamp):'Nenhum autosave'}</b><small>O autosave exclui chaves de API, tokens e credenciais.</small><div class="game16-actions"><button onclick="game16AutoSnapshot('autosave manual')">Atualizar autosave</button><button onclick="game16RestoreAuto()" ${game16.auto?'':'disabled'}>Restaurar</button><button class="primary" onclick="game16Export()">Exportar JSON</button><button onclick="document.getElementById('game16Import').click()">Importar</button></div><input id="game16Import" class="game16-import" type="file" accept="application/json,.json" onchange="game16ImportFile(this.files[0])"></div>`}
function game16RenderConfig(){const el=document.getElementById('game16Config');if(!el)return;const rows=game16Integrity();el.innerHTML=`<div class="section-cap">Saúde do save</div><div class="game16-card orn-card"><span>Integridade da campanha</span><div class="game16-health">${rows.map(r=>`<div class="game16-health-row ${r.level}"><b>${game16Esc(r.name)}</b><span>${game16Esc(r.detail)}</span></div>`).join('')}</div><div class="game16-actions"><button class="primary" onclick="game16Repair()">Verificar e reparar</button><button onclick="game16Export()">Backup completo</button></div><div class="game16-note">A verificação só normaliza estruturas quebradas e limites numéricos. Não reescreve missões, NPCs, regras ou narrativa.</div></div>`}
function game16RenderAll(){game16Inject();game16SeedAgents();game16RenderHome();game16RenderMaster();game16RenderSessions();game16RenderConfig();game16Save()}
function game16HookWorld(){if(window.__game16WorldHooked||typeof gameWorldTurn!=='function')return;window.__game16WorldHooked=true;const old=gameWorldTurn;window.gameWorldTurn=function(reason){const out=old(reason);game16.tick++;game16.lastPulse=Date.now();game16AdvanceAgents();game16FactionAlerts();game16Integrity();game16Save();requestAnimationFrame(game16RenderAll);return out}}
function game16HookLogs(){if(window.__game16LogHooked||typeof gameLog!=='function')return;window.__game16LogHooked=true;const old=gameLog;window.gameLog=function(...args){const out=old(...args);game16.logCount++;if(game16.logCount%10===0)game16AutoSnapshot('autosave por atividade');else game16Save();return out}}
function game16HookGemini(){if(window.__game16GeminiHooked||typeof g11Ctx!=='function')return;window.__game16GeminiHooked=true;const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action);c.continuity={worldTick:game16.tick,publicNews:game16.news.filter(n=>n.visibility==='player').slice(0,4).map(n=>({title:n.title,detail:n.detail})),partyAgents:Object.values(game16.agents).filter(a=>game16VisibleAgent(a.name)).slice(0,5).map(a=>({name:a.name,goal:a.goal,from:a.from,to:a.to,progress:a.progress,max:a.max}))};return c}}
function game16HookViews(){if(window.__game16ViewHooked||typeof showView!=='function')return;window.__game16ViewHooked=true;const old=showView;window.showView=function(v){old(v);requestAnimationFrame(game16RenderAll)}}
function game16Init(){game16SeedAgents();game16Integrity();game16HookWorld();game16HookLogs();game16HookGemini();game16HookViews();if(!game16.auto)game16AutoSnapshot('baseline v16');game16RenderAll();setInterval(()=>{game16HookWorld();game16HookLogs();game16HookGemini()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game16Init);else game16Init();