'use strict';
/* GAME_RUNTIME_V28 — kernel de autoridade: transações, event bus, snapshots e resolução encadeada. Sem UI. */
const GAME28_STORAGE='wwn_game_runtime_v28';
const game28Default={seq:0,tx:[],events:[],locks:{},lastCommit:0,lastError:'',metrics:{actions:0,commits:0,aborts:0,ruleChecks:0,geminiNarrations:0}};
let game28=Object.assign({},game28Default,JSON.parse(localStorage.getItem(GAME28_STORAGE)||'null')||{});
const game28Listeners=new Map();
function game28Save(){try{localStorage.setItem(GAME28_STORAGE,JSON.stringify(game28))}catch(e){}}
function game28Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game28Now(){try{return typeof clock!=='undefined'?{day:Number(clock.day||1),hour:Number(clock.hour||0),min:Number(clock.min||0),label:typeof clockLabel==='function'?clockLabel():''}:{day:1,hour:0,min:0,label:''}}catch(e){return{day:1,hour:0,min:0,label:''}}}
function game28AbsTime(){const n=game28Now();return ((n.day-1)*24*60)+(n.hour*60)+n.min}
function game28PlayerState(){const c=window.gameState?.character||{};return{name:c.name||'',level:Number(c.level||1),hp:Number(c.hp||0),maxHp:Number(c.maxHp||0),effort:Number(c.effort||0),maxEffort:Number(c.maxEffort||0),strain:Number(c.strain||0),maxStrain:Number(c.maxStrain||0),silver:Number(c.silver||0),xp:Number(c.xp||0),inventory:Array.isArray(c.inventory)?game28Clone(c.inventory):[]}}
function game28WorldState(){let tile=null;try{tile=currentTile()}catch(e){}return{time:game28Now(),position:tile?{q:tile.q,r:tile.r,base:tile.base,feature:tile.feature||'',poi:tile.poi||'',seen:!!tile.seen,visited:!!tile.visited}:null,knownPois:typeof knownPOIs!=='undefined'?knownPOIs.size:0,worldTurns:Number(window.gameState?.campaign?.worldTurns||0),tension:Number(window.gameState?.campaign?.tension||0),quest:typeof game14ActiveQuest==='function'?game28Clone(game14ActiveQuest()):null,combat:window.gameState?.combat?game28Clone(gameState.combat):null}}
function game28Snapshot(){return{stamp:Date.now(),absTime:game28AbsTime(),player:game28PlayerState(),world:game28WorldState()}}
function game28Diff(a,b){const out=[];const cmp=(p,x,y)=>{if(JSON.stringify(x)!==JSON.stringify(y))out.push({path:p,before:x,after:y})};if(!a||!b)return out;cmp('player.hp',a.player?.hp,b.player?.hp);cmp('player.effort',a.player?.effort,b.player?.effort);cmp('player.strain',a.player?.strain,b.player?.strain);cmp('player.silver',a.player?.silver,b.player?.silver);cmp('player.xp',a.player?.xp,b.player?.xp);cmp('player.inventory',a.player?.inventory,b.player?.inventory);cmp('world.position',a.world?.position,b.world?.position);cmp('world.time',a.world?.time,b.world?.time);cmp('world.knownPois',a.world?.knownPois,b.world?.knownPois);cmp('world.worldTurns',a.world?.worldTurns,b.world?.worldTurns);cmp('world.tension',a.world?.tension,b.world?.tension);cmp('world.quest',a.world?.quest,b.world?.quest);cmp('world.combat',a.world?.combat,b.world?.combat);return out}
function game28On(type,fn){if(!game28Listeners.has(type))game28Listeners.set(type,new Set());game28Listeners.get(type).add(fn);return()=>game28Listeners.get(type)?.delete(fn)}
function game28Emit(type,payload={}){const evt={id:`e${++game28.seq}`,type,payload:game28Clone(payload),stamp:Date.now(),time:game28Now()};game28.events.unshift(evt);game28.events=game28.events.slice(0,220);game28Save();for(const key of [type,'*'])for(const fn of game28Listeners.get(key)||[]){try{fn(evt)}catch(e){console.warn('game28 listener',e)}}return evt}
function game28Lock(name,ttl=15000){const now=Date.now(),old=Number(game28.locks[name]||0);if(old>now)return false;game28.locks[name]=now+ttl;game28Save();return true}
function game28Unlock(name){delete game28.locks[name];game28Save()}
function game28Begin(kind,payload={},source='player'){const tx={id:`tx${++game28.seq}`,kind,source,payload:game28Clone(payload),status:'open',openedAt:Date.now(),before:game28Snapshot(),after:null,diff:[],result:null,ruleEvidence:[]};game28.tx.unshift(tx);game28.tx=game28.tx.slice(0,80);game28.metrics.actions++;game28Save();game28Emit('transaction.opened',{id:tx.id,kind,source});return tx}
function game28GetTx(id){return game28.tx.find(t=>t.id===id)||null}
function game28AttachRuleEvidence(txId,query){const tx=game28GetTx(txId);if(!tx||!query)return[];let refs=[];try{if(typeof game26Search==='function')refs=game26Search(query,5).map((x,i)=>({id:`R${i+1}`,source:x.row.sourceName,page:x.row.page||0,text:x.row.text.slice(0,900),score:x.score}))}catch(e){}tx.ruleEvidence=refs;game28.metrics.ruleChecks++;game28Save();return refs}
function game28Commit(txOrId,result={}){const tx=typeof txOrId==='string'?game28GetTx(txOrId):txOrId;if(!tx||tx.status!=='open')return tx;tx.after=game28Snapshot();tx.diff=game28Diff(tx.before,tx.after);tx.result=game28Clone(result);tx.status='committed';tx.committedAt=Date.now();game28.metrics.commits++;game28.lastCommit=Date.now();game28Save();game28Emit('transaction.committed',{id:tx.id,kind:tx.kind,diff:tx.diff,result:tx.result,ruleEvidence:tx.ruleEvidence});return tx}
function game28Abort(txOrId,reason='abortado'){const tx=typeof txOrId==='string'?game28GetTx(txOrId):txOrId;if(!tx||tx.status!=='open')return tx;tx.status='aborted';tx.reason=String(reason);tx.closedAt=Date.now();game28.metrics.aborts++;game28.lastError=String(reason);game28Save();game28Emit('transaction.aborted',{id:tx.id,kind:tx.kind,reason:String(reason)});return tx}
function game28OpenTransactions(){return game28.tx.filter(t=>t.status==='open')}
function game28ResolveDangling(){const now=Date.now();for(const tx of game28OpenTransactions())if(now-tx.openedAt>60000)game28Abort(tx,'transação expirada sem commit')}
function game28MechanicalSummary(tx){if(!tx)return'';const parts=[];if(tx.result?.label)parts.push(tx.result.label);if(tx.result?.success===true)parts.push('sucesso');if(tx.result?.success===false)parts.push('falha');for(const d of tx.diff||[]){const n=d.path.replace('player.','').replace('world.','');parts.push(`${n}: ${JSON.stringify(d.before)} → ${JSON.stringify(d.after)}`)}return parts.join(' • ')}
function game28NarrativeContext(tx){return{transaction:{id:tx?.id||'',kind:tx?.kind||'',source:tx?.source||'',action:tx?.payload||{},mechanicalResult:tx?.result||{},actualChanges:tx?.diff||[]},ruleEvidence:(tx?.ruleEvidence||[]).map(r=>({source:r.source,page:r.page,text:r.text})),instruction:'Narre somente consequências compatíveis com mechanicalResult e actualChanges. Não crie rolagens, PV, dano, recursos, XP ou alterações de estado que não estejam aqui.'}}
function game28HookGemini(){if(window.__game28GeminiHook)return;window.__game28GeminiHook=true;try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action),tx=game28.tx.find(t=>t.status==='committed');if(tx)c.authorityKernel=game28NarrativeContext(tx);return c}}}catch(e){}
try{if(typeof gemini11GenerateScene==='function'){const old=gemini11GenerateScene;window.gemini11GenerateScene=async function(...a){game28.metrics.geminiNarrations++;game28Save();return old.apply(this,a)}}}catch(e){}}
function game28HookActions(){if(window.__game28ActionsHook)return;window.__game28ActionsHook=true;try{if(typeof game10Submit==='function'){const old=game10Submit;window.game10Submit=function(){const input=document.getElementById('game10Action'),text=input?.value.trim()||'';const tx=text?game28Begin('player.action',{text},'player'):null;try{const r=old.apply(this,arguments);if(tx){const intent=typeof game10Intent==='function'?game10Intent(text):'livre';game28AttachRuleEvidence(tx.id,`${intent} ${text}`);setTimeout(()=>{if(tx.status==='open')game28Commit(tx,{intent,label:'Ação do jogador processada'})},40)}return r}catch(e){if(tx)game28Abort(tx,e.message||e);throw e}}}}catch(e){}
for(const [name,kind] of [['game15RollSkill','skill.check'],['game15RollSave','saving.throw'],['game15Reaction','reaction.roll'],['game15Initiative','initiative.roll'],['game15ConfiguredAttack','combat.attack'],['game15ConfiguredDamage','combat.damage']]){try{const fn=window[name];if(typeof fn!=='function'||fn.__g28)continue;const wrapped=function(...args){const tx=game28Begin(kind,{args},'engine');try{const r=fn.apply(this,args);game28AttachRuleEvidence(tx.id,`${kind} ${args.join(' ')}`);game28Commit(tx,r&&typeof r==='object'?r:{label:kind});return r}catch(e){game28Abort(tx,e.message||e);throw e}};wrapped.__g28=true;window[name]=wrapped}catch(e){}}
try{if(typeof advance==='function'&&!advance.__g28){const old=advance;const wrapped=function(hours,...rest){const tx=game28Begin('time.advance',{hours},'engine');try{const r=old.call(this,hours,...rest);game28Commit(tx,{hours:Number(hours||0),label:'Tempo avançado'});return r}catch(e){game28Abort(tx,e.message||e);throw e}};wrapped.__g28=true;window.advance=wrapped}}catch(e){}}
function game28PublicApi(){window.WWN_ENGINE=Object.assign(window.WWN_ENGINE||{},{version:28,on:game28On,emit:game28Emit,begin:game28Begin,commit:game28Commit,abort:game28Abort,snapshot:game28Snapshot,diff:game28Diff,attachRuleEvidence:game28AttachRuleEvidence,narrativeContext:game28NarrativeContext,mechanicalSummary:game28MechanicalSummary,getState:()=>game28})}
function game28Init(){game28ResolveDangling();game28HookGemini();game28HookActions();game28PublicApi();game28Emit('engine.ready',{version:28})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game28Init);else game28Init();
