'use strict';
/* GAME_RUNTIME_V34 — Atlas lógico: auditoria de vizinhança/POI, rotas e planejamento de viagem. Sem UI. */
const GAME34_STORAGE='wwn_game_runtime_v34';
const game34Default={lastAudit:null,lastRoute:null,routeHistory:[],metrics:{audits:0,routes:0,invalidPois:0,densityWarnings:0},settings:{maxPoiDensity:.28,knownOnly:false}};
let game34=Object.assign({},game34Default,JSON.parse(localStorage.getItem(GAME34_STORAGE)||'null')||{});
function game34Save(){try{localStorage.setItem(GAME34_STORAGE,JSON.stringify(game34))}catch(e){}}
function game34Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game34Emit(t,p){try{window.WWN_ENGINE?.emit?.(t,p)}catch(e){}}
function game34TileId(t){try{return key(t.q,t.r)}catch(e){return`${t.q},${t.r}`}}
function game34Neighbors(t){const out=[];if(!t)return out;try{for(const d of DIRS||[]){const n=tile(t.q+d.q,t.r+d.r);if(n)out.push(n)}}catch(e){}return out}
function game34PoiAllowed(t){if(!t?.poi)return true;const p=window.POIS?.[t.poi];if(!p)return false;if(!Array.isArray(p.allow)||!p.allow.length)return true;if(p.allow.includes(t.base))return true;if(t.feature&&p.allow.includes(t.feature))return true;return false}
function game34TransitionScore(a,b){if(!a||!b)return 0;try{if(typeof compat==='function')return compat(a.base,b.base)}catch(e){}const ga=BASES?.[a.base]?.group,gb=BASES?.[b.base]?.group;if(ga===gb)return 4;if(!ga||!gb)return 0;const bad=new Set(['desert|wetland','wetland|desert','volcanic|settled','settled|volcanic','cold|desert','desert|cold']);const k=[ga,gb].sort().join('|');return bad.has(k)?-3:1}
function game34Audit(){const issues=[],warnings=[],stats={tiles:0,seen:0,pois:0,knownPois:0,invalidPois:0,harshTransitions:0,clusters:0};let rows=[];try{rows=Array.isArray(world)?world:[]}catch(e){}stats.tiles=rows.length;for(const t of rows){if(t.seen)stats.seen++;if(t.poi){stats.pois++;if(typeof knownPOIs!=='undefined'&&knownPOIs.has(game34TileId(t)))stats.knownPois++;if(!game34PoiAllowed(t)){stats.invalidPois++;issues.push({type:'poi-terrain',tile:game34TileId(t),poi:t.poi,base:t.base,feature:t.feature||''})}}for(const n of game34Neighbors(t)){if(game34TransitionScore(t,n)<=-2){stats.harshTransitions++;warnings.push({type:'harsh-transition',from:game34TileId(t),to:game34TileId(n),a:t.base,b:n.base})}}const local=[t,...game34Neighbors(t)],pc=local.filter(x=>x.poi).length;if(local.length>=4&&pc/local.length>.5){stats.clusters++;warnings.push({type:'poi-cluster',tile:game34TileId(t),ratio:pc/local.length})}}const density=stats.tiles?stats.pois/stats.tiles:0;if(density>Number(game34.settings.maxPoiDensity||.28))warnings.push({type:'poi-density',density,limit:game34.settings.maxPoiDensity});stats.harshTransitions=Math.floor(stats.harshTransitions/2);game34.lastAudit={stamp:Date.now(),ok:issues.length===0,issues:issues.slice(0,80),warnings:warnings.slice(0,120),stats,density};game34.metrics.audits++;game34.metrics.invalidPois=stats.invalidPois;game34.metrics.densityWarnings=warnings.filter(x=>x.type==='poi-density'||x.type==='poi-cluster').length;game34Save();game34Emit('atlas.audit',game34Clone(game34.lastAudit));return game34.lastAudit}
function game34Passable(t,knownOnly=false){if(!t)return false;if(knownOnly&&!t.seen)return false;return true}
function game34StepCost(t){let c=Number(BASES?.[t?.base]?.cost||4);if(t?.feature){const g=FEATURES?.[t.feature]?.group||'';if(g==='mountain')c+=3;else if(g==='water'||g==='coast')c+=2;else if(g==='cold'||g==='volcanic')c+=2}return Math.max(1,c)}
function game34Route(from,to,{knownOnly=game34.settings.knownOnly,maxVisited=500}={}){if(!from||!to)return null;const start=game34TileId(from),goal=game34TileId(to),distMap=new Map([[start,0]]),prev=new Map(),open=[{id:start,t:from,cost:0}],visited=new Set();let loops=0;while(open.length&&loops++<maxVisited){open.sort((a,b)=>a.cost-b.cost);const cur=open.shift();if(!cur||visited.has(cur.id))continue;visited.add(cur.id);if(cur.id===goal)break;for(const n of game34Neighbors(cur.t)){if(!game34Passable(n,knownOnly))continue;const id=game34TileId(n),next=cur.cost+game34StepCost(n);if(next<(distMap.get(id)??Infinity)){distMap.set(id,next);prev.set(id,cur.id);open.push({id,t:n,cost:next})}}}if(!distMap.has(goal))return null;const ids=[];let at=goal;while(at){ids.unshift(at);if(at===start)break;at=prev.get(at)}const path=ids.map(id=>byKey?.[id]).filter(Boolean);const hours=Math.max(1,Math.round(path.slice(1).reduce((n,t)=>n+game34StepCost(t),0)));const unknown=path.filter(t=>!t.seen).length;const r={id:`rt${Date.now()}_${Math.random().toString(36).slice(2,6)}`,start,goal,path:ids,cost:distMap.get(goal),estimatedHours:hours,hexes:Math.max(0,path.length-1),unknown,knownOnly,stamp:Date.now()};game34.lastRoute=r;game34.routeHistory.unshift(r);game34.routeHistory=game34.routeHistory.slice(0,30);game34.metrics.routes++;game34Save();game34Emit('atlas.route.planned',game34Clone(r));return r}
function game34RouteCurrentTo(t){let here=null;try{here=currentTile()}catch(e){}return game34Route(here,t||null)}
function game34RouteSelected(){try{return game34RouteCurrentTo(typeof wwnSelectedTile==='function'?wwnSelectedTile():null)}catch(e){return null}}
function game34RouteContext(){const r=game34.lastRoute;if(!r)return null;return{plannedRoute:{hexes:r.hexes,estimatedHours:r.estimatedHours,unknownHexes:r.unknown,path:r.path.slice(0,24)},instruction:'A rota é uma estimativa do motor. Não invente atalhos nem deslocamento além da rota confirmada.'}}
function game34PoiCandidates(){const rows=[];try{for(const t of world||[]){if(t.poi)continue;const neighbors=game34Neighbors(t),neighborPois=neighbors.filter(n=>n.poi).length;if(neighborPois>2)continue;const compatible=Object.entries(POIS||{}).filter(([,p])=>!p.allow?.length||p.allow.includes(t.base)||(t.feature&&p.allow.includes(t.feature))).map(([id,p])=>({id,name:p.name,type:p.type}));rows.push({tile:game34TileId(t),base:t.base,feature:t.feature||'',compatible:compatible.slice(0,12)})}}catch(e){}return rows}
function game34Hook(){if(window.__game34Hook)return;window.__game34Hook=true;try{window.WWN_ENGINE?.on?.('transaction.committed',evt=>{const k=evt.payload?.kind||'';if(/time\.advance|player\.action/.test(k)&&Math.random()<.12)game34Audit()})}catch(e){}try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(...a){const c=old.apply(this,a),r=game34RouteContext();return r?Object.assign({},c,r):c}}}catch(e){}}
function game34Api(){window.WWN_ATLAS={version:34,audit:game34Audit,route:game34Route,routeCurrentTo:game34RouteCurrentTo,routeSelected:game34RouteSelected,poiCandidates:game34PoiCandidates,getState:()=>game34}}
function game34Init(){game34Audit();game34Hook();game34Api();game34Emit('atlas.logic.ready',{version:34,audit:game34.lastAudit?.stats||{}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game34Init);else game34Init();
