'use strict';
/* GAME_RUNTIME_V36 — memória longa: entidades, fatos com proveniência, digests e orçamento de contexto. Sem UI. */
const GAME36_STORAGE='wwn_game_runtime_v36';
const game36Default={entities:{},facts:[],digests:[],eventSeq:0,lastDigest:0,lastContext:null,metrics:{events:0,facts:0,entities:0,digests:0},settings:{contextChars:7600,digestEvery:18}};
let game36=Object.assign({},game36Default,JSON.parse(localStorage.getItem(GAME36_STORAGE)||'null')||{});
function game36Save(){try{localStorage.setItem(GAME36_STORAGE,JSON.stringify(game36))}catch(e){}}
function game36Clone(v){try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v??null))}}
function game36Norm(s){return String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function game36Id(type,name){return`${type}:${game36Norm(name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'unknown'}`}
function game36Emit(t,p){try{window.WWN_ENGINE?.emit?.(t,p)}catch(e){}}
function game36EnsureEntity(type,name,meta={}){if(!name)return null;const id=game36Id(type,name);if(!game36.entities[id]){game36.entities[id]={id,type,name:String(name),aliases:[],meta:{},publicFacts:[],privateFacts:[],firstSeen:Date.now(),lastSeen:Date.now()};game36.metrics.entities++}const e=game36.entities[id];e.name=String(name);e.meta=Object.assign({},e.meta||{},game36Clone(meta));e.lastSeen=Date.now();game36Save();return e}
function game36AddFact({entityType='world',entityName='campaign',text='',visibility='player',source='engine',eventId='',confidence='confirmed',tags=[]}={}){const clean=String(text||'').trim();if(!clean)return null;const e=game36EnsureEntity(entityType,entityName),bucket=visibility==='player'?'publicFacts':'privateFacts';const exists=e[bucket].find(x=>x.text===clean);if(exists){exists.lastSeen=Date.now();return exists}const f={id:`f${Date.now()}_${++game36.eventSeq}`,entityId:e.id,text:clean,visibility,source,eventId,confidence,tags:Array.isArray(tags)?tags.slice(0,12):[],stamp:Date.now(),lastSeen:Date.now()};e[bucket].unshift(f);e[bucket]=e[bucket].slice(0,40);game36.facts.unshift(f);game36.facts=game36.facts.slice(0,600);game36.metrics.facts++;game36Save();return f}
function game36SeedEntities(){try{const c=gameState?.character;if(c?.name)game36EnsureEntity('character',c.name,{level:c.level,classLabel:c.classLabel,ancestry:c.ancestry})}catch(e){}try{for(const n of gameState?.npcs||[])game36EnsureEntity('npc',n.name,{role:n.role,location:n.location,status:n.status,intent:n.intent})}catch(e){}try{for(const f of gameState?.factions||[])game36EnsureEntity('faction',f.name,{goal:f.goal,stance:f.stance,clock:f.clock,max:f.max})}catch(e){}try{for(const id of knownPOIs||[]){const t=byKey?.[id],p=t?.poi?POIS?.[t.poi]:null;if(p?.name)game36EnsureEntity('place',p.name,{tile:id,type:p.type,terrain:BASES?.[t.base]?.name||'',feature:t.feature?FEATURES?.[t.feature]?.name||'':''})}}catch(e){}try{for(const q of game14?.quests||[])game36EnsureEntity('quest',q.title,{status:q.status,progress:q.progress,max:q.max,priority:q.priority})}catch(e){}game36Save()}
function game36RecordEvent(type,payload={}){game36.metrics.events++;const id=`ev${Date.now()}_${++game36.eventSeq}`,p=game36Clone(payload);if(type==='transaction.committed'){const kind=p.kind||'';for(const d of p.diff||[]){if(d.path==='player.hp')game36AddFact({entityType:'character',entityName:gameState?.character?.name||'personagem',text:`PV mudou de ${d.before} para ${d.after}.`,source:kind,eventId:id,tags:['mechanical']});if(d.path==='world.position')game36AddFact({entityType:'world',entityName:'campanha',text:`O grupo mudou de posição no Atlas.`,source:kind,eventId:id,tags:['travel']});if(d.path==='world.knownPois'&&Number(d.after)>Number(d.before))game36AddFact({entityType:'world',entityName:'campanha',text:'Um novo local de interesse tornou-se conhecido.',source:kind,eventId:id,tags:['discovery']})}}else if(type==='world.rumor'){game36AddFact({entityType:'world',entityName:'rumores',text:p.text||'',visibility:p.visibility==='player'?'player':'master',source:p.source||'rumor',eventId:id,confidence:p.truth==='true'?'confirmed':'reported',tags:['rumor']})}else if(type==='campaign.clue'){game36AddFact({entityType:'quest',entityName:'pistas da campanha',text:p.text||'',visibility:p.visibility==='player'?'player':'master',source:'campaign-director',eventId:id,tags:['clue']})}else if(type==='campaign.secret.revealed'){game36AddFact({entityType:'world',entityName:'segredos revelados',text:p.text||'',visibility:'player',source:p.source||'director',eventId:id,tags:['revealed']})}else if(type==='party.mission.resolved'){game36AddFact({entityType:'npc',entityName:p.member||'aliado',text:`Tarefa “${p.title||''}” terminou: ${p.result||p.status||'resolvida'}.`,visibility:p.visibility==='master'?'master':'player',source:'party-engine',eventId:id,tags:['party','mission']})}else if(type==='combat.ended'){game36AddFact({entityType:'world',entityName:'combates',text:`Combate encerrado (${p.outcome||'encerrado'}): ${p.detail||''}`,source:'combat-supervisor',eventId:id,tags:['combat']})}game36Save();if(game36.metrics.events%Math.max(1,Number(game36.settings.digestEvery||18))===0)game36Digest(`eventos ${game36.metrics.events}`)}
function game36JournalRows(){try{return Array.isArray(gameState?.journal)?gameState.journal:[]}catch(e){return[]}}
function game36Digest(label='sessão'){game36SeedEntities();const journal=game36JournalRows().slice(0,24),tx=window.WWN_ENGINE?.getState?.().tx?.filter(x=>x.status==='committed').slice(0,18)||[],publicFacts=game36.facts.filter(x=>x.visibility==='player').slice(0,40);const summary=[journal.length?`Diário recente: ${journal.map(x=>`${x.title}${x.detail?` — ${x.detail}`:''}`).join(' | ')}`:'',tx.length?`Resoluções: ${tx.map(x=>`${x.kind}: ${(x.diff||[]).map(d=>d.path).join(',')||'sem mudança persistente'}`).join(' | ')}`:'',publicFacts.length?`Fatos confirmados/conhecidos: ${publicFacts.map(x=>x.text).join(' | ')}`:''].filter(Boolean).join('\n').slice(0,9000);const d={id:`dg${Date.now()}_${++game36.eventSeq}`,label,stamp:Date.now(),summary,day:(()=>{try{return clock?.day||1}catch(e){return 1}})(),worldTurns:Number(gameState?.campaign?.worldTurns||0)};game36.digests.unshift(d);game36.digests=game36.digests.slice(0,40);game36.lastDigest=Date.now();game36.metrics.digests++;game36Save();return d}
function game36EntityScore(e,query=''){let s=0;const q=game36Norm(query),terms=q.split(/\s+/).filter(x=>x.length>2);const hay=game36Norm(`${e.name} ${JSON.stringify(e.meta)} ${(e.publicFacts||[]).map(f=>f.text).join(' ')}`);for(const t of terms)if(hay.includes(t))s+=4;s+=Math.max(0,5-Math.floor((Date.now()-Number(e.lastSeen||0))/86400000));return s}
function game36PublicContext(query=''){game36SeedEntities();const budget=Math.max(2500,Number(game36.settings.contextChars||7600)),entities=Object.values(game36.entities).filter(e=>!e.meta?.orphan).map(e=>({e,score:game36EntityScore(e,query)})).sort((a,b)=>b.score-a.score).slice(0,24).map(x=>x.e),out={campaignMemory:{digest:game36.digests[0]?.summary||game36Digest('context bootstrap').summary,entities:[],facts:[],instruction:'Esta memória contém apenas fatos públicos. Não extrapole fatos privados, segredos ou mecânicas não registradas.'}};let used=out.campaignMemory.digest.length;for(const e of entities){const row={type:e.type,name:e.name,meta:e.meta,facts:(e.publicFacts||[]).slice(0,6).map(f=>f.text)};const size=JSON.stringify(row).length;if(used+size>budget)break;out.campaignMemory.entities.push(row);used+=size}for(const f of game36.facts.filter(x=>x.visibility==='player').slice(0,50)){const row={text:f.text,source:f.source,confidence:f.confidence,tags:f.tags};const size=JSON.stringify(row).length;if(used+size>budget)break;out.campaignMemory.facts.push(row);used+=size}game36.lastContext={stamp:Date.now(),query,used,budget,entityCount:out.campaignMemory.entities.length,factCount:out.campaignMemory.facts.length};game36Save();return out}
function game36MasterContext(query=''){const pub=game36PublicContext(query);return Object.assign({},pub,{privateMemory:{facts:game36.facts.filter(x=>x.visibility!=='player').slice(0,80),entities:Object.values(game36.entities).map(e=>({id:e.id,type:e.type,name:e.name,privateFacts:(e.privateFacts||[]).slice(0,12)})).filter(e=>e.privateFacts.length)}})}
function game36FindEntity(name,type=''){const q=game36Norm(name);return Object.values(game36.entities).filter(e=>(!type||e.type===type)&&(game36Norm(e.name).includes(q)||(e.aliases||[]).some(a=>game36Norm(a).includes(q))))}
function game36Hook(){if(window.__game36Hook)return;window.__game36Hook=true;try{window.WWN_ENGINE?.on?.('*',evt=>game36RecordEvent(evt.type,evt.payload||{}))}catch(e){}try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action);return Object.assign({},c,game36PublicContext(action))}}}catch(e){}}
function game36Api(){window.WWN_MEMORY={version:36,seed:game36SeedEntities,addFact:game36AddFact,digest:game36Digest,publicContext:game36PublicContext,masterContext:game36MasterContext,findEntity:game36FindEntity,getState:()=>game36}}
function game36Init(){game36SeedEntities();if(!game36.digests.length)game36Digest('bootstrap');game36Hook();game36Api();game36Emit('memory.ready',{version:36,entities:Object.keys(game36.entities).length,facts:game36.facts.length})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game36Init);else game36Init();
