'use strict';
/* GAME_RUNTIME_V31 — resiliência: checkpoints IndexedDB, migração, auditoria e stress sintético. Sem UI. */
const GAME31_STORAGE='wwn_game_runtime_v31';
const GAME31_DB='wwn_resilience_v31';
const GAME31_STORE='snapshots';
const game31Default={schema:31,checkpointEvery:8,commitCount:0,lastCheckpoint:0,lastAudit:null,lastStress:null,migrations:[],errors:[]};
let game31=Object.assign({},game31Default,JSON.parse(localStorage.getItem(GAME31_STORAGE)||'null')||{});
let game31DbP=null;
function game31Save(){try{localStorage.setItem(GAME31_STORAGE,JSON.stringify(game31))}catch(e){}}
function game31Db(){if(game31DbP)return game31DbP;game31DbP=new Promise((resolve,reject)=>{const r=indexedDB.open(GAME31_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(GAME31_STORE)){const st=db.createObjectStore(GAME31_STORE,{keyPath:'id'});st.createIndex('stamp','stamp');st.createIndex('kind','kind')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return game31DbP}
function game31SafeKeys(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!/^wwn_/i.test(k)||k===GAME31_STORAGE)continue;if(/api.?key|gemini.*key|token|secret|credential/i.test(k))continue;out.push(k)}return out.sort()}
function game31Capture(kind='auto',label='checkpoint'){const data={id:`s${Date.now()}_${Math.random().toString(36).slice(2,6)}`,kind,label,stamp:Date.now(),schema:31,keys:{},meta:{}};for(const k of game31SafeKeys())data.keys[k]=localStorage.getItem(k);try{data.meta={character:gameState?.character?.name||'',day:clock?.day||1,hour:clock?.hour||0,worldTurns:gameState?.campaign?.worldTurns||0,journal:gameState?.journal?.length||0,transactions:window.WWN_ENGINE?.getState?.().tx?.length||0}}catch(e){}return data}
async function game31Put(snap){const db=await game31Db();await new Promise((resolve,reject)=>{const tx=db.transaction(GAME31_STORE,'readwrite');tx.objectStore(GAME31_STORE).put(snap);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});await game31Trim();game31.lastCheckpoint=snap.stamp;game31Save();return snap}
async function game31List(){const db=await game31Db();return new Promise((resolve,reject)=>{const tx=db.transaction(GAME31_STORE,'readonly'),r=tx.objectStore(GAME31_STORE).getAll();r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>b.stamp-a.stamp));r.onerror=()=>reject(r.error)})}
async function game31Trim(limit=12){const rows=await game31List();if(rows.length<=limit)return;const ids=rows.slice(limit).map(x=>x.id),db=await game31Db();await new Promise((resolve,reject)=>{const tx=db.transaction(GAME31_STORE,'readwrite'),st=tx.objectStore(GAME31_STORE);ids.forEach(id=>st.delete(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function game31Checkpoint(kind='auto',label='checkpoint'){try{return await game31Put(game31Capture(kind,label))}catch(e){game31.errors.unshift({stamp:Date.now(),where:'checkpoint',message:e?.message||String(e)});game31.errors=game31.errors.slice(0,30);game31Save();return null}}
async function game31Restore(id){const db=await game31Db(),snap=await new Promise((resolve,reject)=>{const tx=db.transaction(GAME31_STORE,'readonly'),r=tx.objectStore(GAME31_STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(!snap?.keys)throw new Error('Snapshot inválido');for(const [k,v] of Object.entries(snap.keys))if(/^wwn_/i.test(k)&&!/api.?key|gemini.*key|token|secret|credential/i.test(k))localStorage.setItem(k,String(v));return snap}
function game31Audit(){const issues=[],warn=[];const c=window.gameState?.character;if(!c)issues.push('personagem ausente');else{if(!Number.isFinite(Number(c.hp))||!Number.isFinite(Number(c.maxHp))||Number(c.maxHp)<=0)issues.push('PV inválido');if(Number(c.hp)>Number(c.maxHp)||Number(c.hp)<0)issues.push('PV fora do limite');if(!Array.isArray(c.inventory))issues.push('inventário inválido');if(!Array.isArray(c.skills))issues.push('perícias inválidas');if(Number(c.effort||0)<0||Number(c.effort||0)>Number(c.maxEffort||0))warn.push('Esforço fora do limite');if(Number(c.strain||0)<0||Number(c.strain||0)>Number(c.maxStrain||0))warn.push('System Strain fora do limite')}try{if(!Array.isArray(world)||!world.length)issues.push('mundo ausente');if(current<0||current>=world.length)issues.push('posição atual inválida');for(const id of knownPOIs||[])if(!byKey?.[id])warn.push(`POI conhecido sem hex: ${id}`)}catch(e){issues.push('mundo não carregado')}if(!Array.isArray(window.gameState?.npcs))warn.push('NPCs sem array persistente');if(!Array.isArray(window.gameState?.factions))warn.push('facções sem array persistente');if(window.WWN_ENGINE){const opens=WWN_ENGINE.getState?.().tx?.filter(x=>x.status==='open')||[];if(opens.length>3)warn.push(`${opens.length} transações abertas`)}const result={stamp:Date.now(),ok:issues.length===0,issues,warn,counts:{issues:issues.length,warnings:warn.length,storageKeys:game31SafeKeys().length}};game31.lastAudit=result;game31Save();return result}
function game31Repair(){const c=window.gameState?.character;if(c){c.maxHp=Math.max(1,Number(c.maxHp||1));c.hp=Math.max(0,Math.min(c.maxHp,Number(c.hp||0)));c.maxEffort=Math.max(0,Number(c.maxEffort||0));c.effort=Math.max(0,Math.min(c.maxEffort,Number(c.effort||0)));c.maxStrain=Math.max(1,Number(c.maxStrain||1));c.strain=Math.max(0,Math.min(c.maxStrain,Number(c.strain||0)));if(!Array.isArray(c.inventory))c.inventory=[];if(!Array.isArray(c.skills))c.skills=[]}if(window.gameState){if(!Array.isArray(gameState.npcs))gameState.npcs=[];if(!Array.isArray(gameState.factions))gameState.factions=[];if(!Array.isArray(gameState.journal))gameState.journal=[]}try{if(typeof gameSave==='function')gameSave()}catch(e){}return game31Audit()}
function game31Migrate(){const applied=[];try{const c=window.gameState?.character;if(c){if(c.level===undefined){c.level=1;applied.push('character.level=1')}if(!c.attributes){c.attributes={str:10,dex:10,con:10,int:10,wis:10,cha:10};applied.push('character.attributes')}if(c.nextXp===undefined){c.nextXp=Math.max(1,Number(c.level||1)+3);applied.push('character.nextXp')}}}catch(e){}try{if(typeof game14!=='undefined'&&!Array.isArray(game14.quests)){game14.quests=[];applied.push('game14.quests')}}catch(e){}try{if(typeof game21!=='undefined'){for(const k of ['foci','arts','spells','abilities'])if(!Array.isArray(game21[k])){game21[k]=[];applied.push(`game21.${k}`)}}}catch(e){}if(applied.length){game31.migrations.unshift({stamp:Date.now(),applied});game31.migrations=game31.migrations.slice(0,20);try{if(typeof gameSave==='function')gameSave();if(typeof game14Save==='function')game14Save();if(typeof game21Save==='function')game21Save()}catch(e){}}game31Save();return applied}
function game31Synthetic(seed=1){let x=seed>>>0;const rnd=()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296};return{rnd,state:{hp:24,maxHp:24,effort:5,maxEffort:5,strain:0,maxStrain:12,silver:120,xp:0,day:1,hour:8,fatigue:0,worldTurns:0,enemies:0,quests:0}}}
function game31SimTurn(sim){const r=sim.rnd,s=sim.state,kind=Math.floor(r()*8);if(kind===0){s.hp=Math.max(0,s.hp-Math.floor(r()*7))}else if(kind===1){s.hp=Math.min(s.maxHp,s.hp+Math.floor(r()*5));s.strain=Math.min(s.maxStrain,s.strain+1)}else if(kind===2){s.effort=Math.max(0,s.effort-1)}else if(kind===3){s.effort=Math.min(s.maxEffort,s.effort+1)}else if(kind===4){s.silver=Math.max(0,s.silver+(Math.floor(r()*21)-8))}else if(kind===5){s.xp+=r()<.18?1:0;s.quests+=r()<.08?1:0}else if(kind===6){s.fatigue=Math.min(6,s.fatigue+1);s.hour+=4}else{s.worldTurns++;s.hour+=6}while(s.hour>=24){s.hour-=24;s.day++}if(s.fatigue>=6){s.fatigue=2;s.hour+=8}return s}
function game31CheckSynthetic(s){const e=[];if(s.hp<0||s.hp>s.maxHp)e.push('hp');if(s.effort<0||s.effort>s.maxEffort)e.push('effort');if(s.strain<0||s.strain>s.maxStrain)e.push('strain');if(s.silver<0)e.push('silver');if(s.hour<0||s.hour>=24)e.push('hour');if(s.day<1)e.push('day');return e}
function game31RunStress(sessions=33,turnsPerSession=144){const report={stamp:Date.now(),sessions,turnsPerSession,totalTurns:0,checks:0,failures:[],maxDay:0,maxWorldTurns:0};for(let se=0;se<sessions;se++){const sim=game31Synthetic(1009+se*7919);for(let t=0;t<turnsPerSession;t++){game31SimTurn(sim);report.totalTurns++;const e=game31CheckSynthetic(sim.state);report.checks+=6;if(e.length)report.failures.push({session:se+1,turn:t+1,errors:e,state:{...sim.state}})}report.maxDay=Math.max(report.maxDay,sim.state.day);report.maxWorldTurns=Math.max(report.maxWorldTurns,sim.state.worldTurns)}report.pass=report.failures.length===0;game31.lastStress=report;game31Save();return report}
function game31Hook(){if(window.__game31Hook)return;window.__game31Hook=true;try{window.WWN_ENGINE?.on?.('transaction.committed',async evt=>{game31.commitCount++;if(game31.commitCount%Math.max(1,Number(game31.checkpointEvery||8))===0)await game31Checkpoint('auto',`commit ${game31.commitCount}`);if(game31.commitCount%5===0)game31Audit();game31Save()})}catch(e){}try{window.addEventListener('error',e=>{game31.errors.unshift({stamp:Date.now(),where:'window.error',message:e.message||'erro'});game31.errors=game31.errors.slice(0,30);game31Save()});window.addEventListener('unhandledrejection',e=>{game31.errors.unshift({stamp:Date.now(),where:'promise',message:String(e.reason?.message||e.reason||'rejection')});game31.errors=game31.errors.slice(0,30);game31Save()})}catch(e){}}
function game31Api(){window.WWN_RESILIENCE=Object.assign(window.WWN_RESILIENCE||{},{version:31,checkpoint:game31Checkpoint,list:game31List,restore:game31Restore,audit:game31Audit,repair:game31Repair,migrate:game31Migrate,stress:game31RunStress,getState:()=>game31})}
async function game31Init(){game31Migrate();game31Audit();game31Hook();game31Api();if(!game31.lastStress)game31RunStress(33,144);if(!game31.lastCheckpoint)await game31Checkpoint('boot','bootstrap v31');try{window.WWN_ENGINE?.emit?.('resilience.ready',{version:31,audit:game31.lastAudit,stress:{pass:game31.lastStress?.pass,totalTurns:game31.lastStress?.totalTurns}})}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game31Init);else game31Init();
