'use strict';
/* GAME_RUNTIME_V25 — diálogo persistente, memória social e conhecimento revelado. */
const GAME25_STORAGE='wwn_game_runtime_v25';
const game25Default={profiles:{},activeNpc:'',histories:{},busy:false,lastError:'',lastReply:'',lastChange:0};
function game25Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game25Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game25=game25Merge(game25Default,JSON.parse(localStorage.getItem(GAME25_STORAGE)||'null'));
function game25Save(){localStorage.setItem(GAME25_STORAGE,JSON.stringify(game25))}
function game25Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game25Toast(s){try{if(typeof toast==='function')toast(s)}catch(e){}}
function game25Log(k,t,d=''){try{if(typeof gameLog==='function')gameLog(k,t,d)}catch(e){}}
function game25Npcs(){try{return Array.isArray(gameState?.npcs)?gameState.npcs:[]}catch(e){return[]}}
function game25Relations(){try{return typeof game12!=='undefined'&&game12.relations?game12.relations:{}}catch(e){return{}}}
function game25Relation(name){return Number(game25Relations()[name]||0)}
function game25CurrentPlace(){try{const t=currentTile();if(t?.poi&&knownPOIs.has(key(t.q,t.r))&&POIS[t.poi])return POIS[t.poi].name;return BASES?.[t?.base]?.name||''}catch(e){return''}}
function game25EnsureProfiles(){for(const n of game25Npcs()){if(!n?.name)continue;if(!game25.profiles[n.name])game25.profiles[n.name]={name:n.name,role:n.role||'',location:n.location||'',intent:n.intent||'',disposition:'neutra',facts:[],secrets:[],revealed:[],notes:'',lastSeen:Date.now()};else{const p=game25.profiles[n.name];p.role=n.role||p.role;p.location=n.location||p.location;p.intent=n.intent||p.intent}}for(const name of Object.keys(game25.profiles))if(!game25Npcs().some(n=>n.name===name))game25.profiles[name].orphan=true;game25Save()}
function game25VisibleNpcs(){game25EnsureProfiles();const place=game25CurrentPlace().toLowerCase();const npcs=game25Npcs();if(!place)return npcs;const local=npcs.filter(n=>String(n.location||'').toLowerCase().includes(place.split(' ')[0]||place));return local.length?local:npcs}
function game25Profile(name){game25EnsureProfiles();return game25.profiles[name]||null}
function game25History(name){if(!game25.histories[name])game25.histories[name]=[];return game25.histories[name]}
function game25Push(name,role,text){const h=game25History(name);h.push({role,text:String(text||''),stamp:Date.now()});if(h.length>60)h.splice(0,h.length-60);game25.lastChange=Date.now();game25Save()}
function game25Inject(){const home=document.getElementById('inicio');if(home&&!document.getElementById('game25Home')){const a=document.getElementById('game24Home')||document.getElementById('game10Console')||document.getElementById('game9Play');a?.insertAdjacentHTML('afterend','<div id="game25Home" class="game25-runtime"></div>')}const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game25Master')){const a=document.getElementById('game24Master')||document.getElementById('game23Master')||document.getElementById('game14Master');a?.insertAdjacentHTML('afterend','<div id="game25Master" class="game25-runtime"></div>')}const ch=document.getElementById('personagem');if(ch&&!document.getElementById('game25Contacts')){const a=document.getElementById('game13Party')||document.getElementById('game21Character')||document.getElementById('game12Character');a?.insertAdjacentHTML('afterend','<div id="game25Contacts" class="game25-runtime"></div>')}}
function game25NpcOptions(){const npcs=game25VisibleNpcs();if(!game25.activeNpc&&npcs[0])game25.activeNpc=npcs[0].name;return npcs.map(n=>`<option value="${game25Esc(n.name)}" ${n.name===game25.activeNpc?'selected':''}>${game25Esc(n.name)} — ${game25Esc(n.role||'NPC')}</option>`).join('')}
function game25RenderHome(){const el=document.getElementById('game25Home');if(!el)return;game25EnsureProfiles();const opts=game25NpcOptions(),p=game25Profile(game25.activeNpc),h=p?game25History(p.name):[];el.innerHTML=`<div class="section-cap">Conversas & relações</div><div class="game25-card orn-card ${game25.busy?'game25-busy':''}"><div class="game25-head"><div><span class="game25-label">NPC em foco</span><h3>${game25Esc(p?.name||'Nenhum NPC disponível')}</h3><small>${game25Esc(p?`${p.role||'NPC'} • ${p.location||'local desconhecido'} • ${p.disposition||'neutra'}`:'')}</small></div>${p?`<span class="game25-chip ${game25Relation(p.name)>0?'good':game25Relation(p.name)<0?'warn':''}">relação ${game25Relation(p.name)>=0?'+':''}${game25Relation(p.name)}</span>`:''}</div><div style="margin-top:8px"><select class="game25-select" onchange="game25Select(this.value)">${opts||'<option>Nenhum NPC</option>'}</select></div>${p?`<div class="game25-grid" style="margin-top:8px"><div class="game25-kpi"><b>${p.facts.length+p.revealed.length}</b><small>fatos conhecidos</small></div><div class="game25-kpi"><b>${h.length}</b><small>falas registradas</small></div></div><div class="game25-compose"><input id="g25Talk" class="game25-input" maxlength="320" placeholder="Fale com ${game25Esc(p.name)}..." onkeydown="if(event.key==='Enter')game25Talk()"><button class="game25-send primary" onclick="game25Talk()">Falar</button></div><div class="game25-actions"><button onclick="game25NarrateLast()">Ouvir última fala</button><button onclick="game25ClearConversation()">Limpar conversa</button></div>${game25.lastError?`<div class="game25-note">${game25Esc(game25.lastError)}</div>`:''}<div class="game25-dialogue">${h.slice(-8).map(x=>`<div class="game25-line ${x.role}"><b>${x.role==='player'?'Você':game25Esc(p.name)}</b><small>${game25Esc(x.text)}</small></div>`).join('')||'<div class="game25-empty">A conversa ainda não começou.</div>'}</div>`:'<div class="game25-empty">Cadastre NPCs no mundo vivo para conversar com eles.</div>'}</div>`}
function game25RenderContacts(){const el=document.getElementById('game25Contacts');if(!el)return;game25EnsureProfiles();const rows=Object.values(game25.profiles).filter(p=>!p.orphan);el.innerHTML=`<div class="section-cap">Memória social</div><div class="game25-card orn-card"><div class="game25-master-list">${rows.map(p=>`<div class="game25-master-row"><b>${game25Esc(p.name)}</b><small>${game25Esc(p.role)} • ${game25Esc(p.location)} • ${game25Esc(p.intent||'sem intenção registrada')}</small><span class="game25-chip ${game25Relation(p.name)>0?'good':game25Relation(p.name)<0?'warn':''}">${game25Relation(p.name)>=0?'+':''}${game25Relation(p.name)} relação</span></div>`).join('')||'<div class="game25-empty">Nenhum contato persistente.</div>'}</div></div>`}
function game25RenderMaster(){const el=document.getElementById('game25Master');if(!el)return;game25EnsureProfiles();const p=game25Profile(game25.activeNpc);if(!p){el.innerHTML=`<div class="section-cap">Conhecimento dos NPCs</div><div class="game25-card orn-card"><div class="game25-empty">Selecione ou cadastre um NPC.</div></div>`;return}el.innerHTML=`<div class="section-cap">Conhecimento do NPC</div><div class="game25-card orn-card"><div class="game25-head"><div><span class="game25-label">Controle do Mestre</span><h3>${game25Esc(p.name)}</h3><small>Segredos nunca são enviados ao Gemini até serem revelados explicitamente.</small></div><div class="game25-relation"><button onclick="game25Rel(-1)">−</button><strong>${game25Relation(p.name)}</strong><button onclick="game25Rel(1)">+</button></div></div><div class="game25-grid" style="margin-top:8px"><label><span class="game25-label">Disposição</span><select id="g25Disposition" class="game25-select"><option ${p.disposition==='hostil'?'selected':''}>hostil</option><option ${p.disposition==='desconfiada'?'selected':''}>desconfiada</option><option ${p.disposition==='neutra'?'selected':''}>neutra</option><option ${p.disposition==='amistosa'?'selected':''}>amistosa</option><option ${p.disposition==='leal'?'selected':''}>leal</option></select></label><label><span class="game25-label">Local</span><input id="g25Location" class="game25-input" value="${game25Esc(p.location)}"></label></div><label class="game25-section" style="display:block"><span class="game25-label">Notas privadas do Mestre</span><textarea id="g25Notes" class="game25-textarea">${game25Esc(p.notes||'')}</textarea></label><div class="game25-actions"><button class="primary" onclick="game25SaveProfile()">Salvar perfil</button></div><div class="game25-section"><span class="game25-label">Fatos conhecidos pelo NPC / jogador</span>${[...p.facts,...p.revealed].map((x,i)=>`<div class="game25-fact game25-revealed"><b>${game25Esc(x.text||x)}</b><small>${i<p.facts.length?'fato público':'segredo revelado'}</small></div>`).join('')||'<div class="game25-empty">Nenhum fato cadastrado.</div>'}<div class="game25-compose"><input id="g25Fact" class="game25-input" placeholder="Novo fato conhecido"><button class="game25-send" onclick="game25AddFact()">Adicionar</button></div></div><div class="game25-section"><span class="game25-label">Segredos reservados</span>${p.secrets.map((x,i)=>`<div class="game25-fact game25-secret"><b>${game25Esc(x.text||x)}</b><small>não enviado ao jogador/Gemini</small><div class="game25-actions"><button onclick="game25Reveal(${i})">Revelar agora</button><button class="danger" onclick="game25RemoveSecret(${i})">Remover</button></div></div>`).join('')||'<div class="game25-empty">Nenhum segredo cadastrado.</div>'}<div class="game25-compose"><input id="g25Secret" class="game25-input" placeholder="Novo segredo do Mestre"><button class="game25-send" onclick="game25AddSecret()">Guardar</button></div></div></div>`}
function game25RenderAll(){game25Inject();game25RenderHome();game25RenderContacts();game25RenderMaster();game25Save()}
function game25Select(name){game25.activeNpc=name;game25.lastError='';game25Save();game25RenderAll()}
function game25Rel(d){const p=game25Profile(game25.activeNpc);if(!p)return;try{if(typeof game12Rel==='function'){game12Rel(p.name,d)}else{const r=game25Relations();r[p.name]=Number(r[p.name]||0)+Number(d||0)}}catch(e){}game25Save();game25RenderAll()}
function game25SaveProfile(){const p=game25Profile(game25.activeNpc);if(!p)return;p.disposition=document.getElementById('g25Disposition')?.value||p.disposition;p.location=document.getElementById('g25Location')?.value.trim()||p.location;p.notes=document.getElementById('g25Notes')?.value.trim()||'';const n=game25Npcs().find(x=>x.name===p.name);if(n)n.location=p.location;try{if(typeof gameSave==='function')gameSave()}catch(e){}game25Save();game25Log('npc',`Perfil atualizado: ${p.name}`,`${p.disposition} • ${p.location}`);game25RenderAll()}
function game25AddFact(){const p=game25Profile(game25.activeNpc),v=document.getElementById('g25Fact')?.value.trim();if(!p||!v)return;p.facts.push({text:v,stamp:Date.now()});game25Save();game25Log('npc',`Fato registrado para ${p.name}`,v);game25RenderAll()}
function game25AddSecret(){const p=game25Profile(game25.activeNpc),v=document.getElementById('g25Secret')?.value.trim();if(!p||!v)return;p.secrets.push({text:v,stamp:Date.now()});game25Save();game25Log('master',`Segredo guardado: ${p.name}`,'Informação reservada ao Mestre.');game25RenderAll()}
function game25Reveal(i){const p=game25Profile(game25.activeNpc);if(!p||!p.secrets[i])return;const x=p.secrets.splice(i,1)[0];p.revealed.push({...x,revealedAt:Date.now()});game25Save();game25Log('npc',`Segredo revelado por ${p.name}`,x.text);try{if(typeof g11Scene==='function'&&typeof g11Ready==='function'&&g11Ready())setTimeout(()=>g11Scene(false),60)}catch(e){}game25RenderAll()}
function game25RemoveSecret(i){const p=game25Profile(game25.activeNpc);if(!p)return;p.secrets.splice(i,1);game25Save();game25RenderAll()}
function game25PublicContext(name){const p=game25Profile(name);if(!p)return null;return{name:p.name,role:p.role,location:p.location,intent:p.intent,disposition:p.disposition,relationship:game25Relation(p.name),knownFacts:[...p.facts,...p.revealed].map(x=>x.text||x),recentDialogue:game25History(name).slice(-8).map(x=>({role:x.role,text:x.text}))}}
function game25SystemPrompt(p){return`Você interpreta APENAS o NPC ${p.name}, em português do Brasil, dentro de uma campanha de Worlds Without Number. Responda em fala natural e curta, mantendo personalidade, intenção e disposição. Use somente o CONTEXTO PÚBLICO fornecido. Não invente segredos, fatos de mundo, recompensas, rolagens, dano, modificadores ou resultados mecânicos. Não revele informação que não esteja em knownFacts/revealed. Se perguntarem algo que o NPC não sabe, ele deve demonstrar desconhecimento ou incerteza coerente. Não narre ações do jogador. Produza 1 ou 2 parágrafos curtos de fala/gesto do NPC.`}
async function game25Talk(){const p=game25Profile(game25.activeNpc),input=document.getElementById('g25Talk'),text=input?.value.trim()||'';if(!p||!text)return;game25Push(p.name,'player',text);if(input)input.value='';game25.busy=true;game25.lastError='';game25Save();game25RenderAll();let reply='';try{if(typeof g11Ready==='function'&&g11Ready()&&typeof g11!=='undefined'){const ctx=game25PublicContext(p.name);const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(g11.model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':g11.apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:game25SystemPrompt(p)}]},contents:[{role:'user',parts:[{text:`CONTEXTO PÚBLICO:\n${JSON.stringify(ctx)}\n\nFALA DO JOGADOR:\n${text}`}]}],generationConfig:{temperature:.8,maxOutputTokens:420}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Gemini HTTP ${r.status}`);reply=(d?.candidates?.[0]?.content?.parts||[]).map(x=>x.text||'').join('').trim();if(!reply)throw new Error('Gemini não retornou fala.')}else reply=`${p.name} considera suas palavras, mas a narrativa por Gemini ainda não está configurada neste dispositivo.`}catch(e){game25.lastError=e?.message||String(e);reply=`${p.name} não responde de forma clara agora.`}game25Push(p.name,'npc',reply);game25.lastReply=reply;game25.busy=false;game25Save();game25Log('dialogue',`Conversa com ${p.name}`,text);try{if(typeof game24FinalizeTurn==='function'){game24.lastNarrative=reply}}catch(e){}game25RenderAll()}
function game25NarrateLast(){if(!game25.lastReply)return;try{if(typeof game9Tts==='function')game9Tts(game25.lastReply)}catch(e){}}
function game25ClearConversation(){const p=game25Profile(game25.activeNpc);if(!p)return;if(!confirm(`Limpar o histórico de conversa com ${p.name}?`))return;game25.histories[p.name]=[];game25Save();game25RenderAll()}
function game25Context(){const p=game25Profile(game25.activeNpc);return p?{activeNpc:game25PublicContext(p.name)}:{}}
function game25HookGemini(){if(window.__game25GeminiHook)return;window.__game25GeminiHook=true;try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(...a){return Object.assign({},old.apply(this,a),game25Context())}}}catch(e){}}
function game25Hook(){if(window.__game25Hooked)return;window.__game25Hooked=true;game25HookGemini();try{if(typeof showView==='function'){const old=showView;window.showView=function(v){old(v);if(['inicio','mestre','personagem'].includes(v))requestAnimationFrame(game25RenderAll)}}}catch(e){}try{if(typeof gameRefreshAll==='function'){const old=gameRefreshAll;window.gameRefreshAll=function(){old();game25RenderAll()}}}catch(e){}setInterval(()=>game25HookGemini(),1200)}
function game25Init(){game25EnsureProfiles();game25Hook();game25RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game25Init);else game25Init();
