'use strict';
/* GAME_RUNTIME_V22 — consulta fundamentada na biblioteca local. Não substitui autoridade dos manuais. */
const GAME22_STORAGE='wwn_game_runtime_v22';
const game22Default={query:'',answer:'',lastSources:[],busy:false,lastError:'',lastAsked:0};
let game22=Object.assign({},game22Default,JSON.parse(localStorage.getItem(GAME22_STORAGE)||'null')||{});
function game22Save(){localStorage.setItem(GAME22_STORAGE,JSON.stringify({query:game22.query,answer:game22.answer,lastSources:game22.lastSources,lastError:game22.lastError,lastAsked:game22.lastAsked}))}
function game22Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game22Toast(s){try{if(typeof toast==='function')toast(s)}catch(e){}}
function game22Docs(){try{return Array.isArray(game13?.docs)?game13.docs:[]}catch(e){return[]}}
function game22Norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ')}
function game22Terms(q){const stop=new Set(['para','com','como','uma','uns','das','dos','que','por','sem','sobre','qual','quando','onde','isso','esta','esse','essa','the','and','with']);return [...new Set(game22Norm(q).split(/\s+/).filter(x=>x.length>2&&!stop.has(x)))]}
function game22Score(q,d){const terms=game22Terms(q),txt=game22Norm(`${d.title||''} ${d.text||''}`);if(!terms.length)return 0;let score=0;for(const t of terms){const n=txt.split(t).length-1;if(n)score+=4+Math.min(8,n*2)}const phrase=game22Norm(q).trim();if(phrase&&txt.includes(phrase))score+=18;return score}
function game22Search(q,limit=6){return game22Docs().map((d,i)=>({d,i,score:game22Score(q,d)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
function game22SourceLabel(x){return `${x.d.title||'Referência'} • trecho ${x.i+1}`}
function game22BuildContext(q){const rows=game22Search(q,6);return{rows,text:rows.map((x,n)=>`[F${n+1}] ${game22SourceLabel(x)}\n${x.d.text}`).join('\n\n').slice(0,7000)}}
function game22Inject(){const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game22Rules')){const a=document.getElementById('game14Master')||document.getElementById('game13Home')||document.getElementById('gameMasterRuntime');a?.insertAdjacentHTML('afterend','<div id="game22Rules" class="game22-runtime"></div>')}const cfg=document.getElementById('configuracoes');if(cfg&&!document.getElementById('game22RulesCfg'))cfg.insertAdjacentHTML('beforeend','<div id="game22RulesCfg" class="game22-runtime"></div>')}
function game22Render(){game22Inject();const docs=game22Docs(),titles=[...new Set(docs.map(d=>d.title||'Referência'))],el=document.getElementById('game22Rules');if(el){const rows=game22.lastSources||[];el.innerHTML=`<div class="section-cap">Consulta às regras</div><div class="game22-card orn-card"><div class="game22-grid"><div class="game22-kpi"><b>${docs.length}</b><small>trechos indexados</small></div><div class="game22-kpi"><b>${titles.length}</b><small>fontes</small></div><div class="game22-kpi"><b>${rows.length}</b><small>trechos recuperados</small></div></div><div class="game22-query"><input id="g22q" value="${game22Esc(game22.query)}" placeholder="Ex.: como funciona Shock? quando recuperar Esforço?" onkeydown="if(event.key==='Enter')game22Ask()"><button class="primary" onclick="game22Ask()">Perguntar</button></div>${game22.answer?`<div class="game22-answer"><span>${game22.lastError?'Resultado local':'Resposta fundamentada'}</span>${game22Esc(game22.answer).replace(/\n/g,'<br>')}</div>`:''}${rows.length?`<div class="game22-sources">${rows.map(x=>`<div class="game22-source"><span class="game22-score">score ${x.score}</span><b>${game22Esc(x.label)}</b><small>${game22Esc(x.preview)}</small></div>`).join('')}</div>`:''}<div class="game22-actions"><button onclick="game13Open&&game13Open()">Abrir biblioteca</button><button onclick="game22Clear()">Limpar resposta</button></div><div class="game22-note">A resposta usa apenas trechos recuperados da biblioteca local. Se os manuais importados não cobrirem a pergunta, o sistema deve dizer que a evidência é insuficiente em vez de completar com conhecimento externo.</div></div>`}const cfg=document.getElementById('game22RulesCfg');if(cfg)cfg.innerHTML=`<div class="section-cap">Estado da biblioteca</div><div class="game22-card orn-card"><span class="game22-badge ${docs.length?'ok':'warn'}">${docs.length?'biblioteca pronta':'sem manuais importados'}</span><h3 style="margin-top:7px">Regras recuperáveis pelo Mestre</h3><small>${docs.length?`${docs.length} trechos em ${titles.length} fonte(s).`:'Importe TXT/MD/JSON pela Biblioteca do Mestre.'}</small></div>`;game22Save()}
async function game22Ask(){const q=document.getElementById('g22q')?.value.trim()||game22.query.trim();if(!q){game22Toast('Digite uma pergunta sobre as regras.');return}game22.query=q;const ctx=game22BuildContext(q);game22.lastSources=ctx.rows.map(x=>({label:game22SourceLabel(x),score:x.score,preview:String(x.d.text||'').slice(0,220)}));if(!ctx.rows.length){game22.answer='A biblioteca local não contém evidência suficiente para responder a esta pergunta.';game22.lastError='sem evidência';game22Save();game22Render();return}game22.busy=true;game22.lastError='';game22.answer='Consultando os trechos recuperados…';game22Render();try{if(typeof g11==='undefined'||!g11.apiKey||!g11.enabled){game22.answer='Trechos relevantes encontrados. Configure o Gemini para sintetizar uma resposta; enquanto isso, consulte as fontes recuperadas abaixo.';game22.lastError='Gemini não configurado';return}const sys='Você é um assistente de regras de RPG. Responda SOMENTE com base nos EXCERTOS fornecidos. Não use conhecimento externo, não corrija o material, não complete lacunas. Preserve a terminologia das fontes. Cite [F1], [F2] etc. em cada afirmação relevante. Se os excertos não forem suficientes, diga explicitamente que a evidência é insuficiente.';const prompt=`PERGUNTA:\n${q}\n\nEXCERTOS:\n${ctx.text}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(g11.model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':g11.apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:sys}]},contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.15,maxOutputTokens:900}})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Gemini HTTP ${r.status}`);const text=(d?.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').trim();if(!text)throw new Error('Gemini não retornou texto.');game22.answer=text;game22.lastError='';game22.lastAsked=Date.now()}catch(e){game22.answer='Não foi possível sintetizar a resposta agora. Os trechos recuperados continuam disponíveis abaixo.';game22.lastError=e?.message||String(e)}finally{game22.busy=false;game22Save();game22Render()}}
function game22Clear(){game22.query='';game22.answer='';game22.lastSources=[];game22.lastError='';game22Save();game22Render()}
function game22ContextForAction(action=''){const q=[action,(()=>{try{return currentTile()?.poi&&knownPOIs.has(key(currentTile().q,currentTile().r))?POIS[currentTile().poi].name:''}catch(e){return''}})(),(()=>{try{return game14ActiveQuest()?.title||''}catch(e){return''}})()].filter(Boolean).join(' ');const ctx=game22BuildContext(q);return ctx.rows.length?ctx.rows.slice(0,4).map((x,n)=>`[R${n+1}] ${game22SourceLabel(x)}\n${x.d.text}`).join('\n\n').slice(0,4200):''}
function game22HookGemini(){if(window.__game22GeminiHook)return;window.__game22GeminiHook=true;try{if(typeof g11Ctx==='function'){const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action);const ref=game22ContextForAction(action);if(ref)c.authoritativeRuleExcerpts=ref;return c}}}catch(e){}}
function game22Hook(){if(window.__game22Hooked)return;window.__game22Hooked=true;game22HookGemini();try{if(typeof showView==='function'){const old=showView;window.showView=function(v){old(v);if(v==='mestre'||v==='configuracoes')requestAnimationFrame(game22Render)}}}catch(e){}setInterval(()=>{game22HookGemini()},1200)}
function game22Init(){game22Hook();game22Render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game22Init);else game22Init();
