'use strict';
/* GAME_RUNTIME_V7 — integração horizontal de campanha, ficha, combate, mundo vivo e diário. */
const GAME_STORAGE='wwn_game_runtime_v7';
const GAME_SNAPSHOT='wwn_game_snapshot_v7';
const gameDefault={
  character:{name:'Alaric Veyron',hp:27,maxHp:27,effort:6,maxEffort:6,strain:0,maxStrain:12,silver:184,xp:4,nextXp:6,skills:[['Exploração',2],['Sobrevivência',2],['Observação',1],['Furtividade',1],['Atletismo',1],['Convencer',0],['Curar',0],['Saber',0]],inventory:[['Espada longa','1 carga'],['Cota de couro','2 cargas'],['Mochila de viagem','1 carga'],['Rações','2 cargas'],['Tochas','1 carga'],['Corda','1 carga']]},
  campaign:{objective:'Investigar as ruínas além das Colinas das Brumas',tension:2,worldTurns:0,lastWorldReason:'início da campanha'},
  factions:[
    {name:'Casa Ferranor',goal:'Firmar a estrada das colinas',clock:2,max:6,stance:'cautelosa'},
    {name:'Clã do Pinhal Cinzento',goal:'Expulsar intrusos da serra',clock:1,max:6,stance:'hostil'},
    {name:'Mercadores da Ponte',goal:'Reabrir a rota oriental',clock:3,max:6,stance:'neutra'}
  ],
  npcs:[
    {name:'Mara Venn',role:'Batedora',location:'Vila agrícola',status:'ativa',intent:'Mapear a estrada antiga'},
    {name:'Irmão Ors',role:'Monge viajante',location:'Estrada do norte',status:'em trânsito',intent:'Chegar ao mosteiro'},
    {name:'Hadrik Tor',role:'Capataz',location:'Mina exposta',status:'ocupado',intent:'Proteger os trabalhadores'},
    {name:'Selka',role:'Caçadora',location:'Pinhal',status:'desconhecida',intent:'Rastrear uma criatura'}
  ],
  combat:{target:0,lastAttack:null,enemies:[{name:'Guerreiro',hp:7,maxHp:10,ac:12,attack:4,damage:1},{name:'Arqueiro',hp:6,maxHp:8,ac:12,attack:3,damage:1},{name:'Xamã',hp:5,maxHp:7,ac:11,attack:3,damage:0}]},
  journal:[]
};
function gameMerge(base,saved){if(Array.isArray(base))return Array.isArray(saved)?saved:base.slice();if(base&&typeof base==='object'){const out={};for(const k of Object.keys(base))out[k]=gameMerge(base[k],saved&&saved[k]);if(saved&&typeof saved==='object')for(const k of Object.keys(saved))if(!(k in out))out[k]=saved[k];return out}return saved===undefined?base:saved}
let gameState=gameMerge(gameDefault,JSON.parse(localStorage.getItem(GAME_STORAGE)||'null'));
function gameSave(){localStorage.setItem(GAME_STORAGE,JSON.stringify(gameState))}
function gameTime(){try{return typeof clockLabel==='function'?clockLabel():'Sessão '+(appState?.session||8)}catch(e){return'Sessão ativa'}}
function gameLog(kind,title,detail=''){gameState.journal.unshift({kind,title,detail,time:gameTime(),stamp:Date.now()});gameState.journal=gameState.journal.slice(0,120);gameSave();gameRefreshAll()}
function gameEscape(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function gamePct(v,m){return Math.max(0,Math.min(100,Math.round((Number(v)||0)/(Number(m)||1)*100)))}
function gameInjectPanels(){
  const home=document.getElementById('inicio');
  if(home&&!document.getElementById('gameCampaignState')){
    const hero=home.querySelector('.hero-campaign');
    hero?.insertAdjacentHTML('afterend','<div id="gameCampaignState" class="game-runtime"></div>');
  }
  const ch=document.getElementById('personagem');
  if(ch&&!document.getElementById('gameCharacterRuntime'))ch.insertAdjacentHTML('beforeend','<div id="gameCharacterRuntime" class="game-runtime"></div>');
  const co=document.getElementById('confronto');
  if(co&&!document.getElementById('gameCombatRuntime'))co.insertAdjacentHTML('beforeend','<div id="gameCombatRuntime" class="game-runtime"></div>');
  const ma=document.getElementById('mestre');
  if(ma&&!document.getElementById('gameMasterRuntime'))ma.insertAdjacentHTML('beforeend','<div id="gameMasterRuntime" class="game-runtime"></div>');
  const se=document.getElementById('sessoes');
  if(se&&!document.getElementById('gameSessionRuntime')){const list=se.querySelector('.sessions-list');list?.insertAdjacentHTML('beforebegin','<div id="gameSessionRuntime" class="game-runtime"></div>')}
  const cfg=document.getElementById('configuracoes');
  if(cfg&&!document.getElementById('gameDataRuntime'))cfg.insertAdjacentHTML('beforeend','<div id="gameDataRuntime" class="game-runtime"></div>');
  document.querySelectorAll('#configuracoes .setting-row').forEach(r=>{if(/fog of war|névoa densa/i.test(r.textContent))r.classList.add('fog-setting-hidden')});
  gameBindCharacterTabs();gameBindMasterTabs();gameBindCombatTargets();gameBindCombatButtons();
}
function gameRenderHome(){const el=document.getElementById('gameCampaignState');if(!el)return;const c=gameState.campaign;const seen=typeof world!=='undefined'?world.filter(t=>t.seen).length:0;const pois=typeof knownPOIs!=='undefined'?knownPOIs.size:0;el.innerHTML=`<div class="section-cap">Estado da campanha</div><div class="game-grid"><div class="game-stat orn-card game-wide"><span>Objetivo atual</span><b>${gameEscape(c.objective)}</b><small>O Mestre automático mantém mundo, facções e registro enquanto você joga.</small></div><div class="game-stat orn-card"><span>Mundo conhecido</span><b>${seen} hexes</b><small>${pois} locais descobertos</small></div><div class="game-stat orn-card"><span>Tensão</span><b>${c.tension}/6</b><div class="game-meter danger"><i style="width:${gamePct(c.tension,6)}%"></i></div></div><div class="game-stat orn-card"><span>Turnos do mundo</span><b>${c.worldTurns}</b><small>${gameEscape(c.lastWorldReason)}</small></div><div class="game-stat orn-card"><span>Personagem</span><b>${gameState.character.hp}/${gameState.character.maxHp} PV</b><small>Esforço ${gameState.character.effort}/${gameState.character.maxEffort}</small></div></div>`;
  const note=homeNote();const strip=document.querySelector('#inicio .note-strip');if(strip&&note){const b=strip.querySelector('b'),s=strip.querySelector('small');if(b)b.textContent=note.title;if(s)s.textContent=note.detail||note.time}
}
function homeNote(){return gameState.journal[0]||null}
function gameRenderCharacter(){const c=gameState.character;const hp=document.querySelector('#personagem .hp-big');if(hp)hp.innerHTML=`${c.hp} <small>/ ${c.maxHp}</small>`;const hpbar=document.querySelector('#personagem .hp-panel .meter i');if(hpbar)hpbar.style.width=gamePct(c.hp,c.maxHp)+'%';const effort=document.querySelector('#personagem .three-stat .sheetstat:nth-child(3) b');if(effort)effort.textContent=`${c.effort}/${c.maxEffort}`;
  const el=document.getElementById('gameCharacterRuntime');if(!el)return;el.innerHTML=`<div id="gameCharResumo" class="game-tabpanel active"><div class="section-cap">Recursos em jogo</div><div class="game-grid"><div class="game-stat orn-card"><span>PV</span><b>${c.hp}/${c.maxHp}</b><div class="game-meter danger"><i style="width:${gamePct(c.hp,c.maxHp)}%"></i></div><div class="game-btns" style="margin-top:7px"><button class="game-mini danger" onclick="gameHp(-1)">−</button><button class="game-mini" onclick="gameHp(1)">+</button></div></div><div class="game-stat orn-card"><span>Esforço</span><b>${c.effort}/${c.maxEffort}</b><div class="game-meter"><i style="width:${gamePct(c.effort,c.maxEffort)}%"></i></div><div class="game-btns" style="margin-top:7px"><button class="game-mini danger" onclick="gameEffort(-1)">−</button><button class="game-mini" onclick="gameEffort(1)">+</button></div></div><div class="game-stat orn-card"><span>System Strain</span><b>${c.strain}/${c.maxStrain}</b><div class="game-meter danger"><i style="width:${gamePct(c.strain,c.maxStrain)}%"></i></div></div><div class="game-stat orn-card"><span>Prata</span><b>${c.silver}</b><small>recursos carregados</small></div><div class="game-stat orn-card game-wide"><span>Experiência</span><b>${c.xp} / ${c.nextXp}</b><div class="game-meter"><i style="width:${gamePct(c.xp,c.nextXp)}%"></i></div></div></div></div><div id="gameCharSkills" class="game-tabpanel"><div class="section-cap">Perícias</div><div class="game-panel orn-card">${c.skills.map(([n,b])=>`<div class="game-row"><div><b>${gameEscape(n)}</b><small>Teste rápido do personagem</small></div><button class="game-mini primary" onclick="rollSkill('${gameEscape(n)}',${b})">${b>=0?'+':''}${b}</button></div>`).join('')}</div></div><div id="gameCharGear" class="game-tabpanel"><div class="section-cap">Equipamento</div><div class="game-panel orn-card">${c.inventory.map(([n,w])=>`<div class="game-row"><div><b>${gameEscape(n)}</b><small>${gameEscape(w)}</small></div><span class="game-chip">carregado</span></div>`).join('')}</div></div><div id="gameCharMagic" class="game-tabpanel"><div class="section-cap">Magia & Artes</div><div class="game-panel orn-card"><h3>Nenhuma tradição ativa</h3><div class="muted">Este personagem não possui uma tradição arcana ativa registrada nesta ficha. O painel fica reservado para Artes, Esforço comprometido e feitiços quando aplicáveis.</div></div></div>`;gameApplyCharacterTab(gameCharTab)}
let gameCharTab='resumo';
function gameBindCharacterTabs(){const tabs=[...document.querySelectorAll('#personagem .char-tabs button')];const ids=['resumo','skills','gear','magic'];tabs.forEach((b,i)=>{if(b.dataset.gameBound)return;b.dataset.gameBound='1';b.addEventListener('click',()=>{gameCharTab=ids[i];gameApplyCharacterTab(gameCharTab)})})}
function gameApplyCharacterTab(tab){const tabs=[...document.querySelectorAll('#personagem .char-tabs button')],ids=['resumo','skills','gear','magic'];tabs.forEach((b,i)=>{b.classList.toggle('active',ids[i]===tab);b.classList.toggle('game-active',ids[i]===tab)});const staticEls=['.portrait-card','.three-stat','.six-stat','.char-bottom-grid','.encumbrance'];staticEls.forEach(sel=>document.querySelectorAll('#personagem '+sel).forEach(e=>e.style.display=tab==='resumo'?'':'none'));const map={resumo:'gameCharResumo',skills:'gameCharSkills',gear:'gameCharGear',magic:'gameCharMagic'};document.querySelectorAll('#gameCharacterRuntime .game-tabpanel').forEach(e=>e.classList.remove('active'));document.getElementById(map[tab])?.classList.add('active')}
function gameHp(delta){const c=gameState.character;c.hp=Math.max(0,Math.min(c.maxHp,c.hp+delta));gameSave();gameLog('character',delta<0?'Ferimento registrado':'Recuperação registrada',`PV ${c.hp}/${c.maxHp}`)}
function gameEffort(delta){const c=gameState.character;c.effort=Math.max(0,Math.min(c.maxEffort,c.effort+delta));gameSave();gameLog('character',delta<0?'Esforço comprometido':'Esforço recuperado',`Esforço ${c.effort}/${c.maxEffort}`)}
function gameRenderCombat(){const co=gameState.combat;const rows=[...document.querySelectorAll('#confronto .combatant.enemy')];rows.forEach((el,i)=>{const e=co.enemies[i];if(!e)return;el.classList.toggle('game-target',i===co.target&&e.hp>0);el.classList.toggle('game-dead',e.hp<=0);const small=el.querySelector('small');if(small)small.textContent=`PV ${Math.max(0,e.hp)}/${e.maxHp} • CA ${e.ac}`});const el=document.getElementById('gameCombatRuntime');if(!el)return;const target=co.enemies[co.target];el.innerHTML=`<div class="section-cap">Mestre automático</div><div class="game-grid"><div class="game-stat orn-card"><span>Alvo</span><b>${gameEscape(target?.name||'—')}</b><small>${target?`PV ${Math.max(0,target.hp)}/${target.maxHp} • CA ${target.ac}`:'Sem alvo'}</small></div><div class="game-stat orn-card"><span>Herói</span><b>${gameState.character.hp}/${gameState.character.maxHp} PV</b><small>CA 15 • turno do jogador</small></div></div><div class="game-action-state"><span>Inimigos vivos: ${co.enemies.filter(e=>e.hp>0).length}</span><span>Rodada ${appState?.combatRound||1}</span></div>`}
function gameBindCombatTargets(){document.querySelectorAll('#confronto .combatant.enemy').forEach((el,i)=>{if(el.dataset.gameTarget)return;el.dataset.gameTarget='1';el.addEventListener('click',()=>{if(gameState.combat.enemies[i]?.hp<=0)return;gameState.combat.target=i;gameSave();gameRenderCombat()})})}
function gameBindCombatButtons(){const buttons=[...document.querySelectorAll('#confronto .combat-action')];buttons.forEach(b=>{const txt=b.textContent.trim().toLowerCase();if(txt.includes('fuga'))b.onclick=()=>gameFlee();if(txt.includes('item'))b.onclick=()=>gameUseItem();if(txt.includes('habilidade'))b.onclick=()=>gameAbility()})}
function gameCombatAttack(){const co=gameState.combat;let target=co.enemies[co.target];if(!target||target.hp<=0){co.target=co.enemies.findIndex(e=>e.hp>0);target=co.enemies[co.target]}if(!target){toast('O combate foi encerrado.');return}const roll=1+Math.floor(Math.random()*20),bonus=5,total=roll+bonus,hit=total>=target.ac;co.lastAttack={roll,bonus,total,hit,target:co.target};gameSave();document.getElementById('combatDie').textContent=roll;document.getElementById('combatTotal').textContent=total;const out=document.getElementById('combatOutcome');if(out){out.textContent=hit?'ACERTO!':'ERRO';out.className=hit?'hit':'muted'}gameLog('combat',`Ataque contra ${target.name}`,`${roll} + ${bonus} = ${total} contra CA ${target.ac}${hit?' — acerto':' — erro'}`);gameRenderCombat()}
function gameCombatDamage(){const co=gameState.combat,a=co.lastAttack;if(!a||!a.hit){toast('É preciso acertar o ataque antes de rolar o dano.');return}const target=co.enemies[a.target];if(!target||target.hp<=0){toast('O alvo já está fora de combate.');return}const d=1+Math.floor(Math.random()*8),total=d+3;target.hp=Math.max(0,target.hp-total);co.lastAttack=null;gameSave();document.getElementById('damageTotal').textContent=total;gameLog('combat',target.hp<=0?`${target.name} derrotado`:`Dano em ${target.name}`,`${d} + 3 = ${total}; PV ${target.hp}/${target.maxHp}`);gameRenderCombat();if(co.enemies.every(e=>e.hp<=0)){gameState.campaign.tension=Math.max(0,gameState.campaign.tension-1);gameLog('combat','Encontro encerrado','Todos os inimigos estão fora de combate.');toast('Encontro encerrado.') }}
function gameEnemyPhase(){const living=gameState.combat.enemies.filter(e=>e.hp>0);if(!living.length)return'Nenhum inimigo capaz de agir.';let totalDamage=0,parts=[];living.forEach((e,i)=>{const r=1+Math.floor(Math.random()*20),hit=r+e.attack>=15;if(hit){const dmg=1+Math.floor(Math.random()*6)+e.damage;totalDamage+=dmg;parts.push(`${e.name} acerta (${dmg})`)}else parts.push(`${e.name} erra`)});if(totalDamage){gameState.character.hp=Math.max(0,gameState.character.hp-totalDamage)}return parts.join(' • ')+(totalDamage?` • ${totalDamage} dano total`:'')}
function gameNextRound(){const summary=gameEnemyPhase();appState.combatRound=(appState.combatRound||1)+1;saveApp();if(typeof nextRound==='function')nextRound();gameSave();gameLog('combat',`Rodada ${appState.combatRound}`,summary);document.getElementById('combatRound').textContent=appState.combatRound;gameRenderCharacter();gameRenderCombat();if(gameState.character.hp<=0)toast('O personagem chegou a 0 PV. Resolva a situação antes de continuar.')}
function gameFlee(){const r=1+Math.floor(Math.random()*6);const ok=r>=4;gameLog('combat',ok?'Fuga bem-sucedida':'Fuga bloqueada',`Resultado do Mestre: ${r}`);if(ok){gameState.campaign.tension=Math.max(0,gameState.campaign.tension-1);gameSave();appGo('explorar')}else toast('A retirada foi bloqueada.')}
function gameUseItem(){gameLog('combat','Item preparado','O personagem usa/prepara um item do inventário.');toast('Uso de item registrado.')}
function gameAbility(){gameLog('combat','Habilidade declarada','Ação especial registrada para resolução do Mestre.');toast('Habilidade registrada.')}
let gameMasterTab='oracles';
function gameBindMasterTabs(){const tabs=[...document.querySelectorAll('#mestre .master-tabs button')],ids=['oracles','tables','npcs','factions'];tabs.forEach((b,i)=>{if(b.dataset.gameBound)return;b.dataset.gameBound='1';b.addEventListener('click',()=>{gameMasterTab=ids[i];gameRenderMaster()})});const tools=[...document.querySelectorAll('#mestre .tool-card')];tools.forEach(b=>{const t=b.textContent.toLowerCase();if(t.includes('turno de facção'))b.onclick=()=>gameWorldTurn('turno de facção');if(t.includes('tensão'))b.onclick=()=>gameTension();if(t.includes('gerador de nomes'))b.onclick=()=>gameGenerateName()})}
function gameRenderMaster(){const el=document.getElementById('gameMasterRuntime');if(!el)return;const tabs=[...document.querySelectorAll('#mestre .master-tabs button')],ids=['oracles','tables','npcs','factions'];tabs.forEach((b,i)=>{b.classList.toggle('active',ids[i]===gameMasterTab);b.classList.toggle('game-active',ids[i]===gameMasterTab)});document.querySelectorAll('#mestre .oracle-hero,#mestre .oracle-grid,#mestre .oracle-result').forEach(e=>e.style.display=gameMasterTab==='oracles'?'':'none');let html='';if(gameMasterTab==='oracles'){html=`<div class="section-cap">Estado do mundo</div><div class="game-grid"><div class="game-stat orn-card"><span>Tensão</span><b>${gameState.campaign.tension}/6</b><div class="game-meter danger"><i style="width:${gamePct(gameState.campaign.tension,6)}%"></i></div></div><div class="game-stat orn-card"><span>Turnos de facção</span><b>${gameState.campaign.worldTurns}</b><small>${gameEscape(gameState.campaign.lastWorldReason)}</small></div></div>`}else if(gameMasterTab==='tables'){const rows=['Encontro local','Reação social','Complicação de jornada','Rumor','Descoberta','Pressão de facção'];html=`<div class="section-cap">Tabelas rápidas</div><div class="game-panel orn-card">${rows.map((r,i)=>`<div class="game-row"><div><b>${r}</b><small>Resultado contextual registrado no diário.</small></div><button class="game-mini primary" onclick="gameQuickTable(${i})">Rolar</button></div>`).join('')}</div>`}else if(gameMasterTab==='npcs'){html=`<div class="section-cap">NPCs do mundo vivo</div><div class="game-panel orn-card">${gameState.npcs.map(n=>`<div class="game-row"><div><b>${gameEscape(n.name)} — ${gameEscape(n.role)}</b><small>${gameEscape(n.location)} • ${gameEscape(n.intent)}</small></div><span class="npc-status">${gameEscape(n.status)}</span></div>`).join('')}</div>`}else{html=`<div class="section-cap">Facções & projetos</div><div class="game-panel orn-card">${gameState.factions.map(f=>`<div class="game-row"><div><b>${gameEscape(f.name)}</b><small>${gameEscape(f.goal)} • ${gameEscape(f.stance)}</small><div class="faction-clock">${Array.from({length:f.max},(_,i)=>`<i class="${i<f.clock?'on':''}"></i>`).join('')}</div></div><span class="game-chip ${f.stance==='hostil'?'warn':''}">${f.clock}/${f.max}</span></div>`).join('')}</div><div class="toolrow" style="margin-top:8px"><button class="action primary" onclick="gameWorldTurn('turno manual de facção')">Executar turno do mundo</button></div>`}el.innerHTML=html}
function gameQuickTable(i){const tables=[['Patrulha em movimento','Viajante buscando abrigo','Sinais de predador','Caravana atrasada'],['Hostil','Desconfiada','Cautelosa','Neutra','Favorável'],['Caminho bloqueado','Clima piora','Rastro interessante','Atalho arriscado'],['Uma rota foi fechada','Uma ruína foi aberta','Alguém desapareceu','Uma recompensa foi oferecida'],['Marcas antigas','Fonte de água','Passagem escondida','Vestígios recentes'],['Recrutamento','Expansão territorial','Negociação','Retaliação']];const a=tables[i]||tables[0],r=a[Math.floor(Math.random()*a.length)];gameLog('oracle','Tabela rápida',r);toast(r)}
function gameWorldTurn(reason='passagem de tempo'){gameState.campaign.worldTurns++;gameState.campaign.lastWorldReason=reason;const turn=gameState.campaign.worldTurns;gameState.factions.forEach((f,i)=>{const advance=((turn+i)%3===0)||((turn+i)%5===0);if(advance)f.clock=Math.min(f.max,f.clock+1)});const locs=['Vila agrícola','Estrada do norte','Colinas','Ponte de pedra','Pinhal','Mina exposta'];gameState.npcs.forEach((n,i)=>{if((turn+i)%2===0)n.location=locs[(turn+i)%locs.length];n.status=(turn+i)%4===0?'em trânsito':(turn+i)%3===0?'ocupado':'ativa'});if(turn%2===0)gameState.campaign.tension=Math.min(6,gameState.campaign.tension+1);gameSave();gameLog('world','O mundo avançou',`${reason}. Projetos de facção e NPCs foram atualizados.`);document.getElementById('gameMasterRuntime')?.classList.add('world-pulse');setTimeout(()=>document.getElementById('gameMasterRuntime')?.classList.remove('world-pulse'),600)}
function gameTension(){gameState.campaign.tension=gameState.campaign.tension>=6?1:gameState.campaign.tension+1;gameSave();gameLog('world','Tensão da aventura',`Nível atual: ${gameState.campaign.tension}/6`);gameRenderMaster()}
function gameGenerateName(){const first=['Aren','Belka','Corven','Dara','Edrik','Fara','Galen','Hessa','Ivar','Jora'],last=['Venn','Tor','Serr','Morn','Kael','Dovar','Renn','Val','Ors','Dain'];const n=first[Math.floor(Math.random()*first.length)]+' '+last[Math.floor(Math.random()*last.length)];gameLog('oracle','Nome gerado',n);toast(n)}
function gameRenderSessions(){const el=document.getElementById('gameSessionRuntime');if(!el)return;const j=gameState.journal.slice(0,14);el.innerHTML=`<div class="session-live orn-card"><div class="headline"><div><div class="eyebrow">Sessão ${appState?.session||8} • ativa</div><h3>${gameEscape(gameState.campaign.objective)}</h3><div class="muted">${gameTime()} • ${j.length} registros recentes</div></div><span class="game-chip good">em andamento</span></div><textarea id="gameSessionNote" class="game-note-input" placeholder="Anotação rápida da sessão..."></textarea><div class="toolrow" style="margin-top:7px"><button class="action primary" onclick="gameAddSessionNote()">Registrar nota</button><button class="action" onclick="gameWorldTurn('fechamento de cena')">Fechar cena</button></div></div><div class="section-cap">Linha do tempo</div><div class="game-journal">${j.length?j.map(x=>`<div class="journal-item ${gameEscape(x.kind)}"><b>${gameEscape(x.title)}</b><small>${gameEscape(x.time)}${x.detail?' • '+gameEscape(x.detail):''}</small></div>`).join(''):'<div class="orn-card" style="padding:16px;opacity:.65">As ações da campanha serão registradas aqui automaticamente.</div>'}</div>`}
function gameAddSessionNote(){const input=document.getElementById('gameSessionNote'),v=input?.value.trim();if(!v)return;gameLog('note','Nota da sessão',v);if(input)input.value='';toast('Nota registrada.')}
function gameRenderData(){const el=document.getElementById('gameDataRuntime');if(!el)return;const has=!!localStorage.getItem(GAME_SNAPSHOT);el.innerHTML=`<div class="section-cap">Continuidade</div><div class="game-panel orn-card"><h3>Snapshot da campanha</h3><div class="muted">Salva estado do mundo, Atlas, personagem, combate, facções e diário no próprio dispositivo.</div><div class="snapshot-box"><button class="action primary" onclick="gameSnapshotSave()">Salvar snapshot</button><button class="action" onclick="gameSnapshotRestore()" ${has?'':'disabled'}>Restaurar</button><button class="action" onclick="gameSnapshotDownload()">Exportar JSON</button><button class="action danger" onclick="gameRuntimeReset()">Reiniciar runtime</button></div></div>`}
function gameSnapshotObject(){const data={created:new Date().toISOString(),runtime:gameState,storage:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('wwn_'))data.storage[k]=localStorage.getItem(k)}return data}
function gameSnapshotSave(){localStorage.setItem(GAME_SNAPSHOT,JSON.stringify(gameSnapshotObject()));toast('Snapshot completo salvo.');gameRenderData()}
function gameSnapshotRestore(){const raw=localStorage.getItem(GAME_SNAPSHOT);if(!raw)return;try{const s=JSON.parse(raw);Object.entries(s.storage||{}).forEach(([k,v])=>localStorage.setItem(k,v));if(s.runtime)localStorage.setItem(GAME_STORAGE,JSON.stringify(s.runtime));location.reload()}catch(e){toast('Snapshot inválido.')}}
function gameSnapshotDownload(){const blob=new Blob([JSON.stringify(gameSnapshotObject(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='braseiro-wwn-snapshot.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function gameRuntimeReset(){localStorage.removeItem(GAME_STORAGE);location.reload()}
function gameFloatPoiLabels(){const c=document.getElementById('mapCanvas');if(!c||typeof world==='undefined')return;c.querySelector('.poi-label-overlay')?.remove();const overlay=document.createElement('div');overlay.className='poi-label-overlay';c.appendChild(overlay);[...c.querySelectorAll('.hex')].forEach((hex,i)=>{if(!hex.classList.contains('poi-known'))return;const t=world[i];if(!t?.poi||!POIS[t.poi])return;const left=parseFloat(hex.style.left)||0,top=parseFloat(hex.style.top)||0,l=document.createElement('div');l.className='poi-label-float'+(i===current?' current':'');l.textContent=POIS[t.poi].name;l.style.left=(left+HEX_W/2)+'px';l.style.top=(top+76)+'px';overlay.appendChild(l)})}
function gameRefreshAll(){gameInjectPanels();gameRenderHome();gameRenderCharacter();gameRenderCombat();gameRenderMaster();gameRenderSessions();gameRenderData();gameFloatPoiLabels()}
/* Hooks: as ações do jogador alimentam automaticamente diário e mundo vivo. */
if(typeof travel==='function'){const _gameTravel=travel;travel=function(i){const before=typeof current!=='undefined'?current:-1;_gameTravel(i);if(typeof current!=='undefined'&&current!==before){const t=currentTile();gameLog('travel','Jornada concluída',`${BASES[t.base].name} • Q ${t.q} R ${t.r}`)}}}
if(typeof explore==='function'){const _gameExplore=explore;explore=function(){const before=typeof knownPOIs!=='undefined'?knownPOIs.size:0;_gameExplore();const after=knownPOIs.size;gameLog('travel','Exploração do hex',after>before?`${after-before} local(is) revelado(s)`:'Área explorada')}}
if(typeof inspectPOI==='function'){const _gameInspect=inspectPOI;inspectPOI=function(){const t=currentTile(),id=key(t.q,t.r),before=knownPOIs.has(id);_gameInspect();if(!before&&knownPOIs.has(id))gameLog('travel','Local investigado',POIS[t.poi]?.name||'POI')}}
if(typeof enterPOI==='function'){const _gameEnter=enterPOI;enterPOI=function(){const t=currentTile(),id=key(t.q,t.r),before=enteredPOIs.has(id);_gameEnter();if(!before&&enteredPOIs.has(id))gameLog('travel','Local visitado',POIS[t.poi]?.name||'POI')}}
if(typeof camp==='function'){const _gameCamp=camp;camp=function(){_gameCamp();gameLog('travel','Acampamento','O grupo encerrou a jornada e descansou.');gameWorldTurn('acampamento')}}
if(typeof oracleRoll==='function'){const _gameOracle=oracleRoll;oracleRoll=function(type){_gameOracle(type);const o=appState.lastOracle;if(o)gameLog('oracle',`Oráculo: ${o.type}`,`${o.die} — ${o.result}`)}}
if(typeof combatAttack==='function')combatAttack=gameCombatAttack;
if(typeof combatDamage==='function')combatDamage=gameCombatDamage;
if(typeof nextCombatRound==='function')nextCombatRound=gameNextRound;
if(typeof wwnRenderMap==='function'){const _gameMap=wwnRenderMap;wwnRenderMap=function(){_gameMap();gameFloatPoiLabels()};render=wwnRenderMap}
if(typeof appGo==='function'){const _gameGo=appGo;appGo=function(v){_gameGo(v);requestAnimationFrame(gameRefreshAll)}}
if(typeof showView==='function'){const _gameShow=showView;showView=function(v){_gameShow(v);requestAnimationFrame(gameRefreshAll)}}
/* Fog foi aposentado visualmente; mantém compatibilidade de storage sem renderizar camada. */
try{if(typeof appState!=='undefined'){appState.fog=false;saveApp?.()}document.body.classList.add('fog-disabled')}catch(e){}
if(!gameState.journal.length)gameState.journal=[{kind:'world',title:'Campanha carregada',detail:'Mundo vivo, personagem e sessão sincronizados.',time:gameTime(),stamp:Date.now()}];
gameSave();
requestAnimationFrame(()=>{gameInjectPanels();gameRefreshAll()});
