'use strict';
/* GAME_RUNTIME_V8 — missões, expedição, encontros contextuais, TTS, autosave e mundo vivo. */
const GAME8_STORAGE='wwn_game_runtime_v8';
const GAME8_AUTOSAVE='wwn_game_autosaves_v8';
const GAME8_VERSION=8;
const game8Saved=JSON.parse(localStorage.getItem(GAME8_STORAGE)||'null')||{};
const game8Default={
  expedition:{rations:7,torches:5,water:6,fatigue:0,maxFatigue:6,lastCampDay:1,lastCampHour:0},
  quests:[
    {id:'ruinas',title:'Além das Colinas das Brumas',desc:'Encontrar uma rota segura e alcançar um local perigoso ligado às ruínas antigas.',active:true,reward:'2 XP • 80 prata',done:false,steps:[
      {id:'mapa',text:'Mapear pelo menos 8 hexes',type:'seen',target:8},
      {id:'pistas',text:'Descobrir 2 locais de interesse',type:'pois',target:2},
      {id:'perigo',text:'Entrar em um POI perigoso',type:'danger',target:1}
    ]},
    {id:'estrada',title:'A Estrada de Ferranor',desc:'Acompanhar a abertura da rota oriental enquanto facções disputam a região.',active:false,reward:'1 XP • contato local',done:false,steps:[
      {id:'turnos',text:'Deixar o mundo avançar por 2 turnos',type:'world',target:2},
      {id:'ponte',text:'Descobrir a Ponte de Pedra',type:'namedPoi',target:'Ponte de pedra'}
    ]}
  ],
  lastEncounter:null,
  lastScene:null,
  lastAction:null,
  autosaveCounter:0,
  narration:true
};
function game8Merge(base,saved){if(Array.isArray(base))return Array.isArray(saved)?saved:base.slice();if(base&&typeof base==='object'){const o={};for(const k of Object.keys(base))o[k]=game8Merge(base[k],saved&&saved[k]);if(saved&&typeof saved==='object')for(const k of Object.keys(saved))if(!(k in o))o[k]=saved[k];return o}return saved===undefined?base:saved}
let game8=game8Merge(game8Default,game8Saved);
function game8Save(){localStorage.setItem(GAME8_STORAGE,JSON.stringify(game8))}
function game8Escape(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game8Toast(s){if(typeof toast==='function')toast(s)}
function game8Log(kind,title,detail=''){if(typeof gameLog==='function')gameLog(kind,title,detail);else if(typeof note==='function')note(title+(detail?' — '+detail:''))}
function game8Tile(){try{return currentTile()}catch(e){return null}}
function game8TileId(t){try{return key(t.q,t.r)}catch(e){return t?`${t.q},${t.r}`:''}}
function game8KnownPoi(t){if(!t?.poi)return false;try{return knownPOIs.has(game8TileId(t))}catch(e){return false}}
function game8PoiName(t){return game8KnownPoi(t)&&window.POIS?.[t.poi]?POIS[t.poi].name:''}
function game8TerrainName(t){return t&&window.BASES?.[t.base]?BASES[t.base].name:'Terreno desconhecido'}
function game8FeatureName(t){return t?.feature&&window.FEATURES?.[t.feature]?FEATURES[t.feature].name:''}
function game8RegionName(t){try{return labelRegion(t.region)}catch(e){return t?.region||'região'} }
function game8Clock(){try{return clockLabel()}catch(e){return 'Sessão ativa'}}
function game8SkillBonus(name){const arr=window.gameState?.character?.skills||[];const r=arr.find(x=>String(x[0]).toLowerCase()===String(name).toLowerCase());return r?Number(r[1])||0:0}
function game8Roll2d6(bonus=0){const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);return{a,b,bonus,total:a+b+bonus}}
function game8Advance(hours){if(typeof advance==='function')advance(hours)}
function game8WorldTurns(){return Number(window.gameState?.campaign?.worldTurns)||0}
function game8KnownPoiCount(){try{return knownPOIs.size}catch(e){return 0}}
function game8SeenCount(){try{return world.filter(t=>t.seen).length}catch(e){return 0}}
function game8EnteredDangerous(){try{let n=0;for(const id of enteredPOIs){const t=byKey[id];if(t?.poi&&POIS[t.poi]?.type==='perigoso')n++}return n}catch(e){return 0}}
function game8NamedPoi(name){try{for(const id of knownPOIs){const t=byKey[id];if(t?.poi&&POIS[t.poi]?.name===name)return 1}return 0}catch(e){return 0}}
function game8StepValue(step){if(step.type==='seen')return game8SeenCount();if(step.type==='pois')return game8KnownPoiCount();if(step.type==='danger')return game8EnteredDangerous();if(step.type==='world')return game8WorldTurns();if(step.type==='namedPoi')return game8NamedPoi(step.target);return 0}
function game8StepDone(step){const v=game8StepValue(step);return step.type==='namedPoi'?v>=1:v>=Number(step.target||1)}
function game8QuestDone(q){return q.steps.every(game8StepDone)}
function game8QuestProgress(q){const done=q.steps.filter(game8StepDone).length;return{done,total:q.steps.length,pct:Math.round(done/Math.max(1,q.steps.length)*100)}}
function game8ActiveQuest(){return game8.quests.find(q=>q.active&&!q.done)||game8.quests.find(q=>!q.done)||game8.quests[0]}
function game8UpdateQuests(source='progresso'){let changed=false;for(const q of game8.quests){if(!q.done&&game8QuestDone(q)){q.done=true;q.active=false;changed=true;if(window.gameState?.character){gameState.character.xp=(Number(gameState.character.xp)||0)+(q.id==='ruinas'?2:1);if(q.id==='ruinas')gameState.character.silver=(Number(gameState.character.silver)||0)+80;if(typeof gameSave==='function')gameSave()}game8Log('quest',`Missão concluída: ${q.title}`,q.reward)}}if(changed){const next=game8.quests.find(q=>!q.done);if(next)next.active=true}game8Save();game8RenderAll();if(changed)game8Autosave('missão concluída');}
function game8SetQuest(id){game8.quests.forEach(q=>q.active=q.id===id&&!q.done);game8Save();game8RenderAll();game8Log('quest','Objetivo alterado',game8ActiveQuest()?.title||'Todas as missões concluídas')}
function game8Inject(){
  const home=document.getElementById('inicio');if(home&&!document.getElementById('game8Home'))document.getElementById('gameCampaignState')?.insertAdjacentHTML('afterend','<div id="game8Home" class="game8-runtime"></div>');
  const exp=document.getElementById('explorar');if(exp&&!document.getElementById('game8Explore')){const loc=document.getElementById('locationPanel');(loc||exp.querySelector('.event-card'))?.insertAdjacentHTML('afterend','<div id="game8Explore" class="game8-runtime"></div>')}
  const ch=document.getElementById('personagem');if(ch&&!document.getElementById('game8Character'))document.getElementById('gameCharacterRuntime')?.insertAdjacentHTML('afterend','<div id="game8Character" class="game8-runtime"></div>');
  const ma=document.getElementById('mestre');if(ma&&!document.getElementById('game8Master'))document.getElementById('gameMasterRuntime')?.insertAdjacentHTML('afterend','<div id="game8Master" class="game8-runtime"></div>');
  const se=document.getElementById('sessoes');if(se&&!document.getElementById('game8Quests'))document.getElementById('gameSessionRuntime')?.insertAdjacentHTML('afterend','<div id="game8Quests" class="game8-runtime"></div>');
  const cfg=document.getElementById('configuracoes');if(cfg&&!document.getElementById('game8Data'))document.getElementById('gameDataRuntime')?.insertAdjacentHTML('afterend','<div id="game8Data" class="game8-runtime"></div>');
  document.querySelectorAll('#configuracoes .setting-row').forEach(r=>{if(/fog of war|névoa densa/i.test(r.textContent))r.style.display='none'});
}
function game8RenderHome(){const el=document.getElementById('game8Home');if(!el)return;const q=game8ActiveQuest(),p=q?game8QuestProgress(q):{done:0,total:0,pct:100},e=game8.expedition;el.innerHTML=`<div class="section-cap">Expedição</div><div class="game8-grid"><div class="game8-card orn-card game8-wide"><span>Missão ativa</span><b>${game8Escape(q?.title||'Sem missão ativa')}</b><small>${game8Escape(q?.desc||'O mundo continua ativo.')}</small>${q?`<div class="game8-meter"><i style="width:${p.pct}%"></i></div><em>${p.done}/${p.total} etapas</em>`:''}</div><div class="game8-card orn-card"><span>Provisões</span><b>${e.rations}</b><small>rações</small></div><div class="game8-card orn-card"><span>Tochas</span><b>${e.torches}</b><small>unidades</small></div><div class="game8-card orn-card"><span>Fadiga</span><b>${e.fatigue}/${e.maxFatigue}</b><div class="game8-meter danger"><i style="width:${Math.round(e.fatigue/e.maxFatigue*100)}%"></i></div></div><div class="game8-card orn-card"><span>Estado</span><b>${e.rations>1?'Preparado':'Suprimentos baixos'}</b><small>${game8Clock()}</small></div></div>`}
function game8SceneText(){const t=game8Tile();if(!t)return'Nenhuma cena ativa.';const parts=[game8TerrainName(t)];const f=game8FeatureName(t);if(f)parts.push(f);const poi=game8PoiName(t);if(poi)parts.push(poi);let tail='A região permanece aberta à exploração.';if(t.poi&&!poi)tail='Há sinais de algo importante, mas o local ainda não foi identificado.';if(poi&&POIS[t.poi]?.type==='perigoso')tail='O local conhecido carrega sinais claros de risco e pede cautela.';return `${parts.join(' • ')}. ${tail}`}
function game8RenderExplore(){const el=document.getElementById('game8Explore');if(!el)return;const t=game8Tile(),e=game8.expedition,last=game8.lastEncounter;el.innerHTML=`<div class="section-cap">Cena & expedição</div><div class="game8-scene orn-card"><div class="game8-scene-head"><div><span>${game8Escape(game8RegionName(t))}</span><b>${game8Escape(game8PoiName(t)||game8TerrainName(t))}</b></div><button class="game8-icon" onclick="game8NarrateScene()" title="Narrar cena">◖</button></div><p>${game8Escape(game8SceneText())}</p><div class="game8-chips"><i>${e.rations} rações</i><i>${e.torches} tochas</i><i>fadiga ${e.fatigue}/${e.maxFatigue}</i></div><div class="game8-actions"><button onclick="game8Scout()">Observar região</button><button onclick="game8Forage()">Buscar recursos</button><button onclick="game8GenerateEncounter()">Encontro contextual</button></div></div>${last?`<div class="game8-encounter orn-card"><span>Último encontro</span><b>${game8Escape(last.title)}</b><p>${game8Escape(last.text)}</p>${last.hostile?'<button onclick="game8StartEncounter()">Iniciar confronto</button>':''}</div>`:''}`}
function game8RenderCharacter(){const el=document.getElementById('game8Character');if(!el)return;const e=game8.expedition,c=window.gameState?.character||{};el.innerHTML=`<div class="section-cap">Estado de aventura</div><div class="game8-grid"><div class="game8-card orn-card"><span>System Strain</span><b>${c.strain??0}/${c.maxStrain??12}</b><small>controle persistente</small></div><div class="game8-card orn-card"><span>Fadiga de viagem</span><b>${e.fatigue}/${e.maxFatigue}</b><small>registro da expedição</small></div><div class="game8-card orn-card game8-wide"><span>Suprimentos de campo</span><div class="game8-resource-row"><button onclick="game8Supply('rations',-1)">−</button><b>${e.rations} rações</b><button onclick="game8Supply('rations',1)">+</button><button onclick="game8Supply('torches',-1)">−</button><b>${e.torches} tochas</b><button onclick="game8Supply('torches',1)">+</button></div></div></div>`}
function game8RenderQuests(){const el=document.getElementById('game8Quests');if(!el)return;el.innerHTML=`<div class="section-cap">Missões da campanha</div><div class="game8-questlist">${game8.quests.map(q=>{const p=game8QuestProgress(q);return`<div class="game8-quest orn-card ${q.active?'active':''} ${q.done?'done':''}"><div class="game8-quest-head"><div><span>${q.done?'Concluída':q.active?'Ativa':'Disponível'}</span><b>${game8Escape(q.title)}</b></div>${!q.done?`<button onclick="game8SetQuest('${q.id}')">${q.active?'Ativa':'Ativar'}</button>`:'<i>✓</i>'}</div><p>${game8Escape(q.desc)}</p>${q.steps.map(s=>`<div class="game8-step ${game8StepDone(s)?'done':''}"><i>${game8StepDone(s)?'✓':'○'}</i><span>${game8Escape(s.text)}</span></div>`).join('')}<div class="game8-meter"><i style="width:${p.pct}%"></i></div><small>Recompensa: ${game8Escape(q.reward)}</small></div>`}).join('')}</div>`}
function game8RenderMaster(){const el=document.getElementById('game8Master');if(!el)return;const t=game8Tile(),f=window.gameState?.factions||[],n=window.gameState?.npcs||[];el.innerHTML=`<div class="section-cap">Mundo vivo</div><div class="game8-masterbar orn-card"><div><span>Contexto atual</span><b>${game8Escape(game8PoiName(t)||game8TerrainName(t))}</b><small>${game8Escape(game8RegionName(t))} • ${game8Clock()}</small></div><div class="game8-actions"><button onclick="gameWorldTurn('turno manual do Mestre')">Avançar mundo</button><button onclick="game8GenerateEncounter(true)">Gerar encontro</button><button onclick="game8GenerateRumor()">Gerar rumor</button></div></div><div class="game8-split"><div><div class="game8-subcap">NPCs em movimento</div>${n.slice(0,6).map(x=>`<div class="game8-minirow orn-card"><b>${game8Escape(x.name)}</b><span>${game8Escape(x.location)}</span><small>${game8Escape(x.intent||x.status)}</small></div>`).join('')}</div><div><div class="game8-subcap">Facções</div>${f.map(x=>`<div class="game8-minirow orn-card"><b>${game8Escape(x.name)}</b><span>${game8Escape(x.stance)}</span><small>${game8Escape(x.goal)} • ${x.clock}/${x.max}</small></div>`).join('')}</div></div>`}
function game8RenderData(){const el=document.getElementById('game8Data');if(!el)return;const saves=JSON.parse(localStorage.getItem(GAME8_AUTOSAVE)||'[]');el.innerHTML=`<div class="section-cap">Continuidade automática</div><div class="game8-data orn-card"><div><b>Autosaves</b><small>${saves.length} snapshots rotativos • runtime v${GAME8_VERSION}</small></div><div class="game8-actions"><button onclick="game8Autosave('manual')">Salvar agora</button><button onclick="game8RestoreLatest()" ${saves.length?'':'disabled'}>Restaurar último</button><button onclick="game8ExportCampaign()">Exportar campanha</button></div></div>`}
function game8RenderAll(){game8Inject();game8RenderHome();game8RenderExplore();game8RenderCharacter();game8RenderQuests();game8RenderMaster();game8RenderData();game8FixLabels()}
function game8Supply(k,delta){const e=game8.expedition;e[k]=Math.max(0,(Number(e[k])||0)+delta);game8Save();game8RenderAll();game8Log('character',delta<0?'Suprimento consumido':'Suprimento adicionado',`${k==='rations'?'Rações':'Tochas'}: ${e[k]}`)}
function game8Scout(){const bonus=game8SkillBonus('Exploração'),r=game8Roll2d6(bonus),ok=r.total>=8;game8Advance(2);if(ok){const h=game8Tile();let n=0;try{for(const d of DIRS){const x=tile(h.q+d.q,h.r+d.r);if(x&&!x.seen){x.seen=true;n++}}if(typeof render==='function')render()}catch(e){}game8.lastAction={title:'Observação bem-sucedida',text:`${r.a}+${r.b}+${bonus} = ${r.total}. ${n} hex(es) ganharam informação de terreno.`};game8Log('travel','Região observada',game8.lastAction.text)}else{if(window.gameState?.campaign)gameState.campaign.tension=Math.min(6,(gameState.campaign.tension||0)+1);game8.lastAction={title:'Observação inconclusiva',text:`${r.a}+${r.b}+${bonus} = ${r.total}. A tensão aumentou.`};game8Log('travel','Observação inconclusiva',game8.lastAction.text)}game8Save();game8UpdateQuests('observar');game8RenderAll()}
function game8Forage(){const bonus=game8SkillBonus('Sobrevivência'),r=game8Roll2d6(bonus),ok=r.total>=8;game8Advance(2);if(ok){game8.expedition.rations++;game8Log('travel','Recursos encontrados',`${r.a}+${r.b}+${bonus} = ${r.total}. +1 ração.`)}else{game8.expedition.fatigue=Math.min(game8.expedition.maxFatigue,game8.expedition.fatigue+1);game8Log('travel','Busca sem resultado',`${r.a}+${r.b}+${bonus} = ${r.total}. Fadiga ${game8.expedition.fatigue}/${game8.expedition.maxFatigue}.`)}game8Save();game8RenderAll()}
const GAME8_ENCOUNTERS={
 heartland:[['Patrulha local','Uma patrulha pede notícias da estrada e observa o grupo com cautela.',false],['Bandidos na estrada','Homens armados bloqueiam uma passagem e exigem pagamento.',true],['Caravana cansada','Mercadores procuram um lugar seguro para descansar e trocar informações.',false]],
 forest:[['Caçadores do pinhal','Um pequeno grupo segue rastros recentes entre as árvores.',false],['Predadores famintos','Movimento baixo e rápido cerca a trilha.',true],['Sinais de acampamento','Fumaça distante sugere viajantes ou saqueadores nas proximidades.',false]],
 wetlands:[['Luzes no brejo','Luzes fracas se movem onde não deveria haver caminho.',false],['Criaturas do lodo','Formas pesadas emergem da água escura.',true],['Passagem alagada','A rota segura termina em água profunda e vegetação fechada.',false]],
 uplands:[['Batedores hostis','Vigias armados observam a passagem das alturas.',true],['Pedras marcadas','Símbolos antigos indicam um limite ou aviso esquecido.',false],['Cabras de montanha','Um rebanho selvagem denuncia uma trilha praticável.',false]],
 pine:[['Caçadores cinzentos','Arqueiros do clã local surgem entre os pinheiros.',true],['Bosque silencioso','A floresta fica estranhamente quieta e sem pássaros.',false],['Mensageiro ferido','Um viajante cai na trilha com notícias urgentes.',false]],
 arid:[['Saqueadores','Cavaleiros leves aparecem no horizonte e fecham distância.',true],['Fonte rara','Uma depressão no terreno guarda água suficiente para uma pausa.',false],['Tempestade de poeira','A visibilidade cai e a rota some por alguns instantes.',false]],
 volcanic:[['Servos da ruína','Figuras armadas vasculham as pedras negras em busca de algo.',true],['Vidro antigo','Fragmentos vitrificados formam desenhos impossíveis no chão.',false],['Tremor distante','O solo vibra e pequenas pedras descem pelas encostas.',false]],
 coast:[['Barqueiros locais','Pescadores oferecem passagem em troca de ajuda ou moeda.',false],['Saqueadores ribeirinhos','Homens armados avançam de uma enseada oculta.',true],['Destroços recentes','Madeira quebrada e cargas molhadas chegam à margem.',false]],
 frost:[['Lobos do gelo','Olhos acompanham o grupo por trás da neve.',true],['Abrigo de pedra','Uma saliência protegida oferece descanso do vento.',false],['Pegadas humanas','Uma trilha recente corta a neve na direção oposta.',false]]
};
function game8GenerateEncounter(master=false){const t=game8Tile(),region=t?.region||'heartland',list=GAME8_ENCOUNTERS[region]||GAME8_ENCOUNTERS.heartland,seed=Math.floor(Math.random()*list.length),x=list[seed];const poi=game8PoiName(t);let text=x[1];if(poi)text+=` O encontro acontece nas proximidades de ${poi}.`;game8.lastEncounter={title:x[0],text,hostile:x[2],region,time:game8Clock(),enemies:x[2]?game8EncounterEnemies(region):[]};game8Save();game8Log('world',`Encontro: ${x[0]}`,text);game8RenderAll();if(master)game8Toast(`Encontro gerado: ${x[0]}`);return game8.lastEncounter}
function game8EncounterEnemies(region){const set={heartland:[['Saqueador',8,13,3],['Saqueador',8,13,3],['Chefe',12,14,4]],forest:[['Predador',7,13,3],['Predador',7,13,3],['Predador alfa',11,14,4]],wetlands:[['Criatura do lodo',9,12,3],['Criatura do lodo',9,12,3],['Brutamonte do brejo',14,13,4]],uplands:[['Batedor',8,13,3],['Batedor',8,13,3],['Veterano',12,14,4]],pine:[['Arqueiro do clã',7,13,3],['Arqueiro do clã',7,13,3],['Caçador veterano',11,14,4]],arid:[['Saqueador',8,13,3],['Saqueador',8,13,3],['Cavaleiro',12,14,4]],volcanic:[['Servo da ruína',9,13,3],['Servo da ruína',9,13,3],['Guardião',13,14,4]],coast:[['Saqueador ribeirinho',8,13,3],['Saqueador ribeirinho',8,13,3],['Capitão',12,14,4]],frost:[['Lobo do gelo',7,13,3],['Lobo do gelo',7,13,3],['Lobo alfa',11,14,4]]};return(set[region]||set.heartland).map(([name,hp,ac,attack])=>({name,hp,maxHp:hp,ac,attack,damage:1}))}
function game8StartEncounter(){const e=game8.lastEncounter;if(!e?.hostile||!e.enemies?.length){game8Toast('O último encontro não exige confronto.');return}if(!window.gameState?.combat)return;gameState.combat.enemies=e.enemies.map(x=>({...x}));gameState.combat.target=0;gameState.combat.lastAttack=null;if(window.appState)appState.combatRound=1;if(typeof gameSave==='function')gameSave();if(typeof saveApp==='function')saveApp();game8Log('combat',`Confronto iniciado: ${e.title}`,e.text);if(typeof appGo==='function')appGo('confronto');if(typeof gameRenderCombat==='function')gameRenderCombat()}
const GAME8_RUMORS=['Uma torre antiga voltou a mostrar luz à noite.','Mercadores juram que uma estrada mudou de lugar depois da última tempestade.','Um senhor local oferece prata por notícias de ruínas recém-abertas.','Caçadores desapareceram perto dos limites do pinhal.','Há marcas de ferramentas antigas em pedras que ninguém consegue mover.','Uma facção está comprando mapas velhos e pagando muito por eles.'];
function game8GenerateRumor(){const s=GAME8_RUMORS[Math.floor(Math.random()*GAME8_RUMORS.length)];game8Log('world','Rumor',s);game8Toast(s);game8Speak(s)}
function game8Speak(text){if(!game8.narration||!window.speechSynthesis)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='pt-BR';u.rate=.96;u.pitch=.88;speechSynthesis.speak(u)}catch(e){}}
function game8NarrateScene(){const s=game8SceneText();game8.lastScene={text:s,time:Date.now()};game8Save();game8Speak(s);game8Log('scene','Cena narrada',s)}
function game8Autosave(reason='automático'){const pack={version:GAME8_VERSION,reason,at:Date.now(),game8:JSON.parse(JSON.stringify(game8)),game:window.gameState?JSON.parse(JSON.stringify(gameState)):null,app:window.appState?JSON.parse(JSON.stringify(appState)):null,world:localStorage.getItem('wwn_world_engine_v4'),atlas:localStorage.getItem('wwn_atlas_ui_v5')};let arr=JSON.parse(localStorage.getItem(GAME8_AUTOSAVE)||'[]');arr.unshift(pack);arr=arr.slice(0,5);localStorage.setItem(GAME8_AUTOSAVE,JSON.stringify(arr));game8.autosaveCounter++;game8Save();game8RenderData();game8Toast('Snapshot salvo.')}
function game8RestoreLatest(){const arr=JSON.parse(localStorage.getItem(GAME8_AUTOSAVE)||'[]');if(!arr.length){game8Toast('Nenhum autosave disponível.');return}const s=arr[0];if(s.world)localStorage.setItem('wwn_world_engine_v4',s.world);if(s.atlas)localStorage.setItem('wwn_atlas_ui_v5',s.atlas);if(s.game)localStorage.setItem('wwn_game_runtime_v7',JSON.stringify(s.game));if(s.app)localStorage.setItem('wwn_app_v6',JSON.stringify(s.app));if(s.game8)localStorage.setItem(GAME8_STORAGE,JSON.stringify(s.game8));location.reload()}
function game8ExportCampaign(){const data={exportedAt:new Date().toISOString(),version:GAME8_VERSION,game8,game:window.gameState||null,app:window.appState||null,world:localStorage.getItem('wwn_world_engine_v4'),atlas:localStorage.getItem('wwn_atlas_ui_v5')};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='braseiro-wwn-campanha.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function game8AfterTravel(){game8.expedition.fatigue=Math.min(game8.expedition.maxFatigue,game8.expedition.fatigue+1);if(game8.expedition.fatigue>=5)game8Toast('A expedição está muito cansada. Considere acampar.');game8Save();game8UpdateQuests('viagem');if(++game8.autosaveCounter%3===0)game8Autosave('viagem')}
function game8AfterCamp(){if(game8.expedition.rations>0)game8.expedition.rations--;game8.expedition.fatigue=Math.max(0,game8.expedition.fatigue-3);try{game8.expedition.lastCampDay=clock.day;game8.expedition.lastCampHour=clock.hour}catch(e){}game8Save();game8Log('travel','Expedição descansou',`${game8.expedition.rations} ração(ões) restante(s); fadiga ${game8.expedition.fatigue}/${game8.expedition.maxFatigue}.`);game8Autosave('acampamento')}
function game8FixLabels(){const overlay=document.querySelector('.poi-label-overlay');if(overlay){overlay.style.zIndex='120';overlay.style.overflow='visible';overlay.style.pointerEvents='none'}document.querySelectorAll('.poi-label-float').forEach(e=>{e.style.zIndex='121';e.style.pointerEvents='none'})}
function game8Wrap(){
  if(typeof travel==='function'&&!travel._game8){const old=travel;travel=function(i){const before=typeof current!=='undefined'?current:null;const r=old(i);if(before!==current)game8AfterTravel();return r};travel._game8=true}
  if(typeof explore==='function'&&!explore._game8){const old=explore;explore=function(){const r=old();game8UpdateQuests('exploração');game8RenderAll();return r};explore._game8=true}
  if(typeof enterPOI==='function'&&!enterPOI._game8){const old=enterPOI;enterPOI=function(){const before=game8EnteredDangerous();const r=old();if(game8EnteredDangerous()>before)game8UpdateQuests('POI perigoso');game8RenderAll();return r};enterPOI._game8=true}
  if(typeof camp==='function'&&!camp._game8){const old=camp;camp=function(){const r=old();game8AfterCamp();game8RenderAll();return r};camp._game8=true}
  if(typeof gameWorldTurn==='function'&&!gameWorldTurn._game8){const old=gameWorldTurn;gameWorldTurn=function(reason){const r=old(reason);game8UpdateQuests('mundo vivo');game8Autosave('turno do mundo');return r};gameWorldTurn._game8=true}
  if(typeof wwnRenderMap==='function'&&!wwnRenderMap._game8){const old=wwnRenderMap;wwnRenderMap=function(){const r=old();requestAnimationFrame(game8FixLabels);return r};wwnRenderMap._game8=true;window.render=wwnRenderMap}
  if(typeof showView==='function'&&!showView._game8){const old=showView;showView=function(v){const r=old(v);requestAnimationFrame(game8RenderAll);return r};showView._game8=true}
  if(window.appState){appState.fog=false;if(typeof saveApp==='function')saveApp()}
}
function game8Boot(){game8Inject();game8Wrap();game8UpdateQuests('boot');game8RenderAll();setTimeout(game8RenderAll,120);setTimeout(game8FixLabels,250)}
game8Boot();
