'use strict';
/* GAME_RUNTIME_V13 — biblioteca/RAG local e companhia. */
const GAME13_STORAGE='wwn_game_runtime_v13';
const game13Default={docs:[],party:[],lastSearch:''};
function game13Merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a.slice();if(a&&typeof a==='object'){const o={};for(const k of Object.keys(a))o[k]=game13Merge(a[k],b&&b[k]);if(b&&typeof b==='object')for(const k of Object.keys(b))if(!(k in o))o[k]=b[k];return o}return b===undefined?a:b}
let game13=game13Merge(game13Default,JSON.parse(localStorage.getItem(GAME13_STORAGE)||'null'));
function game13Save(){localStorage.setItem(GAME13_STORAGE,JSON.stringify(game13))}
function game13Esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function game13Npcs(){return window.gameState?.npcs||[]}
function game13Chunk(text,title){const clean=String(text||'').replace(/\r/g,'').replace(/\n{3,}/g,'\n\n').trim();const out=[];for(let i=0;i<clean.length;i+=900){const part=clean.slice(i,i+900).trim();if(part)out.push({id:`d${Date.now()}_${out.length}`,title:title||'Referência',text:part,stamp:Date.now()})}return out}
function game13Score(q,t){const terms=String(q||'').toLowerCase().split(/\s+/).filter(x=>x.length>2);if(!terms.length)return 0;const s=String(t||'').toLowerCase();let n=0;for(const term of terms){if(s.includes(term))n+=2;const c=s.split(term).length-1;n+=Math.min(4,c)}return n}
function game13Search(q,limit=5){const query=String(q||'').trim();if(!query)return[];return game13.docs.map(d=>({d,score:game13Score(query,`${d.title} ${d.text}`)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.d)}
function game13Context(q){return game13Search(q,4).map(d=>`[${d.title}] ${d.text}`).join('\n\n').slice(0,3200)}
function game13Inject(){
  if(!document.getElementById('game13Overlay'))document.body.insertAdjacentHTML('beforeend','<div id="game13Overlay" class="game13-overlay" onclick="if(event.target===this)game13Close()"><div class="game13-sheet"><div class="game13-head"><div><div class="game12-label">Biblioteca do Mestre</div><h2>Regras & Referências</h2></div><button class="game13-close" onclick="game13Close()">×</button></div><div id="game13Library"></div></div></div>');
  const ch=document.getElementById('personagem');if(ch&&!document.getElementById('game13Party')){const a=document.getElementById('game12Character')||document.getElementById('gameCharacterRuntime');a?.insertAdjacentHTML('afterend','<div id="game13Party" class="game13-runtime"></div>')}
  const home=document.getElementById('inicio');if(home&&!document.getElementById('game13Home')){const a=document.getElementById('game12Home')||document.getElementById('game10Console');a?.insertAdjacentHTML('afterend','<div id="game13Home" class="game13-runtime"></div>')}
  document.querySelectorAll('#inicio .quick-card').forEach(b=>{if(/Regras/i.test(b.textContent)){b.onclick=()=>game13Open()}})
}
function game13RenderLibrary(){const el=document.getElementById('game13Library');if(!el)return;const results=game13.lastSearch?game13Search(game13.lastSearch,8):[];el.innerHTML=`<div class="game13-stats"><span class="game13-pill">${game13.docs.length} trechos</span><span class="game13-pill">RAG local</span><span class="game13-pill">Gemini contextual</span></div><div class="game13-search"><input id="game13Query" class="game13-input" placeholder="Buscar regra, termo ou situação..." value="${game13Esc(game13.lastSearch)}" onkeydown="if(event.key==='Enter')game13DoSearch()"><button class="game13-btn" onclick="game13DoSearch()">Buscar</button></div>${results.length?results.map(r=>`<div class="game13-result"><b>${game13Esc(r.title)}</b><p>${game13Esc(r.text)}</p></div>`).join(''):(game13.lastSearch?'<div class="game13-result"><small>Nenhum trecho encontrado.</small></div>':'')}<div class="game12-divider"></div><textarea id="game13Paste" class="game13-text" placeholder="Cole aqui um trecho de manual, regra da campanha ou referência textual..."></textarea><div class="game13-toolbar"><button class="game13-btn" onclick="game13AddPaste()">Adicionar texto</button><button class="game13-btn" onclick="document.getElementById('game13File').click()">Importar TXT/MD/JSON</button><button class="game13-btn" onclick="game13Clear()">Limpar biblioteca</button></div><input id="game13File" class="game13-file" type="file" accept=".txt,.md,.json,text/plain,application/json" onchange="game13ImportFile(this.files[0])"><div class="game13-result"><b>Uso narrativo</b><small>Quando houver material importado, os trechos mais relevantes podem ser anexados ao contexto enviado ao Gemini. O motor local continua sendo a autoridade mecânica.</small></div>`}
function game13RenderParty(){const el=document.getElementById('game13Party');if(!el)return;const npcs=game13Npcs();el.innerHTML=`<div class="section-cap">Companhia & contatos</div><div class="game13-card orn-card"><span>Quem acompanha ou está ligado ao grupo</span><div class="game13-party">${npcs.map(n=>{const on=game13.party.includes(n.name);return`<div class="game13-member"><div><b>${game13Esc(n.name)}</b><small>${game13Esc(n.role)} • ${game13Esc(n.location)} • ${game13Esc(n.status||'')}</small></div><button class="${on?'on':''}" onclick="game13ToggleParty('${game13Esc(n.name)}')">${on?'Na companhia':'Adicionar'}</button></div>`}).join('')||'<div class="game12-empty">Nenhum contato disponível.</div>'}</div></div>`}
function game13RenderHome(){const el=document.getElementById('game13Home');if(!el)return;const active=game13.party.length,ctx=game13.docs.length;el.innerHTML=`<div class="game13-card orn-card"><span>Base do VTT</span><b>Companhia ${active} • Biblioteca ${ctx} trechos</b><small>O jogo agora mantém relações do grupo e uma base textual local para apoiar o Mestre/Gemini.</small><div class="game12-actions"><button onclick="game13Open()">Abrir biblioteca</button><button onclick="game12Go('personagem')">Ver companhia</button></div>${ctx?`<div class="game13-context">Referências importadas disponíveis para busca e contexto narrativo.</div>`:''}</div>`}
function game13RenderAll(){game13Inject();game13RenderLibrary();game13RenderParty();game13RenderHome();game13Save()}
function game13Open(){game13Inject();game13RenderLibrary();document.getElementById('game13Overlay')?.classList.add('open')}
function game13Close(){document.getElementById('game13Overlay')?.classList.remove('open')}
function game13DoSearch(){const q=document.getElementById('game13Query');game13.lastSearch=q?.value.trim()||'';game13Save();game13RenderLibrary()}
function game13AddPaste(){const t=document.getElementById('game13Paste');const text=t?.value.trim()||'';if(!text)return;if(game13.docs.length>220){alert('A biblioteca local atingiu o limite desta prévia.');return}game13.docs.push(...game13Chunk(text,'Referência manual'));game13Save();t.value='';game13.lastSearch='';game13RenderAll();if(typeof toast==='function')toast('Referência adicionada à biblioteca.')}
function game13ImportFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{let text=String(r.result||'');if(file.name.toLowerCase().endsWith('.json')){try{const j=JSON.parse(text);text=typeof j==='string'?j:JSON.stringify(j,null,2)}catch(e){}}game13.docs.push(...game13Chunk(text,file.name));if(game13.docs.length>220)game13.docs=game13.docs.slice(-220);game13Save();game13RenderAll();if(typeof toast==='function')toast(`${file.name} importado.`)};r.readAsText(file,'utf-8')}
function game13Clear(){if(!confirm('Limpar a biblioteca local de referências?'))return;game13.docs=[];game13.lastSearch='';game13Save();game13RenderAll()}
function game13ToggleParty(name){const i=game13.party.indexOf(name);if(i>=0)game13.party.splice(i,1);else game13.party.push(name);game13Save();if(typeof gameLog==='function')gameLog('party',i>=0?`${name} saiu da companhia`:`${name} entrou na companhia`,'Estado do grupo atualizado.');game13RenderAll()}
function game13HookGemini(){if(window.__game13GeminiHooked)return;if(typeof g11Ctx!=='function')return;window.__game13GeminiHooked=true;const old=g11Ctx;window.g11Ctx=function(action=''){const c=old(action);const query=[action,c?.terrain,c?.feature,c?.poi,c?.objective?.title||c?.objective||''].filter(Boolean).join(' ');const ref=game13Context(query);if(ref)c.rulesContext=ref;c.party=game13.party.slice();return c}}
function game13Hook(){if(window.__game13Hooked)return;window.__game13Hooked=true;try{if(typeof showView==='function'){const old=showView;showView=function(v){old(v);requestAnimationFrame(game13RenderAll)}}}catch(e){}setInterval(game13HookGemini,800)}
function game13Init(){game13Hook();game13HookGemini();game13RenderAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',game13Init);else game13Init();
